.github/workflows/mypy.yml

I noticed that some of the type annotations are violated an ran the mypy typechecker to see what else might be broken. I think it'd be a good idea to fix the obvious errors, try to improve annotations and mark the remaining errors as to-be-ignored. To continually test for type errors this PR adds a GitHub Action that runs mypy for every PR and push. [Here's the output of this PR.](https://github.com/sgeisler/lnbits/runs/616864506?check_suite_focus=true)
Once the project gains some tests these can be run automatically using actions too (through e.g. a second workflow step).

Add type checking CI

---

lnbits/core/static/js/wallet.js

This adds the possibility to paste or scan an invoice (on "SEND") even if the payment request is prefixed by "lightning:" or "bitcoin:" (as per recommendation in https://github.com/lightningnetwork/lightning-rfc/blob/master/11-payment-encoding.md) which some wallets (e.g. eclair) do.
fix #17
I would suggest to squash on merge (or should I do it manually?)

Allow lightning scheme

---

.travis.yml

As a quickfix to make travis happy we'll use an empty LNPay wallet as backend in tests. This should be replaced with a mock backend later on.

Use LNPay backend for CI

---

docs/_config.yml

Currently the HTTPS version of lnbits.org looks like this when loaded over HTTPS:
This seems to be due to loading assets over HTTP, which browsers rightfully block. This PR intends to fix this by using a HTTPS base URL.

Use https in base url to avoid mixed content

---

lnbits/extensions/withdraw/static/js/index.js

`location.host` contains the hostname and the port while `location.hostname` is only the hostname.
Should fix #46.

Update index.js to include port in links

---

lnbits/extensions/withdraw/templates/withdraw/print_qr.html

Make sure the schema (e.g. HTTPS) is included correctly from the request.

fix https being stripped from QRCodes when showing print view

---

.env.example

The name of the flask app has changed and the word "all" has been eliminated as unnecessary because allowing anyone to use lnbits is the default.

Update .env.example due to recent changes

---

lnbits/app.py
lnbits/core/crud.py
lnbits/core/services.py
lnbits/core/views/api.py
lnbits/db.py

It was bothering me a lot that any error from any wallet backend left our database in an unfixable situation, with a pending payment that wasn't really pending but we couldn't cleanup because we weren't sure.
There were also other potential bugs and race conditions that could be caused by not wrapping these sequential database calls into transactions,
This approach works, but I'm not sure it correct from the Flask level.

Transactions

---

lnbits/app.py

This was prepared but the command was not registered.
It is be needed for production installations were we use gunicorn to run the server.
Both `quart migrate` and `quart assets` should be called before using gunicorn.

fix: register `assets` command

---

lnbits/core/templates/core/wallet.html

This adds a QRcode of the "url_root/wallet?usr=#####&wal=####" so that
the user can create a wallet on desktop and easily use it on his phone.
Also, in a use case where the User Manager extension is used, the
manager can create a wallet and show the QRcode for the user to take it
(e.g. in a hotel front desk the clerk creates it and the user takes it
in his phone browser, to pay for laundry, massage, soda machine...)

Display QRcode for easy wallet export

---

.github/workflows/on-push.yml
Dockerfile

This PR follows a discussion with @arcbtc on Telegram. It improves the `Dockerfile` and adds a new workflow to automatically build the `lnbits` image, tag it with the short commit hash, and push it to Docker Hub. It is triggered on push to `master`.
The workflow (GitHub Action) needs the following repository secrets:
- `DOCKER_USERNAME`: Docker Hub username hosting the repository images.
- `DOCKER_PASSWORD`: Docker Hub access token 
This will allow a better LNbits integration on Umbrel (@getumbrel).
w/ @lukechilds

Improved Dockerfile and auto build lnbits image on commit

---

Dockerfile

This change creates the Dockerfile with the appropriate filesystem permissions to be executed as a non-root user. This is a requirement for Umbrel.
It's also changed to run as non-root by default.
You can still optionally run the container as root just like before with `docker run --user root lnbits`.

Run Dockerfile as non-root user

---

lnbits/templates/base.html

Added head meta tags to base.html. Allows you to save from browser to homescreen. When you click on "App", lnbits will launch fullscreen. Tested on android. Added bonus of masking the url!

added meta-tags to base.html to allow fullscreen app launch on mobiles.

---

lnbits/extensions/watchonly/crud.py
lnbits/extensions/watchonly/templates/watchonly/index.html
lnbits/extensions/watchonly/views_api.py
requirements.txt

This PR adds:
- Bitcoin descriptors support including miniscript (with bump of embit library to v0.2.1)
- Detection of the network (mainnet or testnet) depending on the xpub / tpub that is used
- Fixes first address derivation (it was derived with index=1, so first address with index 0 was always skipped)
- Supports origin fingerprint and derivation in the Bitcoin Core-like style: [fingerprint/derivation]xpub - will be useful for PSBT later on
It also adds some checks for xpubs provided to the watchonly extension:
- only xpubs with depth 3 are allowed (standard for bip44, 49 and 84)
- private keys are not allowed
- descriptors can use any derivations because we assume that people using descriptors understand what they are doing
If descriptors or miniscript support is not needed I can …

add descriptor support, more checks of user input

---

docs/devs/installation.md

The missing data folder will throw an exception:
`sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file`

Add missing instruction to dev installation guide

---

lnbits/extensions/streamalerts/templates/streamalerts/index.html
lnbits/extensions/streamalerts/views_api.py

This fixes two bugs with the Stream Alerts extension.
The first bug prevents donations from showing up in `index.html`. This has now been fixed and more important information is included in the table as well.
The second bug leads do empty name fields for donations, which might cause issues with the Streamlabs API. The name now gets set correctly to "Anonymous."
Edit: I'm pretty sure I fixed this like three weeks ago, but I must have dreamt that or something, as I couldn't find the code anywhere haha. Reimplemented the fix and tested the whole donation process again. No-name+no-message donations go through smoothly.

Stream Alerts: Fix donations table and default donor name "Anonymous"

---

lnbits/core/templates/core/wallet.html

Both amount and memo are required by the API, but only the amount field is marked as such in the UI. This commit also marks the memo field as required.

Create Invoice popup: Mark memo field as required

---

lnbits/core/views/api.py

This fixes two issues with sending to lightning addresses:
1. Lightning addresses with subdomains (like [ln.fitti.io](https://ln.fitti.io)) caused an `invalid lnurl` 400 error
1. Usernames were case sensitive (the spec only allows lowercase https://github.com/fiatjaf/lnurl-rfc/commit/3363ce9e4e274b37c0432d5132f5837197567270)

Fix Lightning Address issues (handle subdomains, enforce case insensitivity)

---

docs/guide/installation.md

"Additional guides," and the clearnet guide, were accidentally added twice.
Or they have become sentient and are multiplying.

Remove duplicate

---

lnbits/utils/exchange_rates.py

fix price conversion for Colombian Peso COP #327
1 COP is less than 1 sat, it was getting parsed as 0.

Fix issue #327

---

lnbits/core/views/api.py

In function api_payments_create_invoice() the line:
> if g.data.get("unit") or "sat" == "sat":
Was being interpreted as
> if g.data.get("unit") or ("sat" == "sat"):
Which is always true, resulting in the selected unit being ignored.
Replace with:
> if (g.data.get("unit") or "sat") == "sat":
Which results in intended behavior.

api: Fix order of operations causing invoice unit to be ignored

---

lnbits/wallets/void.py

fix voidwallet sys.exit
LNbits no longer crashes when using VoidWallet. It gives out a bunch of terminal errors but UI runs without crash.
#340

Fix issue #340

---

docs/guide/installation.md

Moved line which prompts user to try Lnbits with VoidWallet. Temporarily solves #340 if running with VoidWallet is not allowed

Fix misleading instruction about VoidWallet

---

lnbits/extensions/lndhub/views_api.py

The lndhub extension currently returns a "bad auth" error on the /getinfo call.
Ideally we respond with the exact same JSON as LndHub, but we might not have all that information. 
Still we should at least return a valid response here.

Return a valid getinfo JSON response in the lndhub extension

---

lnbits/core/services.py

This one is critical but possibly not the most elegant way to fix it. 
Problem: 
* The entire `pay_invoice` routine was in the database with block (`async with (db.reuse_conn(conn) if conn else db.connect()) as conn`). However, the database access isn't concurrent. When the payment takes a long time, this can lead to the entire instance getting stuck until the payment is resolved. If the payment takes longer than the timeout of the wallet interface, this can lead to "big problems".
Fix: 
* Open (and lock) the database only immediately before it is written to, avoiding a locked state while the payment is being attempted.  
Comments:
* I could not use `db.reuse_conn(conn)` because the connection closes after the `with` block. Now, it `.conenct()`'s every time the db is accessed again. …

Fix DB Lock: open database only when reading and writing to it

---

lnbits/extensions/usermanager/views_api.py
mypy.ini

* Renamed endpoint to `/api/v1/wallets/<wallet_id>`  `/api/v1/transactions/<wallet_id>` to avoid collision with `/api/v1/wallets/<user_id>`.

Fix UserManager endpoint collision (master)

---

lnbits/core/services.py
lnbits/core/views/api.py
lnbits/wallets/lndrest.py

Adds `fee_limit` to the the payment.
Policy: 
```python
if invoice.amount_msat > 1000_000:
lnrpcFeeLimit["percent"] = "1"  # in percent
else:
lnrpcFeeLimit["fixed"] = "10"  # in sat
```
What changed?
1) Add `fee_limit`. 
2) When payment fails, delete temporary DB entry. Why didn't we do this before? 
3) `check_invoice_status` in `api.py` (`/api/v1/payments`) now `exclude_uncheckable=True`. This excludes DB entries with the `temp_` prefix, that can't be checked (and probably should not be checked?).

LNDRest fee limit

---

lnbits/core/services.py
lnbits/wallets/base.py
lnbits/wallets/clightning.py
lnbits/wallets/lnbits.py
lnbits/wallets/lndgrpc.py
lnbits/wallets/lndrest.py
lnbits/wallets/lnpay.py
lnbits/wallets/lntxbot.py
lnbits/wallets/opennode.py
lnbits/wallets/spark.py
lnbits/wallets/void.py

I was challenged by callebyc so here is my very first PR ever.
- The fee limit is now determined from `fee_reserve()` and passed to WALLET.pay_invoice(), to ensure maintaining fee limit = fee reserve (otherwise it may cause a vulnerability).
- This fee limit is now implemented in `LndRestWallet`, `LndWallet` and `CLightningWallet` (here the 0.5% default fee limit is being overwritten).
Thanks for your feedback and to Kixunil for his guidance.

United fee limit

---

lnbits/core/services.py

Doesn't have reason to reserve 2% of the payment on internal payments, since there's no routing fees.

2% reserve only for external payments

---

lnbits/extensions/subdomains/crud.py

i talked to @grmkris via email, and something fishy is going on with cloudflare api also. im looking into it now.
fix sql error: 
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable)
relation "domain" does not exist
LINE 1: ...omain_name FROM subdomains.subdomain s INNER JOIN domain d O...
[SQL: SELECT s.*, d.domain as domain_name FROM subdomains.subdomain s
INNER JOIN domain d ON (s.domain = d.id) WHERE s.id = %s]

Extension Subdomains: Update crud.py, critical sql error

---

lnbits/core/views/api.py
lnbits/utils/exchange_rates.py

small upgrade to conversion endpoint to allow fiat -> sats and sats -> fiat
also allow to pass a list of currencies to get converted
updated data schema:
`{unit: <string defaults to 'sat'>, amount: <float>, to: <string defaults to 'usd'>}`
sats -> fiat
`{"amount": 30000, "to": "eur, gbp"}`
fiat -> sat
`{"amount": 10, "unit": "eur"}`

Upgrade conversion endpoint

---

.env.example
Pipfile
Pipfile.lock
docs/guide/wallets.md
lnbits/wallets/lndgrpc.py
lnbits/wallets/lndrest.py
lnbits/wallets/macaroon/__init__.py
lnbits/wallets/macaroon/macaroon.py
requirements.txt

This PR adds support for AES-256 encrypted macaroons using `pycryptodomex`. The encryption scheme is compatible with the Javascript library `CryptoJS/aes`. Only the LND backend is supported.
There is a new directory `lnbits/wallets/macaroon` that holds functions for loading macaroons, determining their encoding, and a new class `AESCipher` for de- and encrypting macaroons.
User adds an encrypted version of the macaroon in the `.env` file as `LND_GRPC_MACAROON_ENCRYPTED` or `LND_REST_MACAROON_ENCRYPTED`. If these are set, they will overwrite other unencrypted macaroon settings. Opon start, LNBits will ask for the decryption password and decrypt the macaroon. If the password is wrong, an error is returned. The decrypted macaroon is kept in RAM only.
You have two options: You can encrypt the …

Support for encrypted macaroons

---

lnbits/core/crud.py
lnbits/extensions/lndhub/views_api.py

**Description**
* This PR adds a `limit` clause to the `get_payments` crud in order to ... limit the number of payments to receive from the db. 
* This is necessary since the `lndhub` extension used to requests all payments of a user and just sliced returned list (very inefficient). 
* The default number of tx's to receive is set from 200 to 20, because more is usually not needed and the client can still request more if they like. 
* It also removes the unnecessary `delete_expired_invoices()` which went through _all_ invoices and checked with the backend previously. 
**Comments:**
* Add pagination to the crud as well? This would certainly come handy for the web interface which does not need to fetch all transactions if they are not shown anyway. 
**Todo:**
**Info:** Ready to merge!

LNDHhub for fastapi with LIMIT

---

lnbits/core/templates/core/_api_docs.html
lnbits/core/templates/core/wallet.html
lnbits/core/views/api.py

This PR fixes two fiat unit bugs:
* Units were `int()` so 2.30€ == 2€ but nobody seems to have noticed until now 🤷.
* Amount was necessarily `> 1` irrespective of the unit, which means that `$0.25` invoices failed to be created.
Extra:
* The label of the invoice creation dialog changes based on the selected unit (I am very proud of this)
* Allow the creation of invoices without a memo (which is what the UI hints at). Defaults to "LNbits".
* Input changes to '#.##' if a fiat currency is selected.
Todo:

Fix fiat amount entry in invoice creation

---

lnbits/wallets/lndrest.py

This PR adds a fallback to the `LND_REST_CERT` variable. If the user is using the `LndRestWallet` provider but does not supply the `LND_REST_CERT` variable, then LNBits will fallback to using the system's root certificate chain to validate the node's certificate.

Add support for the system's cert chain in LndRestWallet

---

lnbits/core/views/api.py

Conversion to satoshis incorrectly used data.to as fiat currency rather
than data._from.
Note: The api currently assumes you are either converting to or from satoshis. This could be fixed to allow arbitrary conversions, so I will add that if needed.

api: Fix conversion from fiat to satoshis

---

lnbits/app.py

Retry the connection to the backend every 5 seconds if the connection fails. Before, we used to `sys.exit(4)`.
This is useful for Umbrel users who don't use a proper systemd startup chain like a normal person, which means that lnbits doesn't know when lnd is actually ready (and unlocked) to receive connections.

Retry backend connection on startup

---

docs/devs/installation.md

When I tryed to run "pipenv install --dev" on a Pi 4 with the latest Raspberry OS it failed with two dependencies. These additional installations fixed it.

added "missing" libffi/libpq package

---

.github/workflows/mypy.yml
lnbits/core/services.py
lnbits/wallets/base.py
lnbits/wallets/clightning.py
lnbits/wallets/fake.py
lnbits/wallets/lnbits.py
lnbits/wallets/lndgrpc.py
lnbits/wallets/lndrest.py
lnbits/wallets/lnpay.py
lnbits/wallets/lntxbot.py
lnbits/wallets/opennode.py
lnbits/wallets/spark.py
lnbits/wallets/void.py
tests/extensions/bleskomat/test_lnurl_api.py
tests/mocks.py

Reimplements fee reserve from the commits that were lost in the FastAPI transition for `LndRestWallet` and `CLightningWallet`, originally implemented with the help of @iwarpbtc. 
Note: `LndWallet` (GRPC) also has a fee reserve implemented here but the wallet has been phased out for now. Issues that remain were the check for the status after a successful payment. 
12 File changes because `pay_invoice` of every wallet has now the (often unused) argument `fee_limit_msat`.

Fee reserve for lightning backends

---

lnbits/db.py

Ran into the issue of not having a `LNBITS_DATA_FOLDER` (default is `data`) set once too often when setting up LNBits - Maybe helpful for others too.
Without it the guard clause failure will happen later when trying to open the database files:
```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
```
Keep up the great work!

fail early if LNBITS_DATA_FOLDER missing

---

lnbits/utils/exchange_rates.py

As mentioned in #573 we would be happy if you add the Iranian Toman Currency. Blue wallet also uses this [api](https://api.exir.io/v1/ticker?symbol=btc-irt) for IRT.

add IRT api

---

lnbits/extensions/tpos/templates/tpos/index.html

hi,
two days ago, @lilcheti added IRT to "exchange_rates.py". I noticed that the "TPos" extension does not have IRT currency in its list. So I added it.

add "IRT" currency to TPos extention

---

lnbits/core/crud.py
lnbits/tasks.py

This PR fixes webhooks for internal payments.
The bug was reintroduced by [this PR](https://github.com/lnbits/lnbits-legend/pull/500) which reverted the fix because it probably caused problems at some other point. I've put the fix back in but now only if an optional flag `get_standalone_payment(..., internal=True)` is used. This should make sure that this change doesn't affect anything but the webhook (which uses `internal=True`).
The reason why this bug is there in the first place is mildly interesting: `get_standalone_payment` always fetched the first row in the database it finds. If two payments have the same hash (which is the case for internal payments) it is only going to fetch the outgoing payment (with negative amount). This payment however does not (and is not supposed to) fire a …

Core: fix internal webhooks

---

lnbits/extensions/lnurlp/crud.py
lnbits/extensions/lnurlp/lnurl.py
lnbits/extensions/lnurlp/migrations.py
lnbits/extensions/lnurlp/models.py
lnbits/extensions/lnurlp/views_api.py

Allows for creation of floating point fiat values in lnurlp links (such as 0.25 EUR).
Fixes #662.

lnurlp: support for floating point fiat values

---

lnbits/app.py

Apparently, a browser always includes `text/html,application/xhtml+xml,application/xml` in the "Accept" header (unless a user is messing with the kind of headers the browser sends). 
Main goal here is, check if the request is coming from a browser and send the error.html, else send a JSON response with the error.
Tested with CURL, Firefox and Chrome! Working as expected...

Fix HTML response to non browser request

---

lnbits/core/views/api.py

Extends the API call GET `/api/v1/payments` with two optional query parameters `limit` and `offset`
Example: `/api/v1/payments?limit=20&offset=2`

/api/v1/payments with limit and offset

---

lnbits/tasks.py

PR fixes two bugs:
* Check for expired invoices regularly, instead of only upon startup.
* Expired invoices should only be deleted after one pending check. The backend could have been offline for a very long time and expired invoices could have been paid in the mean time.

Delete expired invoices after one pending check

---

lnbits/extensions/tpos/__init__.py
lnbits/extensions/tpos/config.json
lnbits/extensions/tpos/crud.py
lnbits/extensions/tpos/migrations.py
lnbits/extensions/tpos/models.py
lnbits/extensions/tpos/tasks.py
lnbits/extensions/tpos/templates/tpos/index.html
lnbits/extensions/tpos/templates/tpos/tpos.html
lnbits/extensions/tpos/views.py
lnbits/extensions/tpos/views_api.py

This PR adds new functionality to the TPOS extension. 
- Add new tip % option to TPOS extension.      
- When adding a new TPOS, a user can choose 1 or more tip % options to be displayed to the customer.
- When adding a new TPOS, a user can choose a wallet to send all collected tips to.
- Demo Image:
- UI Refresh on TPOS extension.
- Moved the share button to the top navigation, next to the TPOS name, and changed the icon to a more recognizable one.
- Re-arranged the buttons on the keypad to be more ergonomic.
- Added Progressive Web App (PWA) support for the terminal page.
- Demo image:

Enhancements to TPOS Extension

---

lnbits/extensions/copilot/templates/copilot/_api_docs.html
lnbits/extensions/jukebox/templates/jukebox/_api_docs.html
lnbits/extensions/livestream/templates/livestream/_api_docs.html
lnbits/extensions/lnaddress/templates/lnaddress/_api_docs.html
lnbits/extensions/lnurldevice/templates/lnurldevice/_api_docs.html
lnbits/extensions/lnurlp/templates/lnurlp/_api_docs.html
lnbits/extensions/offlineshop/templates/offlineshop/_api_docs.html
lnbits/extensions/paywall/templates/paywall/_api_docs.html
lnbits/extensions/satsdice/templates/satsdice/_api_docs.html
lnbits/extensions/satspay/templates/satspay/_api_docs.html
lnbits/extensions/splitpayments/templates/splitpayments/_api_docs.html
lnbits/extensions/tpos/templates/tpos/_api_docs.html
lnbits/extensions/watchonly/templates/watchonly/_api_docs.html

The move to FastAPI changed the API URLs. This change updates the example URLs for LNbits extensions

Corrected example CURL requests in multiple extension API docs

---

lnbits/static/scss/base.scss

Added line wrapping for text in code examples to make it readable on normal sized screens

Added line wrapping for text in code examples

---

.github/workflows/tests.yml
Makefile
docs/devs/development.md
lnbits/core/crud.py
lnbits/core/views/api.py
tests/conftest.py
tests/core/views/test_api.py
tests/core/views/test_generic.py
tests/core/views/test_public_api.py
tests/extensions/bleskomat/conftest.py
tests/extensions/bleskomat/test_lnurl_api.py
tests/mocks.py

This PR has several improvements for automated testing:
* New PostgreSQL testing pipeline
* Measure code coverage and upload to codecov
* Fix a bug* in `api_payment` that only appears with sqlite.
_*Details about the bug:_
`api_payment` or `GET /api/v1/payments/{payment_hash}` can be used with or without the invoice key of the owner of the payment. If no valid key is provided, it returns no payment details via `get_standalone_payment`, otherwise it does.  For internal payments, the backend created two entries, one debit and one credit. Both of these payments have the same `payment_hash` which can lead to a collision when `get_standalone_payment` looks up the payment. This was never noticed because the database used (sqlite) has always put the transactions in a deterministic order. …

Testing: postgres db backend

---

lnbits/wallets/spark.py

Minimizes the risk of stuck payments due to timeouts in `spark` backend.
* Timeout for `WALLET.call` increased from 40s to 24 hours. 
* `requests.raise_for_status()` added to `WALLET.call`
* catch `httpx.TimeoutException` in `WALLET.call`
* catch `httpx.HTTPError` in `paid_invoices_stream`

Spark: increase timeout and improved error handling

---

lnbits/core/services.py
lnbits/core/templates/core/_api_docs.html
lnbits/core/views/api.py
lnbits/settings.py
lnbits/wallets/fake.py
tests/core/views/test_api.py

When using a lightning backend, every invoice is created by a backend node, even if those invoices are meant to be paid only internally (user-to-user transfer). This creates unnecessary data on the backend's end. 
@arcbtc has coded up the `FakeWalelt` which can act as a backend replacement. 
This adds a new flag `internal=True` to the `data` field of `api_payments_create_invoice()` which forces the use of `FakeWallet` even if another wallet is chosen for regular use. 
Tested.

Core: add internal flag for invoice creation to use FakeWallet

---

lnbits/extensions/usermanager/views_api.py

Requests to `POST /usermanager/api/v1/extensions` would silently fail due to a missing `await`.

error in `/usermanager/api/v1/extensions`

---

lnbits/wallets/fake.py

`FakeWallet`: do not mark payments as failed

---

lnbits/extensions/withdraw/static/js/index.js

* [This](https://github.com/fiatjaf/lnurl-rfc/pull/66#issuecomment-868407854=) says you should use `lnurlw:`
* [This](https://github.com/fiatjaf/lnurl-rfc/blob/luds/17.md) says you should use `lnurlw://`
* Wallet of Satoshi parses `lnurlw://abc` to `//abc`
* Breez can handle it all
* I'm gonna use `lightning:` because I got mad.

LNURLw: change prefix to `lightning:` until wallets fix their bugs

---

lnbits/extensions/lnurlp/static/js/index.js
lnbits/extensions/lnurlp/templates/lnurlp/display.html
lnbits/extensions/lnurlp/templates/lnurlp/index.html
lnbits/extensions/withdraw/static/js/index.js

This PR is based on #725 and enables NFC writing support for LNURL-pay links from the browser (Chrome on Android) with a simple click of a button (screenshot).

LNURLp: Write NFC tags with LNURL-pay links

---

.github/workflows/regtest.yml
.github/workflows/tests.yml
Pipfile
Pipfile.lock
docs/guide/installation.md
lnbits/core/views/generic.py
requirements.txt
tests/conftest.py
tests/core/views/test_api.py
tests/core/views/test_generic.py

* Update `httpx` to `0.23.0` and `http-core` to `0.15.0` in `venv` installation path
* Fix `secp256k1 = "==0.14.0"` and `cffi = "==1.15.0"`
* Adds tests for 
```
GET /wallet
http://127.0.0.1:5000/wallet?usr=1
http://127.0.0.1:5000/wallet?usr=5a30834dcfe64e41a2ec217f36ee5902
http://127.0.0.1:5000/wallet?usr=5a30834dcfe64e41a2ec217f36ee5902&wal=73f3a9457c834343bcf82c908946e2a2
http://127.0.0.1:5000/wallet?usr=5a30834dcfe64e41a2ec217f36ee5902&wal=1
```
and checks whether URL forwards are the way they are supposed to be when creating a new wallet.

CI: Test `core/views/generic.py`

---

README.md
lnbits/core/views/generic.py
tests/core/views/test_generic.py

* Check whether extension exists before enabling/disabling (in `core/views/generic.py`)
* Tests
```
GET /extensions
GET /extensions?usr=1
GET /extensions?usr=1a02ca2c80bd8492396cd2803bb74d8b8
GET /extensions?usr=1a02ca2c80bd8492396cd2803bb74d8b8&enable=lnurlp
GET /extensions?usr=1a02ca2c80bd8492396cd2803bb74d8b8&enable=lnurlp&disable=lnurlp
GET /extensions?usr=1a02ca2c80bd8492396cd2803bb74d8b8&enable=wrong_extension
```

CI: Test `core/views/generic.py` enabling and disabling extensions

---

lnbits/extensions/tpos/templates/tpos/tpos.html

fix the JSON.parse of the tip_options when null (for example the older tpos created )!

fix older tpos without tips

---

.github/workflows/regtest.yml

recent PR of legend-regtest-enviroment does not include lnbits anymore, so we dont need to build it inside the regtest setup workflow anymore.
https://github.com/lnbits/legend-regtest-enviroment/pull/4

faster regtest, docker build is not needed anymore

---

lnbits/bolt11.py
lnbits/jinja2_templating.py

warning in bolt11.py:
`DeprecationWarning: invalid escape sequence \d`
warning in jinja:
`DeprecationWarning: 'contextfunction' is renamed to 'pass_context', the old name will be removed`

fix test warnings when using < python3.8

---

lnbits/core/templates/core/wallet.html

change z-index of the wallet tabs (on mobile) to not be on top of notifications!
z-top instead of z-max

change z-index for wallet tab

---

lnbits/bolt11.py
tests/conftest.py
tests/core/views/test_api.py

This is the first PR of the Mega-merge series. The ultimate goal of the Mega-merge series it to use updated CLN and LND libraries and fix the use of `description_hash` for all wallets (which ultimately enables LNURL).
The Mega-merge series is separated into following parts in order to avoid total chaos and make review easier. All successive PRs have their predecessor merged into them already which is why the number of changed files is deceivingly large for the later PRs (they should go down as we merge one by one). 
Dependency graph:
```
┌───┐
Tests    Refactor   ┌─┤MM3│ CLN
┌────┐     ┌───┐    │ └───┘
│MM1 ├─────►MM2├────►
└────┘     └───┘    │ ┌───┐
└─┤MM4│ LND
└───┘
```
The purpose of this (present) PR is to add tests for invoice creation via the endpoint `/api/v1/payments` with …

Mega-merge 1: Test invoice creation with description hash (WIP)

---

lnbits/extensions/withdraw/templates/withdraw/print_qr_custom.html

Make the custom designed vouchers QR have the instant wallet capability, when scanned with a normal QR scanner!

make instant wallet available in custom vouchers

---

nix/modules/lnbits-service.nix

Without this, evaluating the module doesn't provide a default value visible on search.nixos.org
This is needed to merge https://github.com/NixOS/nixos-search/pull/510

nix: add defaultText to services.lnbits.package

---

build.py
lnbits/commands.py
lnbits/server.py

* Respects `HOST` and `PORT` in `.env` if no arguments are given
* Parses all other arguments and makes them so that uvicorn gets it
* Removes old code from `build.py`
Examples:
```sh
~/git/lnbits-legend(branch:poetry-env*) » poetry run lnbits --help                                                                        cc@ddd
Usage: lnbits [OPTIONS]
Launched with `poetry run lnbits` at root level
Options:
--port INTEGER       Port to listen on
--host TEXT          Host to run LNBits on
--ssl-keyfile TEXT   SSL keyfile
--ssl-certfile TEXT  SSL certificate
--help               Show this message and exit.
```
And passing arbitrary arguments that will be piped to `uvicorn`:
```sh
poetry run lnbits --host 0.0.0.0 --port 5000 --ssl-keyfile ./localhost+2-key.pem --ssl-certfile ./localhost+2.pem …
```

Poetry: uvicorn with .env and command line arguments

---

docs/devs/extensions.md
tools/conv.py

`conv.py` handles the conversion of a `SQLite` DB to a `Postgres` one.
The previous version of the script handled each extension individually, which required some extra work when adding/updating and extension.
The current implementation queries the `SQLite` DB for table names and columns and builds all the conversion scripts automatically.
It also allows to:
- exclude extensions from conversion (eg: `ext_lnurlpos`)
- exclude table from migration (eg: `dbversions`)

Generalize `conv.py`

---

.github/workflows/regtest.yml

this pr adds building of the docker image into regtest tests again before using it inside the regtest for lnbits funding source tests

fixing regtest, using lnbits again

---

.github/workflows/regtest.yml
lnbits/core/views/api.py

Tiny change that returns in `/api/v1/payments` an `HTTPStatus.UNAUTHORIZED` error if the key is missing. 
Same as in other instances where `require_invoice_key` is used.

return http error UNAUTHORIZED instead of BAD_REQUEST if key is missing

---

lnbits/app.py

this fixes issue https://github.com/lnbits/lnbits-legend/issues/652
it works by using its own signal handler, overwriting the default one for the duration of the backend wallet initialisation. after the wallet is initialised, it restores the default uvicorn handler.

stuck in retrying backend loop, fix issue #652

---

lnbits/app.py
lnbits/extensions/copilot/lnurl.py
lnbits/extensions/livestream/lnurl.py
lnbits/extensions/lnurldevice/lnurl.py
lnbits/extensions/lnurlp/lnurl.py
lnbits/extensions/offlineshop/lnurl.py
lnbits/extensions/satsdice/lnurl.py
lnbits/wallets/cln.py

Recently, the backends were update to support `unhashed_description` as well, so we can make CLN happy. 
This PR also changes how the rest of LNbits sends rather `unhashed_description` so it can work with CLN.
For LNURL stuff, provide `unhashed_description` instead of `description_hash`

Lnurlp: use `unhashed_description` instead of `description_hash`

---

lnbits/extensions/tpos/crud.py
lnbits/extensions/tpos/models.py
lnbits/extensions/tpos/templates/tpos/tpos.html
lnbits/extensions/tpos/views_api.py

This PR adds NFC support to the TPOS extension, enabling payment to be collected via NFC tags that contain LNURLw strings (both raw and SUN authenticated via LNBits Bolt Cards extension).

Add NFC support to TPOS Extension

---

lnbits/extensions/tipjar/crud.py

fixes #831 by enforcing the deletion of tips first and then the tipjar, as postgres enforces the foreign key constrains!

Hotfix: delete tips first, on Tipjar Ext

---

docs/guide/installation.md

Fly.io is a neat hosting provider that takes a docker container and runs it for you. They have a generous free tier that is enough to run LNBits w/ sqlite. This PR is just some docs on how to do it.

Add docs for hosting LNBits on Fly.io (for free)

---

.github/workflows/regtest.yml

this helps simplifying the regtest setup.
if we do not want to rebuild the docker image.
it is basically removing this comment, https://github.com/lnbits/legend-regtest-enviroment/blob/main/docker-compose.yml#L11

change docker image name for regtest tests

---

lnbits/extensions/boltcards/static/js/index.js
lnbits/extensions/boltcards/templates/boltcards/index.html

How it was before is better, as people know nfc functionality exists. It pushes them to use the right browser

Reverted nfc button not showing

---

lnbits/extensions/watchonly/models.py

Column `type` has no default value (eg: `''`).
The model must accept `None`.

fix: type can be `None` due to migration issue

---

lnbits/extensions/copilot/views.py

APIRouter already has the route prefix!! 
Websockets for animations and tipping work as expected!

remove already added prefix ou route - ws working again

---

lnbits/extensions/lndhub/views_api.py

Remove the delays in gettxs and getuserinvoices calls to support wallets that use the lndhub extension.

lndhub: remove delays

---

lnbits/core/static/js/wallet.js

Got a QR (LNURLw) from General Bytes ATM which was upper-cased like `LIGHTNING:LNURL1XXXX` and ended up with the `Malformed request: checksum is incorrect` message from the invoice decoder when scanning it. So here's a little fix.

fix for uppercase QR

---

.env.example
poetry.lock
pyproject.toml

These are some small quality of life changes.
Only pyScss had to be updated to  make LNbits work with Python 3.10
The environs package was unable to parse boolean values as it included the comments at the end of each line in the calculations. For some reason it does work for some installations and for others it doesn't.

Updates and fixes

---

Makefile
tests/extensions/boltz/test_api.py

our github workflow tests, may have created swaps on boltz.exchange.
This PR makes sure, it is uses localhost api URL, even though they are not running because no regtest is running.
It is fine for the tests, they are expected to fail for boltz tests not in regtest.

make sure tests not spamming boltz live servers

---

poetry.lock

poetry lock got commited out of sync with pyproject.toml
`Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.`

fix poetry lock issue

---

.github/workflows/codeql.yml
.github/workflows/formatting.yml
.github/workflows/mypy.yml
.github/workflows/regtest.yml
.github/workflows/tests.yml

make github workflows only run on pull_request.
they run twice now in some cases.

make gh workflows only run on pull_request

---

lnbits/db.py
lnbits/extensions/boltcards/migrations.py
lnbits/extensions/boltz/migrations.py
lnbits/extensions/invoices/migrations.py
lnbits/extensions/lnurldevice/migrations.py
lnbits/extensions/lnurlpayout/migrations.py
lnbits/extensions/streamalerts/migrations.py
lnbits/extensions/tipjar/migrations.py

The amount in `sats` can be higher than the the `INT` type in postgres (2^32)
**Solution**:
- add the `big_int` property (simialr with `timestamp_now`)
**Note**:
- in Postgres `int8` is an alias for `BIGINT`
- expected_amount: `BIGINT`
- timeout_block_height: `INT`

fix: use bigint for amounts in postgres

---

lnbits/app.py

i changed the log of a successful backend connection from INFO to SUCCESS, looks better :), it is green now.

nicer logger formatting for successful backend connection

---

.env.example

This PR adds missing theme options in  `.env.example`:
- The `bitcoin` theme in the comment
- The `flamingo` theme in the list of values for `LNBITS_THEME_OPTIONS`

Adding missing theme options in conf example file

---

lnbits/core/views/api.py

Make /api/v1/lnurlscan  no longer require exactly 2 parts for name's domain split by "."
Payment to addresses like anton@bits.my-ns.me is now possible.

Allow more than 2-nd level domain in incoming ln-addresses

---

lnbits/core/static/js/wallet.js
lnbits/core/templates/core/wallet.html

camera now properly shows an error, if browser has no access to a camera or anything else is wrong with it.
Closes https://github.com/lnbits/lnbits/issues/1072

Proper Error Handling for qrcode-stream components

---

lnbits/extensions/withdraw/lnurl.py

If the lnurlw link was not found, the code would raise an `HTTPException` (line 97) which would in turn then trigger the `except` block in line 144, where the code tries to access the variable `changesback` which was still undefined. 
Now the `try: except:` block starts later.
Here is the full stack trace:
```bash
2022-10-26 09:52:16.95 | ERROR | lnbits.app:basic_error:197 | handled error
2022-10-26 09:52:16.95 | ERROR | lnbits.app:basic_error:198 | ERROR:
Traceback (most recent call last):
File "/root/fast/lnbits-legend/lnbits/extensions/withdraw/lnurl.py", line 97, in api_lnurl_callback
raise HTTPException(
fastapi.exceptions.HTTPException
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File …
```

LNURLw extension: refactor try except block

---

docs/guide/installation.md

A port is necessary for postgresql config. Add postgresql default port 5432 in documentation for LNBITS_DATABASE_URL config

Documentation for postgresql default port

---

.env.example

LNBITS_ALLOWED_USERS and LNBITS_ADMIN_USERS wants usr string from wallet url
List needs to be comma separated if used more than one user

Documentation improved in example env

---

lnbits/templates/base.html

added a API DOCS button linking to /docs swagger api docs into the footer toolbar.

API DOCS button in footer toolbar

---

lnbits/extensions/boltcards/templates/boltcards/index.html

It was written in the README, but I think it's better to warn in the UI as well. 
Missed it and lost a Boltcard in the process ;-)

Added warning to backup keys

---

lnbits/extensions/tpos/templates/tpos/index.html
lnbits/extensions/tpos/templates/tpos/tpos.html

Adds the option for a costumer to round the value to pay, as a tip.
Ex: amount is 1.25, costumer pays 2. 
0.75 is set as the tip and goes to selected tip wallet!

Add Rounding as tipping option

---

lnbits/server.py
lnbits/settings.py

running lnbits with `poetry run lnbits` did not take FORWARDED_ALLOW_IPS into account, so https was not working correctly

let poetry run lnbits recognize forwarded_allow_ips for https

---

lnbits/core/views/api.py

Currently the `unhashed_description` is discarded if `description_hash` is present (and vice-versa).
This results in the `"'description_hash' unsupported by CLN, provide 'unhashed_description'"` being thrown for a LNbits instance with a `CLightningWallet` back-end wallet. 
The current fix allows both `description_hash` and `unhashed_description` to be present at the same time.
**The call:**
```
curl --location --request POST 'https://legend.lnbits.com/api/v1/payments' \
--header 'x-api-key: xxxxxxxxxxxxxxxxxxxxxxxx' \
--header 'Content-Type: application/json' \
--data-raw '{
"out": false,
"amount": 3,
"description_hash": "4abe6ea61212e956ca0a3c81ea04d441527df9bd7674a6ee5113b53cf5fbb824",
"unhashed_description": "5b5b22746578742f706c61696e222c20225061796d656e7420746f206d6f746f72696e6130225d …
```

fix: allow both `description_hash` and `unhashed_description` to be present

---

lnbits/extensions/satspay/crud.py
lnbits/extensions/satspay/helpers.py
lnbits/extensions/satspay/migrations.py
lnbits/extensions/satspay/models.py
lnbits/extensions/satspay/static/js/utils.js
lnbits/extensions/satspay/tasks.py
lnbits/extensions/satspay/templates/satspay/display.html
lnbits/extensions/satspay/templates/satspay/index.html
lnbits/extensions/satspay/views.py
lnbits/extensions/satspay/views_api.py
lnbits/tasks.py

This PR contains several fixes and improvements.
- **fix**: on Charge page the tabs are disabled and a tool tip is shown (`...Payment Not Available`) even if the Charge is still active
- **fix**: the green checkmark is not shown after the payment is made (a page refresh was required)
- **fix**: `Webhook` not called by `task.py`
- now the `webhook` is called when the invoice is paid
- the status of the `webhook` call is persisted and shown to the user (see screenshot 1)
- if the `webhook` call is successful, then it is now assured that it will not be called a second time
- if the `webhook` call has failed, then it can be called again if the `Charge` page is refreshed
- **feat**: each charge persists its wallet config (mempool url, network) at the time of creation (for onchain charges)
- …

fix `staspay` webhook for LN payment

---

lnbits/extensions/satspay/crud.py
lnbits/extensions/satspay/models.py

Tipjar also has a `CreateCharge` class. The `extra` field has been added in `satspay` but not in `tipjar`.
This PR enforces the default vaues for the `satspay` `CreateCharge` class.

fix: force default value initialisation (tipjar fix)

---

lnbits/db.py

if `values` is `str` then `list(values)` will create a tuple where each character is an item:
```
7qGBzeL8gSYeFSWTiiCrL  ->  ('B', '7', 'q', 'G', 'B', 'z', 'e', 'L', '8', 'g', 'S', 'Y', 'e', 'F', 'S', 'W', 'T', 'i', 'i', 'C', 'r', 'L')
```

fix: do not apply `list()` to `str` value

---

lnbits/extensions/tpos/views_api.py

When TPOS is getting a lnurl response, it identifies itself via user-agent header. This identification can be then displayed (not only) in the boltcard extension. 
So let me know if this is a good idea or a bad idea.

TPOS identifies itself via user-agent

---

lnbits/core/views/api.py

This PR fixes the audit endpoint route from `/api/v1/audit/` to `/api/v1/audit` (removing the trailing `/`).

Fix: audit endpoint

---

lnbits/extensions/satspay/helpers.py
lnbits/extensions/satspay/static/js/utils.js
lnbits/extensions/satspay/templates/satspay/index.html

- store the response from the `webhook` call
- show the response to the user (click on the status badge)
Automatic tests can now check that the webhook call was made.

feat: store & show `webhook` response body for charges

---

lnbits/app.py
tests/core/views/test_generic.py
tests/extensions/boltz/test_api.py

Properly reports the last line of the exception in Error html (for browsers) and in the JSON response (for API calls) and prints the stack trace in the terminal.
Adds 3 FastApi error handlers:
* `Exception` for general exceptions
* `RequestValidationError` for Pydantic validation errors of input data
* `HTTPException` for any HTTP error we raise in the code via `raise HTTPException()`

Fix: FastApi exception handling and logging

---

lnbits/extensions/lnurlp/tasks.py

- **fix**: catch any exception when a `webhook` call fails
- for example adding a LNURLp callback invalid header (`{"h1": 1}`) was not caught 
- headers can only have string values, not ints
- feat: store the response `code`, `message` and `body`
- this can help later troubleshoot why the `webhook` call failed

LNURLp - save `webhook` call details

---

lnbits/core/crud.py
lnbits/core/views/api.py
lnbits/extensions/lnurlp/tasks.py
lnbits/extensions/withdraw/crud.py
lnbits/extensions/withdraw/lnurl.py
lnbits/extensions/withdraw/migrations.py
lnbits/extensions/withdraw/models.py
lnbits/extensions/withdraw/static/js/index.js
lnbits/extensions/withdraw/templates/withdraw/index.html

- add `webhook_body` and `webhook_headers` for `withdraw` callbacks
- store the the `webhook` response in `apipayments`.`extra` column

Withdraw webhook improvements

---

lnbits/extensions/satspay/crud.py
lnbits/extensions/satspay/views_api.py

**Steps**:
- go to `satspay` extension
- open `New Charge` dialog
- select `onchain` wallet (do NOT click `Create Charge` yet)
- in new tab:
- go to `watchonly` extension
- delete the account that the charge was pointing to
- back in the `satspay`  tab click `Create Charge`
**Actual Result**
- a technical error is shown: `NoneType' object has no attribute 'address'`
- there is an error stacktrace
**Expected Result**
- it fails with a user-friendly message: `Wallet '{onchainwallet}' can no longer be accessed.`
- no stacktrace

fix: onchain wallet deleted for charge

---

lnbits/core/crud.py
lnbits/extensions/lnurlp/tasks.py
lnbits/extensions/withdraw/lnurl.py

For internal payments there are two entries with the same `hash` in `apipayments`.
This caused the updated of `extra` to loose the previous set values if the wrong payment came first for `fetchone`
The fix allows to specify if the `incoming` or `outgoing` payment should be updated.

fix: handle `extra` updates for internal payments

---

lnbits/core/templates/core/wallet.html
lnbits/extensions/cashu/templates/cashu/wallet.html
lnbits/extensions/copilot/templates/copilot/compose.html
lnbits/extensions/events/templates/events/display.html
lnbits/extensions/invoices/templates/invoices/pay.html
lnbits/extensions/jukebox/templates/jukebox/jukebox.html
lnbits/extensions/livestream/templates/livestream/index.html
lnbits/extensions/lnaddress/templates/lnaddress/display.html
lnbits/extensions/lnticket/templates/lnticket/display.html
lnbits/extensions/lnurldevice/templates/lnurldevice/index.html
lnbits/extensions/lnurlp/templates/lnurlp/display.html
lnbits/extensions/lnurlp/templates/lnurlp/index.html
lnbits/extensions/lnurlp/templates/lnurlp/print_qr.html
lnbits/extensions/offlineshop/templates/offlineshop/index.html
lnbits/extensions/offlineshop/templates/offlineshop/print.html
lnbits/extensions/paywall/templates/paywall/display.html
lnbits/extensions/satsdice/templates/satsdice/display.html
lnbits/extensions/satsdice/templates/satsdice/displaywin.html
lnbits/extensions/satsdice/templates/satsdice/index.html
lnbits/extensions/satspay/templates/satspay/display.html
lnbits/extensions/subdomains/templates/subdomains/display.html
lnbits/extensions/tpos/templates/tpos/tpos.html

This PR addresses the issue #1245 and adds 'lightning:' prefix into QRs containing payment requests and lnurls. Above that it makes payment requests upper cased to save some space (about from 65x65 px to 57x57 in my testing).

QR invoices and lnurls got prefix and uppercased

---

lnbits/bolt11.py
lnbits/core/services.py
lnbits/core/views/api.py
lnbits/extensions/bleskomat/helpers.py
lnbits/extensions/boltz/boltz.py
lnbits/extensions/boltz/mempool.py
lnbits/extensions/cashu/crud.py
lnbits/extensions/lndhub/utils.py
lnbits/wallets/lndgrpc.py
tests/core/views/test_api.py

Since LNBits does not support Python 3.5 and older (which are EOL since 2020 anyway), we can use the builtins instead of binascii.

use bytes.fromhex/hex builtins instead of binascii.hexlify/unhexlify

---

lnbits/extensions/boltcards/README.md

Reverts lnbits/lnbits#1241
Change was made based on a wrong assumption. In fact it doesn't matter if the keys are filled via key json or pasted manually.

Revert "Update BoltCard Extension README"

---

lnbits/bolt11.py
lnbits/core/models.py
lnbits/core/views/api.py
lnbits/extensions/boltcards/lnurl.py
lnbits/extensions/boltz/boltz.py
lnbits/extensions/copilot/lnurl.py
lnbits/extensions/livestream/lnurl.py
lnbits/extensions/lnaddress/lnurl.py
lnbits/extensions/lndhub/decorators.py
lnbits/extensions/lndhub/views_api.py
lnbits/extensions/lnurldevice/lnurl.py
lnbits/extensions/lnurlp/lnurl.py
lnbits/extensions/offlineshop/lnurl.py
lnbits/extensions/satsdice/lnurl.py
lnbits/lnurl.py
lnbits/wallets/cln.py
lnbits/wallets/eclair.py
lnbits/wallets/fake.py
lnbits/wallets/lndgrpc.py
tests/core/views/test_api.py

the encoding parameter defaults to `'utf-8'`, so it's not needed
reference:
* https://docs.python.org/3/library/stdtypes.html#str.encode
* https://docs.python.org/3/library/stdtypes.html#bytes.decode

remove unnecessary argument encoding from bytes.decode() and str.encode()

---

lnbits/extensions/lnurlp/lnurl.py
lnbits/extensions/lnurlp/static/js/index.js
lnbits/extensions/lnurlp/views.py

LNURL page link changed from `host/lnurlp/{id}` to `host/lnurlp/link/{id}` (see Screenshot 1) to make room for
LNURL endpoint which changed from `host/lnurlp/api/v1/{id}` to `host/lnurlp/{id}` (see Screenshot 2). Backwards compatibility maintained so old QR codes and LNURLs that point to `lnurlp/api/v1/{id}` still work!

shorten lnurlp endpoint URL for smaller QR codes

---

lnbits/extensions/nostrnip5/crud.py
lnbits/extensions/nostrnip5/templates/nostrnip5/signup.html

The price in sats is being multiplied by 100, should only be done for fiat currencies. 
I input a price of 999 sats and got an invoice for 99900:

Don't Multiply Sat Price by 100 for NIP-5 Verification

---

lnbits/extensions/smtp/crud.py
lnbits/extensions/smtp/migrations.py
lnbits/extensions/smtp/models.py
lnbits/extensions/smtp/smtp.py
lnbits/extensions/smtp/tasks.py
lnbits/extensions/smtp/templates/smtp/index.html
lnbits/extensions/smtp/views_api.py

new pr of https://github.com/lnbits/lnbits/pull/1337

FEAT: v2: Overrides having to pay in SMTP if the owners admin key is present

---

lnbits/wallets/lntips.py

Handles error for non-existing outgoing payment checks.
Fixes: #1373

LNTips fix: payment lookup error handling

---

.env.example

1. Link to details on what and how to include information in a .env file
2. Clarify how to activate the FORWARDED_ALLOW_IPS environment variable for those situations where the proxy is not at the default 127.0.0.1 (most often this is required when running inside a Docker container.)

Additional information in .env

---

lnbits/extensions/tpos/templates/tpos/tpos.html
lnbits/extensions/tpos/views_api.py

Some merchants using TPoS need to capture the billed fiat amount for book keeping. This quick fix captures the fiat amount via invoice memo.

Track fiat amount in TPoS invoices.

---

.github/workflows/formatting.yml
.github/workflows/migrations.yml
.github/workflows/mypy.yml
.github/workflows/regtest.yml
.github/workflows/tests.yml
pyproject.toml

noticed that a lot of checks failing atm...
testing if not creating virtualenv improves stability of the workflows.

FIX: improve workflow stability

---

lnbits/settings.py

Some `settings` fields can be removed over time, but the values in the DB still remain.
If extra fields are present then an exception is thrown:
```
2023-01-23 14:36:46.93 | ERROR | lnbits.app:lnbits_startup:155 | 2 validation errors for SuperSettings
lnbits_ext_github_token
extra fields not permitted (type=value_error.extra)
lnbits_extensions_manifests
extra fields not permitted (type=value_error.extra)
```
This PR ignores extra fields.

fix: ignore extra settings fields

---

.dockerignore
.github/workflows/regtest.yml
Dockerfile
tools/create_fake_admin.py

this pr adds a tool to create a user with predefined ID. so we can use it to test LNbits as fundingsource inside regtest.
-   github workflow
-   tools/create_fake_user.py
-   changes in Dockerfile so we can run the tools/\*.py
-   changes in .dockerignore so tools are available inside docker aswell

TEST: LNbits as fundingsource in regtest

---

.gitignore

Reverts lnbits/lnbits#1429
`extensions` folder must be ignored for the installable extensions pr we merged to work. If people want to update their extension this should no longer be done through the core repo.

Revert "fix gitignore"

---

.env.example
lnbits/core/services.py

Changes `LNBITS_FORCE_HTTPS` in `.env.example` to `False` to reflect the same default as in `settings.py`.
Respects the setting when printing admin UI link.

respect https setting in admin ui link

---

lnbits/core/helpers.py
lnbits/core/views/api.py
lnbits/extensions/lnurlp/__init__.py
lnbits/extensions/lnurlp/models.py
lnbits/extensions/lnurlp/views_api.py

**Summary**
- some extensions are performing background work (like `asyncio.Task` or `WebSockets`)
- when an extension is upgraded or uninstalled the background work has to stop
-  no longer listen for invoices, closes `WebSockets`, etc
**Solution**
- each extension SHOULD expose a clean-up endpoint IF it has background work to be stopped
- by convention the clean-up `HTTP` method is `DELETE` and the endpoint is the root of the extension API
- eg: `DELETE http://localhost:5000/lnurlp/api/v1`
- MUST be restricted to admin users
> **Note** directly calling the clean-up logic from `python` is not possible
**Test**
- add a log statement to `on_invoice_paid` (of `task.py`) for an extension
- create 3 different releases, each with a different log statement (example …

Extension Upgrade - stop background work

---

lnbits/app.py

- extensions can be installed by default when the server starts
- when an extension is auto-installed it is expected to be ready to use
- this PR implicitly activates extensions that are auto-installed

fix: activate default installed extensions

---

lnbits/app.py
lnbits/extension_manager.py
lnbits/middleware.py
lnbits/settings.py

- some extensions need to map routes outside their scope (and under the root path)
- by default extension endpoints are under `/ext_id`
Examples
- **lnurlp** must map `/.well-known/lnurlp/`
- **nostrrelay** should serve relay info under `/` (if a particular header is set)
```curl
GET 'http://localhost:5000/' --header 'Accept: application/nostr+json'
```
- an extension can specify a `{ext_id}_redirect_paths` variable in `__init__.py` (similar to `{ext_id}_static_files`)
- nostrrelay example (here)[https://github.com/lnbits/nostr-relay-extension/blob/main/__init__.py#L23]:
```py
nostrrelay_redirect_paths = [
{
"from_path": "/",
"redirect_to_path": "/api/v1/relay-info",
"header_filters": {
"accept": "application/nostr+json"
}
}
]
```
- this means: WHEN a request is made to `/` AND has the …

Add redirect paths for extensions

---

lnbits/core/views/generic.py
lnbits/helpers.py
lnbits/templates/base.html

Hide the left hand-side Admin menu item if `LNBITS_ADMIN_UI` is set to `false`

fix: hide Admin UI if `LNBITS_ADMIN_UI` is `false`

---

lnbits/core/static/js/extensions.js

- init `filteredExtensions` with `[]`

fix: filter error on `Extensions` page

---

.env.example
docs/guide/installation.md
lnbits/app.py
lnbits/core/services.py
lnbits/core/templates/admin/_tab_server.html
lnbits/settings.py

IDEA: introduce BASEURL variable like other webapplications also have
this PR introduces the settings variable `LNBITS_BASEURL`
this makes generating URLs on the serverside much easier for developers.
you do not need to rely on a request object anymore to create an absolute URL,
for example for all the lnurl stuff, server startup log/superuser urls, etc...
the obvious downside is that users need to introduce a new variable if they are behind a proxy.
but i think it is tradeoff worth taking, because this will reduce the overall complexity of the code
and also simplyfies generating proper url for other developers aswell.
also gets rid of `LNBITS_FORCE_HTTPS` variable, because it is not used anymore.

introduce baseurl and remove force_https

---

lnbits/app.py
lnbits/helpers.py
lnbits/settings.py
lnbits/templates/base.html
pyproject.toml

introduces a fallback to VoidWallet if the funding source is not responding after 30s on startup
- only falls back if adminui is enabled!
- makes the api come up even if the fundingsource is not responding
- should not interfere with wallets that got disconnected after startup

FEAT: add funding source fallback and VoidWallet warning for frontend

---

lnbits/settings.py

forgot the add port to baseurl default

FIX: default baseurl should include port

---

.env.example
lnbits/core/templates/admin/_tab_server.html
lnbits/extension_manager.py
lnbits/settings.py

closes https://github.com/lnbits/lnbits/issues/1547 and corrects behaviour of `is_admin_only` (was previously checking with the folder path and not the extension code)

remove lnbits_disabled_extensions

---

README.md

links introduced in https://github.com/lnbits/lnbits/pull/1546 are broken
one needs to use the `https://` protocol otherwise markdown things we are linking to a local file

fix markdown links in the readme

---

lnbits/extension_manager.py

**Initial Requirements**:
- we have assumed that `LNbits` will be shipped with a small set of basic extensions (lnurlp, lnurlw, ...)
- but the user can update these extensions (eg `lnurlp`)
- so (in case of container re-create) what you have in `/extensions/lnurlp` it is not necessarily the version you have installed (might be the old pre-packaged one)
- if the extension is found in `installed_extensions` and the releases is different from what you have, then it will re-install it
**New Requirements**
- no extension will be pre-packaged
- if there is an `extensions/{ext_id}/config.json` file then assume the extension is already installed

fix: assume no pre-installed extensions

---

flake.lock
flake.nix

After bumping shortuuid in https://github.com/lnbits/lnbits/pull/1576 (allowing us to use the default Python 3.10) and overriding build-systems in poetry2nix in https://github.com/nix-community/poetry2nix/pull/1046 and https://github.com/nix-community/poetry2nix/pull/1049 we can now successfully build lnbits via nix flake. All we need to do is to update the flake.lock file which this PR does.
Caveat: `nix run` still is not able to successfully launch lnbits, because the new approach to extensions want to install files in read-only location. I opened an issue for this: https://github.com/lnbits/lnbits/issues/1579

flake: update to latest nixpkgs

---

pyproject.toml

we can use the toml syntax and don't have to resort to crazy cfg syntax

simplify exclude syntax for mypy in pyproject.toml

---

lnbits/app.py
lnbits/extension_manager.py

While digging around issue https://github.com/lnbits/lnbits/issues/1579 I found out that the extension manager mixes usage of `os.path.join` and `pathlib.Path`
This PR tries to use only the latter.
Draft PR, since this is untested yet.

refactor extension_manager to use `pathlib.Path` instead of `os.path.join`

---

lnbits/core/services.py

bugfix
related to: https://github.com/lnbits/lnbits/issues/1425
message if a different wallet tries to pay an already paid invoice.
message if same wallet tries to pay same invoice:
before:

bugfix: 500 error if same wallet tries to pay an external invoice twice

---

package-lock.json
package.json

FEAT: lock name inside package-lock, by adding name to package.json

FEAT: lock name inside package-lock, by adding name to package.json

---

lnbits/wallets/lndrest.py

improve on lndrest errorhandling
https://github.com/lnbits/lnbits/issues/252

improve errorhandling for lndrest #252

---

lnbits/core/static/js/wallet.js

Enable BIP21 URI's / QR codes to be used/scanned with the LNbits wallet
Fixes #1202

Allow for scanning BIP21 QR codes

---

lnbits/core/crud.py
lnbits/core/models.py
lnbits/core/templates/admin/_tab_server.html
lnbits/middleware.py

- the admin has the option of making some extensions `Admin Only`:
- ![image](https://user-images.githubusercontent.com/2951406/230139646-d3ba2642-1d19-4998-9c99-774dc04668f7.png)
- when a non-admin tries to access one of these extensions, it will receive an error message:
- ![image](https://user-images.githubusercontent.com/2951406/230139847-9fe69754-0966-456a-b3d4-e8e4fadf7bc5.png)
- access is also denied on the API level (but in JSON format):
- ![image](https://user-images.githubusercontent.com/2951406/230140266-fb97d173-5e90-4ade-8537-76cea6aac4b3.png)
- the admin extension should not be visible on the `Extensions` page or on the left hand-side extension list
- this rule does not apply for public pages (where no `usr` is present)
- for example, `nostrrelay` can be an admin extension, …

Fix admin ext access

---

poetry.lock
pyproject.toml

remove python38 from pyproject.toml

---

Makefile
lnbits/core/static/js/service-worker.js

should should fix current problems with PWA.
https://stackoverflow.com/questions/30523843/service-worker-how-to-update-the-cache-when-files-changed-on-the-server
CACHE_VERSION needs in increment when files changed so it will recache everything.
* added a automatic increment script to run on `make bundle`

increment cache version for service-worker.js

---

lnbits/core/crud.py
lnbits/core/helpers.py
lnbits/core/services.py
lnbits/core/views/api.py
lnbits/core/views/generic.py

This PR allows for an external environment to define a value for `SUPER_USER` even if that user_id is not yet present in the system.
The value for `SUPER_USER`  must be a hex string with a minimum length of 32 chars (128 bits).
LNbits will normalize the `SUPER_USER` value such that:
- its length is 32 chars (128 bits).  Any characters after the 32nd position will be ignored
- for example the valid hex `d858dc48ab1ef6bc1e5ce27c44b508eea9c73214776b5b38d92b4292d8c961c2` will be normalized to `d858dc48ab1e46bc9e5ce27c44b508ee`
- it must be a valid UUID4
- for example the valid hex `ffffffffffffffffffffffffffffffff` will be normalized to `ffffffffffff4fffbfffffffffffffff`
The normalization is required so that a external environments do not have to comply with LNbits, but the other way around. …

Create super user account if it does not exist

---

docs/guide/installation.md

poetry errors on OSX, added troubleshooting note on how to bypass the error on installation.
```
The Poetry configuration is invalid:
- Additional properties are not allowed ('group' was unexpected)
- 
at ~/.poetry/lib/poetry/_vendor/py3.9/poetry/core/factory.py:43 in create_poetry
39│             message = ""
40│             for error in check_result["errors"]:
41│                 message += "  - {}\n".format(error)
42│
→  43│             raise RuntimeError("The Poetry configuration is invalid:\n" + message)
44│
45│         # Load package
46│         name = local_config["name"]
47│         version = local_config["version"]
```

Add troubleshooting note for Poetry errors on OSX install

---

.pre-commit-config.yaml

mypy in pre-commit is flakey and does not and will never support configs from pyproject.yaml.
also its pretty slow so i think its best to remove it from pre-commit

remove mypy from precommit

---

lnbits/core/crud.py

`get_latest_payments_by_extension` isn't working on SQlite. The query `WHERE pending = 'false'` doesn't work for SQLIte, changed it to `0`!
Issue was that TPOS wouldn't get the latest payments to display!

fix "boolean" query for sqlite

---

lnbits/app.py
lnbits/core/templates/core/extensions.html

- when an extension is installed via `LNBITS_EXTENSIONS_DEFAULT_INSTALL` the `shortDescription` value is not shown
- see `gerty`, `juckebox` or `events` in the screenshot below:
- the fix will now show the `shortDescription` no matter how the extension was installed
- re-install of extension not required

fix: ext short description for pre-installed extensions

---

.github/workflows/regtest.yml
Dockerfile
lnbits/wallets/eclair.py
tests/conftest.py
tests/helpers.py

as @jackstar12 discover the regtest were not using the actual fundingsources.
- switched invoice create to lnd-1 node because it is connected the best inside regtest
- make invoice amount smaller
- switch LndWallet, LndRestWallet to use lnd-3 (selfpayments)
had to change the docker regtest setup aswell, because eclair was actually not working. using a wrong zmq endpoint
also @jackstar12 fixed eclair backend, it was also not beeing able to pay a real invoice.

TEST: fix tests for real wallets

---

lnbits/templates/base.html

the footer nav is show until md, but the space only for mobile, should be on both.

quickfix spacing und mobile footer

---

lnbits/core/templates/core/extensions.html
lnbits/extension_manager.py

Extension repository is required in order to show more info about the extension to the user.
This PR only shows the repo url as a tooltip.
Add more manifests to the `Extension Sources` list:
- https://raw.githubusercontent.com/lnbits/lnbits-extensions/main/extensions.json
- https://raw.githubusercontent.com/motorina0/lnbits-extensions/main/extensions.json
- https://raw.githubusercontent.com/lnbits/nostrclient/main/manifest.json
Each source should show the correct repo as tooltip:

feat: show extension repo as tooltip for each repo

---

.env.example
lnbits/core/templates/admin/_tab_server.html
lnbits/core/views/api.py
lnbits/core/views/generic.py
lnbits/settings.py

Allow server admin to limit the number of available fiat currencies

Ability to limit available fiat currencies

---

.gitignore

The communists want everyone to live the exact same life through the use of nazi software.

Add pre-commit-config to gitignore

---

lnbits/app.py
lnbits/core/models.py
lnbits/core/services.py
lnbits/core/views/generic.py
lnbits/settings.py
lnbits/tasks.py
lnbits/wallets/__init__.py
lnbits/wallets/base.py
tests/core/views/test_api.py
tests/helpers.py

These are some changes from https://github.com/lnbits/lnbits/pull/1702 which probably deserve its own pr.
I moved the `get_wallet_class` and `set_wallet_class` functions into the wallets module for two reasons:
- probably fits better logically
- fixed some issue with circular imports in https://github.com/lnbits/lnbits/pull/1702
I left a `get_wallet_class` wrapper for now in settings because lndhub and bleskomat reliy on it being there, maybe update that in the future.
https://github.com/search?q=org%3Alnbits%20NOT%20repo%3Alnbits%2Flnbits%20NOT%20repo%3Alnbits%2Flnbits-legend-1%20get_wallet_class&type=code
`set_wallet_class` isnt used in any vetted extension:
https://github.com/search?q=org%3Alnbits+NOT+repo%3Alnbits%2Flnbits+NOT+repo%3Alnbits%2Flnbits-legend-1+set_wallet_class&type=code …

Refactor get walletclass

---

.gitignore
lnbits/server.py

like we did for the data dir. 
tested works great. 
so no more unstaged git files when you are symlinking into your own extensions dir.

remove extensions dir completly, create it on startup

---

.env.example
lnbits/settings.py

default is 600 = 10 minutes, which is a pretty short amount of time, for example when using lnbits fundingsource inside lnbits itself it would fail if you do a submarine swap or anything involved with hold invoices
i think 3600 = 1 hour should not make a difference in performance and is a way more reasonable default expiry

Increase default invoice expiry to 1 hour

---

lnbits/core/templates/admin/_tab_funding.html
lnbits/core/templates/admin/index.html

Fix the save badge (red dot) being always on. Made the invoice expiry input as number, as the settings, so that the settings and the formData are equal, and don't trigger the badge!
Make a deep copy (not sure it's necessary, but `_.clone()` makes a shallow copy, and it can be done with vanilla js *maybe we could discard underscore **one less lib dependency)
Add a restart note when/if the settings changed require a server restart!
Closes #1801

Fix admin notifications

---

lnbits/wallets/eclair.py
lnbits/wallets/lnbits.py
lnbits/wallets/lndrest.py
lnbits/wallets/lnpay.py
lnbits/wallets/lntips.py
lnbits/wallets/opennode.py
lnbits/wallets/spark.py

Leads to ugly stack traces when the cleanup routine is called while `paid_invoice_stream` is still streaming.
Example:

Wallets: Catch errors during cleanup

---

lnbits/core/templates/core/index.html

Layout fix for #1834:
<div style="display:flex;">
<br><img src="https://github.com/lnbits/lnbits/assets/3606313/ab6a603f-9e6b-41c9-8f8a-088e66195431" width="45%" />
➡️<img src="https://github.com/lnbits/lnbits/assets/3606313/8ca87695-1930-4d09-819f-dea3624234cb" width="45%" />
</div>

Ads layout fix

---

lnbits/core/services.py
lnbits/core/tasks.py
tests/conftest.py
tests/core/views/test_api.py

fixes: https://github.com/lnbits/lnbits/issues/1820
I introduced a `send_payment_notification` service because this logic is now needed in three seperate places in order to avoid inconsistent messages. Now all messages inclue the whole payment information ( `payment.dict`) which could be considered a breaking change (outgoing had the structure of `PaymentResponse`.

websocket internal payment notifications

---

lnbits/db.py
tests/core/test_db.py

This small pr demonstrates the faulty `register_type` call I mentioned in some other prs with a small test case.
This bug is specific to postgres because the faulty converter only applied there. The functions around times / dates are pretty inconsistent across dbs so when someone wants to use them they need to be aware of such differences.
Here you can see it failing:
https://github.com/lnbits/lnbits/actions/runs/5696767068/job/15442435962?pr=1842

Bug: invalid type converter

---

lnbits/core/views/api.py
lnbits/wallets/lnbits.py
tests/core/views/test_api.py

Testing handling of pending payments by using hodl invoices generated in the regtest CI (by LND).
Fixes 2 bugs
- api_payents_create responds with error if payment fails
- bug in the LNbits backend that did not respond correctly for pending outgoing payments.

Tests: hold invoice tests pending during payment

---

lnbits/app.py
lnbits/cache.py
tests/core/test_cache.py

This pr introduces a simple redis-like cache utility.
- temporary caching of exchange rates, especially usefull with something like https://github.com/lnbits/lnbits/pull/1789
- caching node peer information or payment history in cln at https://github.com/lnbits/lnbits/pull/1702
- improving api key validation which currently queries the entire wallet, including balance, see: https://github.com/lnbits/lnbits/blob/bc55d52ea25475a524059fccbc5a35039f8be533/lnbits/decorators.py#L52-L55

add cache utility

---

lnbits/core/static/js/wallet.js
lnbits/core/templates/core/wallet.html

Followup to https://github.com/lnbits/lnbits/pull/1845
This PR hides the paste button in unsupported environments:
- the clipboard API only works in [secure context](https://stackoverflow.com/a/51823007)
- [Firefox supports the clipboard API only in extensions](https://support.mozilla.org/en-US/questions/1331833); `navigator.clipboard.readText` is undefined in Firefox

UI: hide paste payment request in unsupported environments

---

tests/conftest.py
tests/helpers.py

this is required for bolt11 library merge PR https://github.com/lnbits/lnbits/pull/1817
the issue was, creditwallet used an empty ```payment_hash```

[TEST] proper credit_wallet function from services for test helpers

---

lnbits/core/static/js/wallet.js

Continuation of https://github.com/lnbits/lnbits/pull/1756
Instead of creating a new endpoint for csv just fetch all payments and create the csv in the browser.
It also exports the fiat value and currency from https://github.com/lnbits/lnbits/pull/1789

Fix csv export

---

lnbits/core/models.py
lnbits/core/services.py
lnbits/wallets/base.py
lnbits/wallets/cliche.py
lnbits/wallets/corelightning.py
lnbits/wallets/corelightningrest.py
lnbits/wallets/eclair.py
lnbits/wallets/fake.py
lnbits/wallets/lnbits.py
lnbits/wallets/lndgrpc.py
lnbits/wallets/lndrest.py
lnbits/wallets/lnpay.py
lnbits/wallets/lntips.py
lnbits/wallets/opennode.py
lnbits/wallets/spark.py
lnbits/wallets/void.py
tests/core/views/test_api.py
tests/mocks.py

Changing up the entire wallet interface is not necessary. We can just get the `bolt11` via the database for now.

clnrest: revert unnecessary changes

---

lnbits/wallets/cln.py
pyproject.toml

some time ago we added pyln do main dependencies, its need for think like, saas or docker. so this import was dead code

[CHORE] cln.py pyln-client is not optional

---

tests/conftest.py

this is important for local testing. else you will install those extensions if you have them inside env.

[BUG] dont install default extensions for tests

---

.github/workflows/tests.yml

i think it is a good idea to test both at least for fakewallet tests.

[TEST] run tests.yml on py39 and py310

---

lnbits/app.py

for immediate vision of installed extensions. i tried it to have a onliner to save some space. but it was very hard to read if there are many extensions installed.
for comparison:

FEAT: add installed extensions to log

---

lnbits/app.py

this catches exception on set_wallet_class and switches to VoidWallet if it fails.

feat: catch wallet init exception, string formatting for app.py

---

lnbits/app.py
lnbits/core/tasks.py
lnbits/tasks.py

Not all long-running tasks are cancelled upon shutdown, which caused some issues with `WALLET.cleanup`.
I introduced a few new functions:
- `create_task` basically a wrapper around the asyncio equivalent, adds the task to a list
- `cancel_all_tasks` cancels all tasks previously created with `create_task` (if any are already stopped, `cancel` will do nothing)
- `create_permanent_task` wrapper around `create_task` with `catch_everything_and_restart`
Now all tasks are cancelled on shutdown and `WALLET.cleanup` goes without errors.

cancel all long-running tasks

---

lnbits/app.py
lnbits/core/models.py
lnbits/core/views/api.py
lnbits/middleware.py

The sse endpoint doesnt work if there is no properly configured reverse proxy that takes care of disabling gzip. A small wrapper around `GzipMiddleware` can fix that tough.
The code for the endpoint itself seems a bit overcomplicated to me aswell (why an additional queue?), refactored that aswell.

[REFACTOR] payments sse endpoint

---

lnbits/core/static/js/wallet.js
lnbits/core/templates/core/wallet.html

Closes: https://github.com/lnbits/lnbits/issues/1731
Payments are now refetched upon invoice creation. 
I was also wondering why the payment status is being polled regulary while sse does the same anyways. If there's a reason for that, let me know.

Update payments on invoice creation

---

lnbits/core/crud.py
lnbits/core/models.py
lnbits/core/views/api.py
lnbits/decorators.py

- move wallettype models from decorators.py into models.py
- use enum instead of int for wallet_types
- use HTTPStatus for consistency

[REFACTOR] WalletType into enum

---

lnbits/core/views/api.py

save user input into extra when he chooses a currency for api_create invoice

[FEAT] save fiat amount in api_create_invoice

---

lnbits/core/crud.py

this was missed here https://github.com/lnbits/lnbits/pull/1888
curious why mypy only started to error after i rebases here. https://github.com/lnbits/lnbits/actions/runs/5952068411/job/16143185781?pr=1887

[BUG] use WalletType for get_wallet_for_key fn

---

lnbits/core/migrations.py

I recently noticed that the `balances` view is a bit more complicated that it has to be. Instead of doing two full row scans over the payments table (once for incoming, once for outgoing) it can be reduced to just one, making it faster and easier to understand.
`EXPLAIN ANALYZE` for old view
```
Finalize GroupAggregate  (cost=6828.51..6876.21 rows=200 width=63) (actual time=61.485..63.383 rows=526 loops=1)
Group Key: apipayments.wallet
->  Gather Merge  (cost=6828.51..6871.16 rows=340 width=63) (actual time=61.460..62.855 rows=749 loops=1)
Workers Planned: 2
Workers Launched: 2
->  Partial GroupAggregate  (cost=5828.49..5831.89 rows=170 width=63) (actual time=25.640..25.836 rows=250 loops=3)
Group Key: apipayments.wallet
->  Sort  (cost=5828.49..5828.91 rows=170 width=63) (actual …
```

optimize balances view

---

lnbits/core/views/api.py

return a exception per error it is description hash or unhashed_description

[REFACTOR] proper create_invoice responses for descriptions

---

lnbits/utils/exchange_rates.py
tests/core/views/test_api.py

simplifies the code and adds caching.
the the `return_exceptions` on  the `gather` is key as it tells gather not to return if one of the tasks fail but instead wait for all to complete.
Exir was removed as a provider because it doesnt work (maybe binance alternative?)

refactor exchange rates

---

lnbits/wallets/fake.py

When using `description_hash` the tag `h` needs to be set.

[FIX] fakewallet: set tag of description_hash invoice correctly

---

.gitignore
lnbits/commands.py
lnbits/core/services.py

related to https://github.com/lnbits/lnbits/pull/1855 put the `.super_user` into our data_dir to not pollute our root dir removed the weird mention to the url in the logs and mention the `lnbits-cli superuser` instead
this is a breaking change for the bundlers, `cat .super_user` is not good anymore. fix would be `cat data/.super_user` but for future compatibility i recommend using `poetry run lnbits-cli superuser`

[REFACTOR] `.super_user` move it into data dir

---

lnbits/core/crud.py
lnbits/core/services.py
lnbits/core/views/admin_api.py
lnbits/settings.py
tests/conftest.py
tests/core/views/test_admin_api.py

while working on the push notification pr i found it very hard just to update 2 settings inside the db, so i improved upon update_admin_settings. now you just need to provide a dict with key/values you want to update inside db.
also debugging the endpoints for update_settings i found despite the type of `EditableSettings` fastapi did in fact pass a dict.
import

[FEAT] improve update_admin_settings

---

tests/conftest.py
tests/helpers.py

Using the admin ui in tests has the side effect of loading settings from the database, which might contain some settings from manual testing.
To mitigates this, we can create a fresh postgres database for testing. This has also has the advantage that migrations run everytime and no leftovers are produced.

[TEST] use clean db in postgres tests

---

lnbits/app.py
lnbits/core/__init__.py
lnbits/core/crud.py
lnbits/core/db.py
lnbits/core/helpers.py
lnbits/core/services.py
lnbits/core/tasks.py
lnbits/core/views/admin_api.py
lnbits/core/views/api.py
lnbits/core/views/generic.py
lnbits/core/views/public_api.py
lnbits/middleware.py
lnbits/tasks.py
lnbits/wallets/corelightningrest.py
pyproject.toml
tests/conftest.py

This fixes `E402: module level import not at top of file` and required a bit of a refactor for core imports.
now every core.view creates its own `APIRouter` which is imported into `core/__init__.py` where its initialised inside app via `init_core_routers(app)`
tested backwards compatibility for extensions and they at least not crash with import errors.

[REFACTOR] core/__init__ to not have circular import issues

---

lnbits/core/crud.py
lnbits/core/models.py

Adds the deleted flag to the CRUD for `get_user`, so it doesn't send deleted wallets to the UI.
Closes #1939

do not show deleted wallets

---

docs/devs/extensions.md

Updated the dev guide for extension development to work with the current extension management process

Updated dev user guide for extension development

---

lnbits/core/crud.py
lnbits/core/models.py
lnbits/core/static/js/index.js
lnbits/core/static/js/wallet.js
lnbits/core/templates/core/wallet.html
lnbits/core/views/api.py
lnbits/core/views/generic.py
lnbits/static/js/base.js
lnbits/static/js/components.js
tests/core/views/test_api.py
tests/core/views/test_generic.py

this removes the functionalitiy to create accounts and wallets via the GET /wallet endpoint in generic.py
it add endpoints inside the api.py for it and the frontend is modified to use the api endpoints
this also simplifies for the `feat/login` for the route.

[FEAT] cleanup GET /wallet endpoint, add wallet api routes

---

lnbits/core/views/api.py

catches
```
2023-09-26T17:35:19-06:00  Task exception was never retrieved
2023-09-26T17:35:19-06:00  future: <Task finished name='Task-5361' coro=<EventSourceResponse._ping() done, defined at /root/.cache/pypoetry/virtualenvs/lnbits-9TtSrW0h-py3.10/lib/python3.10/site-packages/sse_starlette/sse.py:249> exception=ClosedResourceError()>
2023-09-26T17:35:19-06:00  Traceback (most recent call last):
2023-09-26T17:35:19-06:00    File "/root/.cache/pypoetry/virtualenvs/lnbits-9TtSrW0h-py3.10/lib/python3.10/site-packages/sse_starlette/sse.py", line 259, in _ping
2023-09-26T17:35:19-06:00      await send({"type": "http.response.body", "body": ping, "more_body": True})
2023-09-26T17:35:19-06:00    File "/root/.cache/pypoetry/virtualenvs/lnbits-9TtSrW0h-py3.10/lib/python3.10/site-packages/starlette/ …
```

fix: catch sse exceptions

---

lnbits/app.py
lnbits/helpers.py
lnbits/settings.py
lnbits/static/i18n/br.js
lnbits/static/i18n/cn.js
lnbits/static/i18n/de.js
lnbits/static/i18n/en.js
lnbits/static/i18n/es.js
lnbits/static/i18n/fr.js
lnbits/static/i18n/it.js
lnbits/static/i18n/jp.js
lnbits/static/i18n/nl.js
lnbits/static/i18n/pi.js
lnbits/static/i18n/pl.js
lnbits/static/i18n/pt.js
lnbits/static/i18n/we.js
lnbits/templates/base.html

- remove the `settings.lnbits_commit` property from logs and UI
Reason:
- it makes it harder to have reproducible build
- lnbits  now uses `dev` branch for unstable releases and `main` for stable, tagged releases. Therefore the commit version is redundant

feat: remove commit version

---

flake.lock
flake.nix
lnbits/settings.py
nix/modules/lnbits-service.nix
nix/tests/nixos-module/default.nix

There wasn't too much bitrot over time, this is a minimal PR to update potree2nix, get lnbits building again and passing the existing vmTest which is buildable via `nix build .#checks.x86_64-linux.vmTest -L` or `nix flake check` for example.
I've tested this as working on x86_64-linux and aarch64-linux.
It would be really nice if we could explain how to use the nixosModule in the Documentation rather than telling people to just `nix build` and run the program. The correct way to use the Nix work is via `services.lnbits.enable = true`, but this can be done in a later PR, and I'll endeavor to write that document.

nix: fix nixosModule and build

---

lnbits/core/views/generic.py

manifest still uses icon from 0.3.0
let's use the current one (from the main branch)

use current version of logo for manifest icon

---

lnbits/middleware.py

removes a workaround and TODO left in the code.

[CHORE] cleanup ip block middleware workaround for older fastapi

---

lnbits/nodes/base.py

So I've updated to 0.11.0, rushed the new node stats and it just doesn't seem right to me. Closed channels are being included. Here I'm offering my humble hot fix. 
Maybe also inactive channels should be included in some/all of those stats? Let me know what you think.

fix: Closed channels affecting the stats

---

.env.example
docs/guide/admin_ui.md
lnbits/core/templates/core/index.html
lnbits/core/views/api.py
lnbits/helpers.py
lnbits/settings.py

with `LNBITS_CREATE_ACCOUNT=false` while keeping existing users functional (i.e. no allowlist for existing users)

add possibility to turn off new registrations 

---

lnbits/helpers.py
tests/core/test_helpers_query.py

i saw this bits of code all over the codebase, this `helpers.py` tries to abstract that away and make it more readable.
in boltz alone i used this pattern 3 times.
here is the pr utilizing the insert_query.
https://github.com/lnbits/boltz/pull/13
todo:

feat: add useful query helpers for insert and update

---

poetry.lock
pyproject.toml

- see pyproject.toml for the dependency addition, and comment by @motorina0 here: https://github.com/bitkarrot/scheduler/issues/8#issuecomment-1754662019

 add python-crontab for scheduler extension

---

.github/workflows/nix.yml

builds on top of https://github.com/lnbits/lnbits/pull/2027 which is needed for the successful nix build
The `nix build` action in the CI [takes around **~36** minutes](https://github.com/lnbits/lnbits/actions/runs/6473111117/job/17575129639?pr=2026), so it is run only if run only when poetry/flake files are changed

add "nix build" to GitHub CI

---

lnbits/commands.py
lnbits/core/helpers.py

Each extension has a DB version stored in the `dbversions` table. When an extension is upgraded this version can change if there are new scripts in `migration.py` file.
The bug is on extension upgrade. The temp upgraded module name was used for the `dbversions` table:
The fix uses the explicit DB name.
**Test Steps**:
- install an extension with a lower version (eg: satspay v0.2.3)
- upgrade to a higher version (eg: satspay v0.2.5)
- two entries for `satspay` are now in the `dbversions` (see screenshot)
**Expected Result**:
- the `satspay` entry gets updated to version `7`
- no new `satspay` entry in `dbversions`
**Note**:
- I suspect this bug was introduced with this PR https://github.com/lnbits/lnbits/pull/1940

fix: explicitly specify the DB name when migrating

---

docs/guide/installation.md

Fix install instructions after #2052 and #2060
Also these have been merged to `main`, not to `dev`, so this is also targeted to `main`. We will then merge `main` into `dev`.

[main/fix] fix docs/guide/installation

---

.env.example

The recent Node Management feature is only available if you set `LNBITS_ADMIN_UI=true`. 
For LNBITS users who keep running their instance managing their `.env` file, the following PR would allow them to use the feature and adjust settings without the UI.
This can be looked up at the boolean settings blurp [over here](https://github.com/lnbits/lnbits/blob/fed2d411399a0f3f46c1fffe5f6f67942e56b2e7/lnbits/settings.py#L236), and has been tested on a production node.
What is missing is the "Node" menu entry on the left navigation bar. The overview can be retrieved by browsing to https://yourdomain.com/**node**?user=1233434555564, but adding this navigation bar  as soon one of 
```
LNBITS_NODE_UI=false 
LNBITS_PUBLIC_NODE_UI=false
LNBITS_NODE_UI_TRANSACTIONS=false
```
is `true` would make the …

Enable Node Management via .env without activating admin-UI

---

lnbits/wallets/__init__.py

There is an extra empty line because black wants it that way and ruff does not complain.

add comment why CLightningWallet alias is needed

---

.env.example

The `.env.example` was missing the example for `SUPER_USER`

doc: add `SUPER_USER` field

---

lnbits/static/i18n/en.js
lnbits/static/i18n/we.js
lnbits/wallets/fake.py

FakeWallet used to create invalid payment secrets. Now it does it in a bolt11 compliant way. 
FakeWallet now also keeps the payment secrets and returns them upon a successful payment. This should fix the bug reported by Alby users who complained that they were only receiving "00000...".
FakeWallet can now also report the status of a paid invoice by keeping a set of them.

FakeWallet: provide payment preimage

---

lnbits/wallets/corelightningrest.py

Updates to the new CLN-REST interface which now can use `payment_hash` for looking up payments and invoices. 
Feature requests in https://github.com/Ride-The-Lightning/c-lightning-REST/issues/184 are included in the latest release.

Upadte to c-lightning-REST v0.10.5

---

lnbits/core/views/api.py

Allow `extra` to get passed when making a payment.
```
{
"unit": "sat",
"out": true,
"extra": {
"orderId":"3l4k23j4k2l3j34",
"tag":"FEES"
},
"bolt11": "lnbc10u...0p8da5"
}
``` 
on the payments will show:
```
{
"paid": true,
"preimage": "0...000",
"details": {
"checking_id": "ede3426...93bb8d6",
"pending": false,
"amount": -1000000,
...
"expiry": 1699445241,
"extra": {
"orderId": "3l4k23j4k2l3j34",
"tag": "FEES"
},
...
}
}
```
Closes #2082

pass custom extra on payment out

---

lnbits/middleware.py

There is a middleware called `InstalledExtensionMiddleware` and this middleware is great! But it had a bug.
A middleware (in general) intercepts all HTTP calls and does some pre/post processing on the request.
The main job of this middleware is to:
- check if an extension is upgraded
- if so, then redirect the calls to the latest upgraded version by re-writing the HTTP path
Static resources do not require redirect so in the old version only the paths for the `/api` calls were redirected.
However, the public pages (like http://127.0.0.1:5000/tpos/9BKt3SCEtLMmwXSh6sxjsp) are not `/api` and are not static resources, therefore they were not redirected (this is the bug).
The changes in this PR simplify the middleware by:
- explicitly check if the path is a static resource (and skip redirect)
- …

fix: redirect for all paths of the extension (not only for `/api`)

---

flake.nix
poetry.lock
pyproject.toml

this is needed for liquid support in the new boltz extension, sadly i could not get it to work with embit library, liquid support is not quite ready there and no documentation or tests available

feat: add libwally for liquid support

---

lnbits/core/services.py
lnbits/core/tasks.py
lnbits/core/views/api.py
lnbits/core/views/node_api.py
lnbits/extension_manager.py
lnbits/settings.py
lnbits/utils/exchange_rates.py
lnbits/wallets/alby.py
lnbits/wallets/corelightningrest.py
lnbits/wallets/eclair.py
lnbits/wallets/lnbits.py
lnbits/wallets/lndrest.py
lnbits/wallets/lnpay.py
lnbits/wallets/lntips.py
lnbits/wallets/opennode.py
lnbits/wallets/spark.py

Inspired by a feature request mentioned in https://github.com/lnbits/lnbits/pull/2086/#discussion_r1391300477
Updated all calls to external resources to include user agent set to `f"LNbits/{settings.version}"`

set User-Agent when accessing external resources

---

lnbits/core/templates/core/extensions.html
lnbits/core/templates/core/wallet.html
lnbits/templates/base.html

When using `delimiters` to avoid the `{% raw %}` stuff, the toolbar, which is rendered on the base html doesn't display languages correctly.
- refactored the language list to show correctly

fix issue with displaying languages

---

Makefile

since we are already using awk, we might as well use it exclusively and drop sed

use awk to bump CACHE_VERSION (drop sed usage)

---

lnbits/core/models.py
tests/core/views/test_api.py

this pr adds a 15 minutes margin before deleting failed outgoing payments.

fix: time margin for deleting failed payments

---

lnbits/core/templates/core/index.html

hotfix to restore `AD_SPACE_TITLE`

restore ad space title

---

lnbits/core/__init__.py
lnbits/core/views/api.py
lnbits/core/views/webpush_api.py

refactor to make `views/api.py` cleaner

refactor: move webpush to its own router

---

nix/modules/lnbits-service.nix

This adds an additional option to the nixos module so you can pass additional environment variables to lnbits. 
These variables are merged with the variables set in the systemd service.

Add nixos module option to pass additional environment variables

---

lnbits/core/views/api.py

`r.raise_for_status` raises an proper exception now

fix: lnurl should follow redirect

---

pyproject.toml

It seems there are many small improvements we want to release as part of 0.11.3 that is before merging big features to 0.12.0.
Let's merge PRs from [Milestone 0.11.3](https://github.com/lnbits/lnbits/milestone/10) and do the release now-ish.
We can do 0.12.0 later in January.

chore: update to version 0.11.3

---

.github/workflows/nix.yml

- this should reduce the build time needed in the CI
- this should reduce the build time needed when deploying LNbits - users just need to call `cachix use lnbits` before calling `nix build`

update nix ci action to use cachix to cache results

---

lnbits/nodes/cln.py

Bolt11 allows for invoices to have no amount, allowing the sender to select the amount to send. At least core lightning and LND support this.
When looking through my invoices on the node page, I get an error when it tries to fetch an unpaid invoice with no amount:
```
Nov 30 19:59:56 wilfrid poetry[2788777]:   File "/mnt/bitcoin/git/lnbits-legend/lnbits/nodes/cln.py", line 46, in wrapper
Nov 30 19:59:56 wilfrid poetry[2788777]:     return await f(*args, **kwargs)
Nov 30 19:59:56 wilfrid poetry[2788777]:   File "/mnt/bitcoin/git/lnbits-legend/lnbits/nodes/cln.py", line 311, in get_invoices
Nov 30 19:59:56 wilfrid poetry[2788777]:     data=[
Nov 30 19:59:56 wilfrid poetry[2788777]:   File "/mnt/bitcoin/git/lnbits-legend/lnbits/nodes/cln.py", line 312, in <listcomp>
Nov 30 19:59:56 wilfrid …
```

cln: allow amountless invoices in node tx list

---

lnbits/core/views/generic.py

Store last active wallet as a cookie. When the user re-opens the tab it will have the last active wallet selected.
Before this PR the first wallet was the selected one.
https://github.com/lnbits/lnbits/assets/2951406/91bb032f-e71d-4dae-beb4-ef53f71b598c

feat: remember last active wallet

---

lnbits/core/crud.py
lnbits/core/migrations.py
lnbits/core/models.py
lnbits/db.py

feat: add `created_at` and `updated_at` to wallets and accounts

---

flake.nix

The definition of the dev shell in the flake file had issues when opening a development shell. However, defining the custom dev shell is unnecessary anyway as mkPoetryApplication already creates a default working dev shell.

fix: remove custom dev shells from the flake file

---

lnbits/core/views/auth_api.py
lnbits/utils/crypto.py
lnbits/wallets/lndgrpc.py
lnbits/wallets/lndrest.py
lnbits/wallets/macaroon/__init__.py
lnbits/wallets/macaroon/macaroon.py

`AESCipher` class is used for encrypting/decrypting messages.
Initially it was required for macaroons, but now the auth logic also uses it. Therefore it has been moved to its own `utils.crypto.py` file and the imports updated.

refactor: extract `AESCipher` to `crypto.py`

---

lnbits/core/views/auth_api.py
lnbits/helpers.py

Small refactoring that allows extensions also to encrypt messages using the default auth secret.
One use-case is exposing secret endpoints that can only be used between extensions.
```py
@nostrclient_ext.websocket("/api/v1/{id}")
```
If the decrypted value of `id` is `"relay"` then the connection is allowed (made by another extension). Otherwise the connection is dropped.

refactor: extract `encrypt_internal_message` and `decrypt_internal_message`

---

.env.example
lnbits/app.py
lnbits/commands.py
lnbits/core/helpers.py
lnbits/core/views/generic.py
lnbits/extension_manager.py
lnbits/helpers.py
lnbits/settings.py

Add the `LNBITS_EXTENSIONS_DEACTIVATE_ALL` flag. If set to true then on server startup the extensions will not be loaded. This will exclude running the migration and  the route mapping.
**Scenario 1**
- start the server with the flag set to `false` (default)
- test install/uninstall/upgrade
- new: if an extension is deactivated at the start-up moment then it will not be loaded
**Scenario 1**
- start the server with the flag set to `true`
- expect: 
- no extension should be loaded
- the extensions are not visible on the left hand side
- the extensions are visible on the extensions page (http://localhost:5000/extensions)
- the extensions can be installed/uninstalled/de-activated

Deactivate all extensions flag

---

lnbits/wallets/alby.py
lnbits/wallets/base.py
lnbits/wallets/cliche.py
lnbits/wallets/corelightning.py
lnbits/wallets/corelightningrest.py
lnbits/wallets/eclair.py
lnbits/wallets/lnbits.py
lnbits/wallets/lndgrpc.py
lnbits/wallets/lndrest.py
lnbits/wallets/lnpay.py
lnbits/wallets/lntips.py
lnbits/wallets/opennode.py
lnbits/wallets/spark.py

- better error messages when a conf variable is not provided
- unify approaches among different source files

refactor __init__ functions of Wallets (funding sources)

---

.env.example
lnbits/commands.py
lnbits/core/crud.py
lnbits/settings.py

`lnbits-cli db cleanup-wallets` removes all wallets that never had an transaction. this helps against spammers creating random wallets, eventually slowing down the db.

feat: `cleanup-wallets` cli command

---

lnbits/core/templates/core/extensions.html
lnbits/core/views/generic.py

This PR solves two small issues:
**Withdraw extension link**
Opening the `LNURLp` extension from the extension page will result in an error page. Works fine from the left-side menu.
The reason is that there is a path conflict with an endpoint defined in `lnbits/core/views/generic.py`. Adding an `/` suffix solves the issue.
**Enable/Disable extension**
When enabling/disabling an extension the state of the extension is not updated (`enabled/disabled`). A refresh or performing the action again is required.

Fix extension navigation

---

lnbits/wallets/alby.py
lnbits/wallets/opennode.py

* fixes https://github.com/lnbits/lnbits/issues/2211
* supersedes https://github.com/lnbits/lnbits/pull/2220
cc @bitkarrot for testing

alby: fix balance reporting and error handling + opennode: fix error handling

---

lnbits/static/js/account.js

Check for `username` before allowing password change
**Steps**:
- create a new account
- go to Account page an try to change the password
- an error message is displayed: `[{'loc': ('body', 'username'), 'msg': 'field required', 'type': 'value_error.missing'}]` 
**Expected Result**:
- a nice message is displayed asking the user to set an `username` first
- username/password login is not possible without a username
**Workaround**:
- set a username before changing the password
**Cause**: 
- regression bug from "Install wizard on first launch" feature

fix: cannot change user password

---

.github/workflows/docker.yml

something changed in the docker-build-push action.
added `workflow_dispatch` to be able to manually run those docker releases via github

bug: docker upload workflow

---

lnbits/core/views/admin_api.py

this can be useful when debugging invoice listeners. in the future there coud be some monitor dashboard on the admin ui.

feat: add `monitor` admin endpoint for listeners

---

.github/workflows/regtest.yml
tests/helpers.py

regtest not uses `lnbits/lnbits` aswell

fix: regtest use new docker hub address

---

lnbits/app.py

The use of `click` in the app itself is an issue. The `click.echo()` method tries to consume the command line arguments.
In this example `port`:
```sh
poetry run lnbits --port 5555
```
The error was: 
```
click.exceptions.NoSuchOption: No such option: --port
```
This issue was reported for a docker run. 
**Steps**:
- remove the files of an extension
- start server with this command `poetry run lnbits --port 5555`
An exception is thrown:
```
Error: No such option: --port
2024-02-09 12:29:34.32 | ERROR | Traceback (most recent call last):
File "/Users/moto/Library/Caches/pypoetry/virtualenvs/lnbits-_FscvqzI-py3.9/lib/python3.9/site-packages/click/core.py", line 1077, in main
with self.make_context(prog_name, args, **extra) as ctx:
File …
```

fix: use `get_dbversions` instead of `db_versions`

---

.env.example
README.md
docs/guide/wallets.md
lnbits/settings.py
lnbits/wallets/breez.py

Loads Greenlight partner certificate and key from either file/hex/base64 settings for use in the Breez SDK wallet.

Add Greenlight partner certificate settings to Breez SDK wallet

---

lnbits/core/views/generic.py

Report from @callebtc:
> I noticed a bug in the extension manager: if the internet connection doesn't work (or possibly if the github token is invalid), lnbits doesn't load up any extensions at all. there should probably be some sort of timeout in during which the extension manifest is polled and if it fails, the extensions should still be visible in the extension manager. I've noticed this because I had a firewall on that silently blocked requests from lnbits and no extensions showed up even though I had them installed.
The logic was there, but due to a bug the wrong filtering took place.

fix: show installed extensions when manifest cannot be reached

---

lnbits/nodes/lndrest.py

closes: #2258
The LND api returns the timestamps as strings which wasnt caught because strings can be appended and pydantic just converted it to an integer by itself.

fix: correct invoice expiry for lndrest

---

lnbits/core/crud.py
lnbits/core/views/auth_api.py
lnbits/settings.py

closes #2212 
See issue https://github.com/lnbits/lnbits/issues/2212 . Prepare to allow more SSO providers (eg: [Authentik](https://goauthentik.io/), [Keycloak](https://www.keycloak.org/) or [Authelia](https://www.authelia.com/).) 
The `/auth` endpoint now does not explicitly uses `google` or `github`. Any number of SSO Providers can be used now.
In order to add a new provider one must:
1. Implement the `ProviderSSO` class (eg: `KeycloakSSO`)
- this class must be added in the `lnbits.core.sso.provider`. The full namespace is `lnbits.core.sso.provider.ProviderSSO`
- several implementation examples can be found here: https://github.com/tomasvotava/fastapi-sso/tree/master/fastapi_sso/sso
- ideally the new implementation is accepted by `fastapi-sso`. Please also  open a PR to the above repo …

refactor: generalize SSO auth

---

lnbits/helpers.py
lnbits/tasks.py

DEPRECATED: Use the repo name instead, will be removed in the future
before: `register_invoice_listener(invoice_queue, get_current_extension_name())`
after: `register_invoice_listener(invoice_queue, "my-extension")`

feat: deprecate get_current_extension_name

---

lnbits/core/tasks.py
lnbits/tasks.py

logging and validation should be handled by the dict itself.
adds unnecessary complexity where nothing is gained.

refactor: remove SseListenerDict

---

Dockerfile

because it could not resolve localhost

fix: docker image invoice listener were not stopping

---

lnbits/tasks.py

changes the `register_invoice_listener` to use a non unique key so you its not possible to have a listeners running twice and throw a warning when trying to.
we should discourage use of `get_current_extension_name` its not needed, easy enough for the extension dev to pass the extension name or whatever he wants his listener to be named.
@talvasconcelos  some extension still don't use a name, but they should! can you check that? also they should not use `get_current_extension_name()` anymore

feat: unique invoice listeners for extensions

---

lnbits/core/helpers.py
lnbits/core/views/api.py
lnbits/settings.py

Related to:
- https://github.com/lnbits/splitpayments/issues/14
- https://github.com/lnbits/scrub/issues/7
- https://github.com/lnbits/lnbits/pull/2278
When an extension is uninstalled/upgraded the background tasks have to be stopped.
Issue:
- the background tasks were being stopped by calling a REST API endpoint on `localhost`
- `localhost` is not always accessible (docker container for example)
Solution:
- first try to call the `stop` logic using a normal python function call

fix: extension stop background work

---

lnbits/app.py
lnbits/tasks.py
lnbits/wallets/alby.py
lnbits/wallets/lnpay.py
lnbits/wallets/opennode.py

it was only used in lnpay, opennode and alby which all had it disabled anayways with a pretty old TODO, so i guess the feature is disabled for a y ear now and nobody used it, so i just removed it

refactor: remove unused webhook handler for wallets

---

lnbits/tasks.py

listeners used did not use the helper function

refactor: tasks should be run with internal `create_task` wrapper

---

lnbits/core/models.py
lnbits/core/views/api.py

Required while testing the APIs, but can be useful in general.
The new endpoint uses `check_user_exists` access level, so full user permissions is required to get all wallets.

feat: add get endpoint for user wallets

---

lnbits/app.py
lnbits/core/views/auth_api.py
lnbits/core/views/generic.py

Fixes:
- the account icon is not visible on Safari & Firefox
- the active wallet cookie not removed after logout
Before:
After:

Fix login logout on safari

---

tests/core/test_helpers_query.py

```PytestCollectionWarning: cannot collect test class 'TestModel' because it has a __init__ constructor (from: tests/core/test_helpers_query.py)```

test: fix TestModel warning

---

tools/preimage.py

`poetry run python tools/preimage.py`

feat: add tool preimage generator

---

lnbits/db.py
tests/core/test_db_fetch_page.py
tests/core/test_helpers_query.py
tests/helpers.py

feat: add group_by to fetch_page

---

lnbits/core/models.py
lnbits/wallets/corelightning.py
lnbits/wallets/corelightningrest.py

Payment state check should *only* return False if the payment 100% failed. Uncheckable entries should not enter the db in the first place, which we will be working on next.

bug: cln paymentstate check on error

---

lnbits/core/services.py

An warning message is shown in the logs when users update the settings:
```log
| WARNING | lnbits.core.services:update_cached_settings:716 | Failed overriding setting: is_super_user, value: True
```
This PR fixes the warning message.

fix: check if key present in `settings` before updating

---

lnbits/core/tasks.py

error is not raised, even if failed webhook would be marked as sent every time

fix: raise failed request to not run `mark_webhook_sent`

---

lnbits/core/crud.py
lnbits/core/views/api.py
lnbits/decorators.py
tests/core/test_db.py

The comment (now removed) explains the problem:
```python
```
The problem is that by specifying the `wallet id` the order is not enforced **if the same wallet is the sender and the receiver**.
An explicit `ORDER BY` has been added to the SQL statement.

fix: enforce order of payments

---

lnbits/core/models.py
lnbits/core/services.py
lnbits/wallets/alby.py
lnbits/wallets/base.py
lnbits/wallets/cliche.py
lnbits/wallets/corelightning.py
lnbits/wallets/corelightningrest.py
lnbits/wallets/eclair.py
lnbits/wallets/fake.py
lnbits/wallets/lnbits.py
lnbits/wallets/lndgrpc.py
lnbits/wallets/lndrest.py
lnbits/wallets/lnpay.py
lnbits/wallets/lntips.py
lnbits/wallets/opennode.py
lnbits/wallets/spark.py
lnbits/wallets/void.py
lnbits/wallets/zbd.py

The first parameter of `PaymentStatus` indicates the actual state (`success=True`, `failed=False`, `pending=None`).
This is hard to read and remember.
This PR uses 3 new **explicit** subclasses:
```py
class PaymentSuccessStatus(PaymentStatus):
paid = True
class PaymentFailedStatus(PaymentStatus):
paid = False
class PaymentPendingStatus(PaymentStatus):
paid = None
```

refactor: dev-friendly payment status name

---

lnbits/wallets/base.py
lnbits/wallets/fake.py
lnbits/wallets/lnbits.py

A payment status is pending when the `paid` value is none.
In the old implementation if a payment was failed (`paid == False`) then the `pending` property would be `True` (which is incorrect)

fix: pending property for PaymentStatus

---

poetry.lock
pyproject.toml

Bumping the Breez SDK to v0.3.6 mainly to upgrade the VLS signer to v0.11

Bump breez-sdk to 0.3.6

---

lnbits/static/js/service-worker.js
lnbits/templates/error.html

As people keep getting stuck on the error page

feat: added home button on error page

---

lnbits/core/views/tinyurl_api.py

- also use `wallet.wallet.id` as key instead of `wallet.wallet.inkey`

refactor: tiny url to use require decorators and `wallet.id`

---

lnbits/core/templates/admin/_tab_users.html

In the server administration, more precisely on the “Users” tab, `admin-users` and `allowed-users` cannot be removed. This was originally reported on https://github.com/lnbits/lnbits/issues/2297.
After a quick search through recent commits, the problem seems to have been created as part of a recent PR (https://github.com/lnbits/lnbits/pull/2252). 
This PR reverts some of those changes, in order for this functionality to work again.

bug: Fix regression. Admin-users and allowed-users can now be removed through the web interface

---

lnbits/app.py
lnbits/core/tasks.py

let the app have the responsibility to create the tasks not a helper function inside tasks.py. makes it way easier to follow on how those background tasks are ran.

refactor: move registering of tasks into `app.py`

---

Makefile
lnbits/core/templates/service-worker.js
lnbits/core/views/generic.py

use server_startup_time as the version
(the same trick we use for static files)
I have no idea how to test this, so please do test!

chore: remove CACHE_VERSION from service-worker.js

---

lnbits/core/views/api.py
lnbits/core/views/generic.py
lnbits/static/js/wallet.js
lnbits/templates/macros.jinja
lnbits/utils/exchange_rates.py

- refactor allowed_currencies into function to use in generic and api.
- remove currencies request in frontend move it to generic
- dont request balance on first payments fetch

feat: reduce initial requests on wallet page

---

lnbits/static/js/wallet.js

fiat amount not shown in balance on initial pageload, lets reintroduce the first fetch_balance to fix it.
maybe in the future balance call and wallet itself should give the current fiat value if the wallet uses fiat tracking so you dont need the extra conversion call

hotfix: initial currency conversion on balance

---

.github/actions/prepare/action.yml
.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/jmeter.yml
.github/workflows/make.yml
.github/workflows/regtest.yml
.github/workflows/release.yml
.github/workflows/tests.yml

gets rid of deprecating warnings in actions.

chore: update to node 20.x on workflows

---

.github/workflows/docker.yml
.github/workflows/release.yml

closes #2345
also removed the duplicate dockerhub upload for latest. that was kinda dump (i introduced it), because you could also manually tag a special release which would than always push to latest tag aswell which makes no sense.

bug: releasing docker image had invalid credentials

---

.github/workflows/jmeter.yml
integration/extensions-enable-all.jmx
integration/tpos.jmx

This PR introduces a new JMeter test. It does not change the code.
This test will check that:
- there are no backwards incompatible changes in `core` that affect the extensions (eg: some functions moved in `core` from one file to another and the extension fails to install)
- the vetted extensions do not use deprecated APIs

[test] add jmeter tests to install and enable all vetted extensions

---

lnbits/app.py
lnbits/core/views/generic.py
lnbits/middleware.py

removes warnings
```
tests/core/views/test_generic.py::test_core_views_generic
tests/core/views/test_generic.py::test_get_wallet_with_user_and_wallet
tests/core/views/test_generic.py::test_get_extensions
tests/core/views/test_public_api.py::test_core_views_generic
/home/dni/.cache/pypoetry/virtualenvs/lnbits-XeqO4Z-j-py3.10/lib/python3.10/site-packages/starlette/templating.py:178: DeprecationWarning: The `name` is not the first para
meter anymore. The first parameter should be the `Request` instance.
Replace `TemplateResponse(name, {"request": request})` by `TemplateResponse(request, name)`.
warnings.warn(
```

test: remove warnings for `TemplateResponse`

---

lnbits/commands.py
lnbits/db.py
pyproject.toml
tests/core/views/test_node_api.py
tools/i18n-check.py

dont use pythjons builts in functions name as variable

chore: adhere to ruff's `A`

---

lnbits/static/js/admin.js

fixing 307 requests making a request to `/settings/`

fix: remove trailing slash from admin.js

---

flake.nix
lnbits/app.py
poetry.lock
pyproject.toml
tests/conftest.py

recommended use: https://fastapi.tiangolo.com/advanced/events/?h=lifespan
threw warnings in pytest
```
tests/core/test_db.py::test_create_wallet_and_delete_wallet
/home/dni/repos/lnbits/lnbits/lnbits/app.py:467: DeprecationWarning:
on_event is deprecated, use lifespan event handlers instead.
Read more about it in the
[FastAPI docs for Lifespan Events](https://fastapi.tiangolo.com/advanced/events/).
@app.on_event("startup")
tests/core/test_db.py::test_create_wallet_and_delete_wallet
/home/dni/repos/lnbits/lnbits/lnbits/app.py:410: DeprecationWarning:
on_event is deprecated, use lifespan event handlers instead.
Read more about it in the
[FastAPI docs for Lifespan Events](https://fastapi.tiangolo.com/advanced/events/).
@app.on_event("shutdown")
```

refactor: use new fastapi lifespan instead of startup/shutdown events

---

lnbits/core/views/extension_api.py

should use `from http import HTTPStatus`

fix: fastapi status import

---

lnbits/commands.py
lnbits/db.py
lnbits/middleware.py
lnbits/nodes/base.py
lnbits/nodes/cln.py
lnbits/nodes/lndrest.py
lnbits/settings.py
lnbits/wallets/base.py
lnbits/wallets/fake.py
pyproject.toml
tools/i18n-ai-tool.py
tools/i18n-check.py

basically use `list` and `type` instead of `List` and `Type`
this is save to use for python3.9 and has been deprecated. also has some performance drawbacks.
read more here: https://docs.astral.sh/ruff/rules/non-pep585-annotation/

chore: adhere to ruff's `UP`

---

lnbits/py.typed

tasks.py:8: error: Skipping analyzing "lnbits.tasks": module is installed, but missing library stubs or py.typed marker [import-untyped]
https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports

feat: add PEP561 marker for types

---

lnbits/wallets/breez.py

The application should receive a `SendPaymentResponse` from the SDK when calling `send_payment()`. Within the response it contains the payment.

Fix mishandling of send_payment response

---

lnbits/wallets/phoenixd.py

There's a typo in phoenixd wallet's stream.
According to docs, is `payment_received` instead of `payment-received`
https://phoenix.acinq.co/server/api#payments-websocket

typo in phoenixd ws

---

.github/workflows/regtest.yml
lnbits/core/services.py
lnbits/core/views/payment_api.py
lnbits/wallets/alby.py
lnbits/wallets/base.py
lnbits/wallets/corelightning.py
lnbits/wallets/corelightningrest.py
lnbits/wallets/eclair.py
lnbits/wallets/lnbits.py
lnbits/wallets/lndgrpc.py
lnbits/wallets/lndrest.py
lnbits/wallets/phoenixd.py
tests/regtest/test_real_invoice.py
tests/wallets/fixtures/json/fixtures_rest.json
tests/wallets/fixtures/json/fixtures_rpc.json

This PR addresses an issue for **failed** `outgoing payments`.
If an outgoing payment (invoice paid by the user) is marked as failed, then it will be deleted after a certain time interval.
The (current) reason for deleting the failed outgoing payment is to unlock the user funds. Because while the payment is still present the amount is considered locked.
The issue is that sometimes the `outgoing payment` can be marked as failed for technical reason, BUT the invoice is not actually canceled.
The solution in this PR is to:
- never mark a payment as `failed` unless the funding source explicitly returns a status that says the payment is failed
- any technical errors will keep the invoice as `pending`
- make sure `get_payment_status` for all funding sources returns `failed` under _some_ …

fix: pay invoice status

---

lnbits/core/crud.py
lnbits/core/models.py
lnbits/core/views/api.py
lnbits/core/views/payment_api.py
lnbits/core/views/wallet_api.py
lnbits/decorators.py
tests/api/test_api.py

- refactor KeyChecker to be more approachable
- only 1 sql query needed even if you use `get_key_type`
- rename `WalletType` to `KeyType` wallet type was misleading

refactor: fix duplicate keychecker

---

lnbits/app.py
lnbits/core/views/payment_api.py
lnbits/exceptions.py

refactor exceptionhandlers into `exception.py` also now always throw payment error when pay_invoice and invoice errors when create_invoice.
return a status flag with the detailed error message. with a 520 response

refactor: catch payment and invoice error at fastapi exceptionhandler level

---

lnbits/commands.py
lnbits/core/crud.py
lnbits/core/migrations.py

payments are not deleted if we delete a wallet, so to get a accurate total representation of the lnbits balance we need to create the balances view based on the wallets table, not payments, else deleted balances will still show up.
2nd, `delete_unused_wallets` and `delete_accounts was` never working because they never got an `updated_at` time, so i just check if its null else i check to timedelta on created_at

fix: show proper total balances fix cleanups

---

lnbits/wallets/corelightning.py
lnbits/wallets/corelightningrest.py

```
2024-05-14 17:32:14.44 | WARNING |
lnbits.wallets.corelightning:pay_invoice:165 | RPC call failed: method:
pay, payload: {'bolt11': 'lnbc210n1pnru86xsp523xtewax3k7zam0ne8f36
4paz7dulmxf3g7f99xtynt4v5lzvgxqpp5l29euul4m0re896msdp6gawtlrrdctc97ftvh3udf4jrduuhk4tqhp5yd577hw58ty73gn9c2ekjytu39ysf33m2rfzetz37rqll86lsnhscqpjrzjqttftvqu0f5sneckep3lkwdut
7mmhhpcyjmlmnjn4hze8ed7pq88xrq4jsqqc8gqqyqqqqlgqqqqqqgq2q9qxpqysgqqzee8yulqs8s8yyllsjjmln6vetu6gq502cykcnzyqxs5mrd0hq899nauhjmklllvz7y2n2nvtg3c2z3ymvvc7pcc4f2jh4xufun7acqew4
htt', 'maxfee': 2000}, error: {'code': -32602, 'message': 'Invalid
bolt11: Prefix bc is not for regtest'}```

fix: add cln unspecified error code bolt11 error to errorcodes

---

lnbits/core/services.py
poetry.lock
pyproject.toml

Addresses: https://github.com/lnbits/lnbits/issues/2054
The rationale for this change is explained in the issue's discussion: https://github.com/lnbits/lnbits/issues/2054#issuecomment-2112247822
**Summary:** The Bolt 11 spec says that an invoice, without the `x` tag field specified, should expire by default in 1 hour (3600 seconds). The `bolt11` package used by lnbits does not implement this, setting the `expiry` to `None` when the tag field is absent. The current implemented fallback sets the expiration date to 1 month after the creation date, which is incompatible with the spec and creates the reported differences between lnbits and other tools that decode the same invoice.

Fix: Wrong expiration date in invoice details

---

lnbits/app.py
lnbits/commands.py
lnbits/core/crud.py
lnbits/core/views/extension_api.py
lnbits/core/views/generic.py
lnbits/decorators.py
lnbits/extension_manager.py
lnbits/settings.py

It was previously possible for a user to access an installed extension even if the user did not explicitly enabled that extension.
With this PR the `enable/disable` state for an extension is enforced for both the UI and the API.
Prerequisite for https://github.com/lnbits/lnbits/pull/2516
- choose an extension (`gerty` for example)
- access http://localhost:5000/gerty
- expected: `Not found`
- install `gerty` as admin (but do not enable)
- access http://localhost:5000/gerty
- expected: `User extension 'gerty' not enabled.`
- enable `gerty`
- access http://localhost:5000/gerty
- expected: extension properly loaded
- disable `gerty`
- access http://localhost:5000/gerty
- expected: `User extension 'gerty' not enabled.`
- enable `gerty`
- access http://localhost:5000/gerty
- expected: …

[fix] check user extension access

---

lnbits/core/models.py
lnbits/core/services.py
lnbits/decorators.py

Do not allow payments from extensions that are disabled by the user.
**Steps**:
- user enables `withdraw` extension
- user create  `withdraw link` and shares it
- user disables  `withdraw` extension
- `withdraw link` still working
**Expected Result**:
- `withdraw link` does not work until the `withdraw` extension is enabled again
**Note**:
- this functionality relies on the fact that extensions use the `"tag"` field in the "'extra'" options
-  this is not enforced in the code in any way at the moment
- the function `_check_wallet_balance` is a simple refactor (no business logic changes) it was required by the code check tools (parent function was getting too large)

[feat] Check payment tag

---

lnbits/wallets/phoenixd.py

Similar resolution as #2513, but leaves in comments and applies description.
Tested with lnurlp extension locally with phoenixd 0.1.5-6845a31 in testnet, with assignment of unhashed_description or memo.

fix: phoenixd wallet description field supports lnurlp

---

lnbits/decorators.py

Light decorator used to check if there is an authenticated user or not.
Does not enforce authentication.
Required when querying for user specific resources.

[feat] add `authenticated_user_id` decorator

---

.env.example
lnbits/core/crud.py
lnbits/core/services.py
lnbits/core/templates/admin/_tab_server.html
lnbits/core/views/api.py
lnbits/core/views/auth_api.py
lnbits/settings.py

Have a list of extensions which are pre-enabled for the regular users.
**Steps:**
- login as admin
- go to: Server > Server (tab)
- add the extensions that you want to pre-enable
- save
- create a new user
- the selected extensions should be enabled
Note: existing users will not get these extensions enabled by default.

[feat] add `default_user_extensions` setting

---

docs/guide/installation.md

websocket weren't working with that conf

docs: nginx websocket support for reverse proxy

---

lnbits/core/services.py
lnbits/core/views/api.py

The default wallet was created only if the user was accessing the UI right after register.
This fix creates the default wallet also when the user is created via an API call.

fix: always create default wallet for user

---

lnbits/tasks.py

While working on #2358, I noticed that the fee of an invoice is not applied when the invoice gets settled through the `paid_invoices_stream`. The dispatcher only sets pending to False, but it should do a proper status check since the `fee_msat` or `preimage` fields of the `PaymentStatus` are never set otherwise.

fix: proper status check in invoice paid callback

---

lnbits/app.py

so it does not block webserver start on saas instances and comes up faster if extensions are reinstalled

fix: install extensions async

---

lnbits/utils/exchange_rates.py

old code for CZK:
```
https://blockchain.info/tobtc?currency=CZK&value=1 -> 0.00000064
1 / 0.00000064 = 1562500.0
```
new code for CZK:
```
https://blockchain.info/tobtc?currency=CZK&value=1000000 -> 0.63594724
1000000 / 0.63594724 = 1572457.4887690367
```
---
old code for USD:
```
https://blockchain.info/tobtc?currency=USD&value=1 -> 0.00001487
1 / 0.00001487 = 67249.49562878278
```
new code for USD:
```
https://blockchain.info/tobtc?currency=USD&value=1000000 -> 14.87099547
1000000 / 14.87099547 = 67244.99392238737
```

add bitpay and yadio fiat rate providers + increase precision of blockchain.info fiat rate provider

---

lnbits/middleware.py

closes #2599
special thanks to bitkarrot for figuring that out, it was actually initialized twice, the decorator alone is enough!
also was issue for first_install middleware, manually tested it

fix: random exceptions in logs in middleware

---

lnbits/core/models.py
lnbits/core/views/payment_api.py
lnbits/helpers.py

Some devices cannot handle a large response payload.
This PR adds the `filter_fields` optional field that only includes the filtered fields. If `filter_fields` is missing or an empty list then all fields are returned.
It only filters top-level fields.
**Request**:
```curl
curl --location 'http://localhost:5000/api/v1/payments/decode' \
--header 'Content-Type: application/json' \
--data '{
"data": "lnbc230n1pn20zexsp5yh56523hvkysgak3jyv3c4tj8jaljjwchpdr4sxfj0lf87lnshyqpp5u5enyfn0wyxmrcpdhrmc2sa3r385qdq9a2f9ntscnhvqezg334kqdq8xye8xcgcqpjrzjqvnwdyky2hw42nrsnwa5wzcv5lstkpq49amh69z9l59lxuy69qe6xrrpfyqqtlcqqgqqqqqqqqqqqzgq0q9qxpqysgqfqvvxnnd4j2s3yqn6j0xcdjf80ar76dvlrutwsalc6aevhaf6avhtlumuu3pctk3mstr0pk6e72jz5w7th5vtx5gn536z9feqsz5yuspqnahvd",
"filter_fields": ["amount_msat", "payment_hash"]
}' …
```

feat: filter response fields for `/api/v1/payments/decode`

---

lnbits/tasks.py

skips payment check if voidwallet is active

fix: skip pending payment check on void

---

lnbits/app.py

Set a max wait time of 60 seconds. After 7 retries, all future retries will have a 60 second max wait.

Set a maximium sleep time when retrying to connect to the funding source

---

lnbits/core/services.py
lnbits/exceptions.py
lnbits/lnurl.py

this is used multiple times in extensions to safeguard `views_lnurl.py` endpoint to not return a wrong lnurl error response.
you use it by just setting following on your lnurl router/view
```
withdraw_ext_lnurl = APIRouter(prefix="/api/v1/lnurl")
withdraw_ext_lnurl.route_class = LNURLErrorResponseHandler
```

feat: add generic lnurl error response handler

---

lnbits/core/models.py
tests/api/test_api.py

Addresses:  #2642 
The issue states that when an invoice is created using `msat` as a unit, the `sat` value is not calculated properly. Which is, in fact, true. 
Looking deeper at the code, we can see [`api_payments_create_invoice`](https://github.com/lnbits/lnbits/blob/65ecca2507fb474398504d1c792eb08a04666a6f/lnbits/core/views/payment_api.py#L125) relies on [`create_invoice`](https://github.com/lnbits/lnbits/blob/65ecca2507fb474398504d1c792eb08a04666a6f/lnbits/core/services.py#L123) to create the actual invoice, and that the latter uses [`calculate_fiat_amounts`](https://github.com/lnbits/lnbits/blob/65ecca2507fb474398504d1c792eb08a04666a6f/lnbits/core/services.py#L85) to get the amount in `sats` regardless of the selected unit/currency. 
`calculate_fiat_amounts` only supports the …

fix: add proper validation for the unit field when creating an invoice

---

lnbits/core/templates/admin/_tab_server.html

server tab with a hint that it is currently not used.
i ran into an issue developing an extension where i needed to know the url inside a task, where i cannot pass the `Request` object. so i depend on `settings.lnbits_baseurl` there

feat: add baseurl to admin ui settings

---

.gitignore
lnbits/app.py
lnbits/commands.py
lnbits/core/crud.py
lnbits/core/extensions/extension_manager.py
lnbits/core/extensions/helpers.py
lnbits/core/extensions/models.py
lnbits/core/helpers.py
lnbits/core/views/extension_api.py
lnbits/core/views/generic.py
lnbits/extension_manager.py
lnbits/helpers.py
lnbits/middleware.py
lnbits/settings.py
tests/unit/test_settings.py

Derived from: https://github.com/lnbits/lnbits/issues/2540
If two extensions (`ext_a` and `ext_b`) have overlapping redirect paths then the second one (`ext_b`) will be installed but deactivated.
If `ext_a` is deactivated, then `ext_b` can be activated.
See test scenario here:
The PR with JMeter tests: https://github.com/lnbits/lnbits-extensions/pull/415
This PR extended a bit outside the scope defined in the title. Some of the concepts in extension manager got clearer and I've decide to also refactor the extension manager and add tests to guard for future bugs.
Short explanation of the relevant changes per file:
- `app.py` (refactor)
- extract redirect logic from this file to `settings.activate_extension_paths`
- `commands.py` (refactor)
- update function calls and imports
- `crud.py` …

Fix overlapping redirect paths

---

lnbits/core/models.py

it actually means is_internal and internal payments cant fail so we return success status

refactor: rename is_uncheckable

---

lnbits/core/views/payment_api.py
lnbits/core/views/wallet_api.py
lnbits/decorators.py

its always better to explicitly choose `require_invoice_key` or `require_admin_key` makes the code more readable and you always know upfront which key you need.
breaking change for 1.0.0

refactor: remove `get_key_type` decorator

---

lnbits/core/crud.py

`webpush_settings` table does not exist when it got merged it used `lnbits.settings`

chore: remove unused crud for webpush settings

---

lnbits/wallets/boltz.py

Boltz rejects nbsp char (produced by JS Intl.NumberFormat api), so simply replace it with normal space

fix(boltz): sanitize invoice description

---

lnbits/__init__.py

makes it clear what extensions are expected to use and also makes future changes to the structure of core safer because extension can just depend on ```from lnbits import require_admin_key``` for example.
TODO: still couple of exports from `crud.py` are missing, still thinking about making proper services.py fn's instead of extension import from core crud

feat: explicitly export for extensions from `__init__.py`

---

lnbits/core/models.py
lnbits/core/templates/core/wallet.html
lnbits/core/views/payment_api.py
lnbits/static/js/wallet.js
tests/api/test_api.py

This pull request introduces support for NFC payments when receiving Lightning payments in the wallet. It also enhances the receive dialog to display the invoice amount in both satoshis and the selected fiat currency.
1. NFC Payment Support:
- Users can now receive payments via NFC-enabled LNURL-withdraw links.
- When the device supports NFC, the receive dialog prompts the user to tap an NFC tag to pay the invoice.
- The app reads the NFC tag and automatically processes the payment if it contains a valid LNURL-withdraw link.
- Notifications are provided throughout the NFC reading and payment process.
2. Receive Amount Display:
- The receive dialog now displays the invoice amount in satoshis and fiat currency.
- Provides clarity to users about the amount being requested.
3. NFC Support …

Add NFC Payment Support and Display Receive Amount in Receive Dialog

---

lnbits/app.py
lnbits/core/models/extensions.py
lnbits/core/services/extensions.py
lnbits/settings.py

In order to check if an extension was previously installed check if there is an `upgrade_hash` instead of checking `self.module_name in sys.modules`

fix: check the settings for extension installed

---

Makefile
lnbits/core/crud/settings.py
lnbits/core/migrations.py
lnbits/core/services/settings.py
lnbits/settings.py

Previously the `settings` were saved as JSON in DB. This made it hard to update a particular value.
This PR introduces a new table called `system_settings` where the values are saved like so:
- the value is serialised with `json.dumps()` and deserialised with `json.loads()` so the type is preserved (number, list, string, etc)
- the tag defaults to `core`, but it can be used in future by extensions (ex: `satspay`)

refactor: make settings key-value in DB

---

lnbits/app.py
lnbits/core/models/extensions.py
lnbits/core/templates/core/extensions.html
lnbits/settings.py

- allow the installation of extensions by simply 
- pasting the extension files at the  `LNBITS_EXTENSIONS_PATH`
- creating a symbolic link from the extension dir to the `LNBITS_EXTENSIONS_PATH
- eg: `ln -s $(pwd) /bla/bla/lnbits/data/extensions/extensions`
- improve the logic for determining if an extension is first install or upgrade
- minor UI refresh fixes

[feat] install extensions from dir

---

lnbits/core/crud/users.py

Postgres is more strict with `GROUP BY`.
Use explicit `WHERE` clause for wallet ID.

[fix] wallet search on postgres

---

lnbits/core/templates/admin/_tab_theme.html
lnbits/templates/base.html

Proper remove CUSTOM BADGE if it's no text is set

fix: don't show when custom badge is not set

---

lnbits/wallets/base.py
lnbits/wallets/lnpay.py
lnbits/wallets/opennode.py

Possible solution to #2045.
Instead of optionally polling on the frontend we can just emulate the behaviour of the invoices stream by regulary polling the currently pending invoices. It shouldnt be too big of a difference in regards to rate limiting because whether the browser or the invoice task polls doesnt matter.

feat: emulate behaviour of paid_invoices_stream for wallets that dont support it

---

lnbits/core/templates/node/_tab_channels.html
lnbits/core/templates/node/index.html
lnbits/core/views/node_api.py
lnbits/nodes/base.py
lnbits/nodes/cln.py
lnbits/nodes/lndrest.py
tests/regtest/test_x_node_api.py

- `set_channel_fees` for node abstract
- api to change fees per channel
- show fees on channel view in frontend
- set fees per channel in frontend
- `CHANNELD_SHUTTING_DOWN` and `AWAITING UNILATERAL` into `pending` state
copy shorts cuts and fee edit on  channel list

feat: nodemanager, view and edit channels fees

---

lnbits/wallets/nwc.py

If the WebSocket is already closed when a subscription times out (e.g., due to a relay restart or dropped connection), the NWC funding source fails to send the CLOSE event, resulting in an exception. This prevents the subscription from being marked as closed and removed from the subscription list. Consequently, LNbits attempts to close the subscription repeatedly.
This PR resolves the issue by ensuring subscriptions are marked as closed and removed from the list before the CLOSE event is sent.

fix: NWC mark and remove subs before sending close request

---

lnbits/wallets/nwc.py

Gives up connecting to the nwc service if it doesn't respond for 2 minutes.
Closes https://github.com/lnbits/lnbits/issues/2883 .

fix: Add timeout to wait_for_connection

---

.gitignore

after updating extension i saw a dirty repo with the upgrades, this one ignores them for sure

fix: lnbits/upgrades where not ignore

---

lnbits/core/services/funding_source.py

fix: convert `BigDecimal` object to `int` (postgres only)

---

lnbits/core/templates/payments/index.html
lnbits/templates/components.vue

Differentiate between in/out pending payments.

change icon for pending

---

lnbits/helpers.py
lnbits/middleware.py

Required in order to fix `/upgrades` path issues
Failing reason: waiting for a new rc

feat: add `normalize_path ` helper

---

poetry.lock
pyproject.toml

that is currently only used by an extension but we could easily add fileuploads to core if needed

feat: add python-multipart for uploads

---

.env.example
lnbits/core/templates/admin/_tab_theme.html

- `admin` is not an extension
- temp disable a js rule that was causing

[fix] admin errors

---

lnbits/app.py

call the rate limiter init after the settings have been loaded from DB

[fix]: rate limiter init

---

docs/guide/installation.md
lnbits/core/models/audit.py
lnbits/core/models/extensions.py
lnbits/core/models/payments.py
lnbits/core/models/users.py
lnbits/core/models/wallets.py
lnbits/db.py
lnbits/nodes/base.py
lnbits/nodes/cln.py
lnbits/nodes/lndrest.py
lnbits/settings.py
lnbits/utils/cache.py
lnbits/wallets/__init__.py
lnbits/wallets/base.py
poetry.lock
pyproject.toml

python3.13 does fail on building greenlet.
https://python-poetry.org/docs/1.8/dependency-specification/#tilde-requirements
- removed python3.9 (had issues aswell)
- now poetry will throw errors when installing on wrong versions
- RUF007 formatting now works without python3.9

fix: python versions were defined incorrectly and remove 3.9

---

lnbits/core/services/__init__.py
lnbits/core/services/users.py
lnbits/core/views/auth_api.py
lnbits/helpers.py
lnbits/settings.py

- add validation for `int` and `float` settings
- remove SaaS settings and logic (use `first_install`) instead
- default to stronger default `auth_secret`
- create temporary `auth_secret` and store it in a file

[fix] settings cleanup

---

lnbits/core/services/notifications.py

Previously `"status"` was not returned.
```json
{"pending": false, "status": "success"}
```

feat: return payment status in the websocket response

---

lnbits/wallets/lnbits.py

This PR adds backwards compatibility to handle both the new `bolt11` and legacy `payment_request` field names when creating invoices using an lnbits funding source.
- Added fallback to check for `payment_request` if `bolt11` is not present
- Used `data.get()` for safer key access
Previously, LNbits used `payment_request` as the key for BOLT11 invoices, but newer versions use `bolt11`. This change ensures our wallet implementation works with both versions, preventing potential issues when interacting with different LNbits instances.
resolves #3024

FIX: Backwards compatibility for creating invoice with lnbits funding source

---

lnbits/core/templates/core/index.html

Don't show the runs on scroll if the title is different than `LNbits` and denomination is different than `sats`

hide 'Runs On' scroll if title is not LNbits

---

lnbits/core/templates/core/wallet.html

Implemented font size scaling using CSS clamp() function to make wallet balance
text responsive to viewport width. The balance now properly fills available
space while shrinking when constrained by smaller viewports, maintaining readability across all device sizes without text overflow issues.
- Min size: 0.75rem (12px) prevents text from becoming too small on mobile
- Scaling: 10vw provides smooth resizing relative to viewport width
- Max size: 3rem (48px) caps growth on larger screens
- you may want to play with the values of the clamp function [mdn web docs clamp() fct](https://developer.mozilla.org/en-US/docs/Web/CSS/clamp)
- mobile
- desktop
- mobile
- desktop

[CHORE] add responsive text scaling with clamp() for wallet balance display

---

lnbits/utils/exchange_rates.py

The timeout was too short for some exchanges.
Now:
- longer timeout (3 sec instead of 0.5)
- parallel call for the exchanges API

fix: make parallel calls for exchages

---

lnbits/core/templates/users/index.html
lnbits/static/js/users.js

Add button to go directly to the payments page when search for wallet is done:

feat: show wallet payments on search

---

lnbits/core/models/notifications.py

Previous message did not include node balance:
```
LNbits Demo
SERVER STATUS
Up time: 00:01:53.
Accounts: xxx.
Wallets: xxx.
In/Out payments: xxx/yyy.
Pending payments: xxxx.
Failed payments: xxx.
LNbits balance: xxx sats.
```

fix: include node balance in server status

---

lnbits/commands.py

Related to: https://github.com/lnbits/lnbits/issues/3096
```sh
Usage: lnbits-cli users [OPTIONS] COMMAND [ARGS]...
Users related commands
Options:
--help  Show this message and exit.
Commands:
cleanup-accounts  Delete all accounts that have no wallets
new               Create a new user bypassing the system...
``` 
```sh
$ poetry run lnbits-cli users new -u new_user_05 -p secret1234
User 'new_user_05' created. Id: '60d9973cc8ce4412b75cc9bec0d5a919'
```
This PR also fixes the `delete-settings` command which was still using the old DB Table name.

feat: create new user from the command line

---

lnbits/templates/print.html

Fixes all failing pages that rely on `print.html`
- after V1 is released we may have to comeback and make a proper print template

bug: add the defaults else it fails

---

lnbits/wallets/lndrest.py

I've run into this error:
> asyncpg.exceptions.DataError: invalid input for query argument $5: '0' ('str' object cannot be interpreted as an integer) 
This occurred during an UPDATE on the apipayments table, where the fee column (expected to be an INTEGER) was given a string '0'.
I've tracked it to this line in tasks.py:
`payment.fee = status.fee_msat or 0`
While fee is declared as an int in the Payment model, the source of fee_msat (status.fee_msat) can occasionally be a string (e.g., '0'). This can happen when LN backend APIs (such as lnd) return large integers as strings in JSON.
So I'm suggesting this little fix for lndrest.

fix: Explicitly convert lndrest fee_msat to int

---

lnbits/core/templates/core/wallet.html

Reported here: https://github.com/lnbits/lnbits/issues/3117
Also added a small refactoring for using positive conditions (`==` instead of `!=`)

fix: mask for fiat amount

---

lnbits/core/services/payments.py

Ensure that fee_reserve always operate on the absolute value of amount_msat internally. This removes the need to call abs() in calling code and reduces the risk of inconsistent fee behavior.
Previously, this inconsistency caused the default 2000 msat limit to apply to all external payments, even for much larger amounts, due to percentage fee reserve being calculated on a negative input.

fix: Normalize fee_reserve amount value 

---

lnbits/core/crud/payments.py
lnbits/core/models/payments.py
lnbits/core/services/notifications.py
tests/unit/test_pay_invoice.py

Reported here: https://github.com/lnbits/lnbits/issues/3114
- `webhook_status` is `TEXT` in DB
- use `payment.json()` instead of `payment.dict()`
- fix error logging (include error in message, not as extra param)
- add webhook unit test

fix: webhook call on invoice pay

---

lnbits/core/crud/payments.py
lnbits/core/crud/wallets.py
lnbits/core/views/payment_api.py
tests/unit/test_pay_invoice.py

Update API to allow fetching all payments from all wallets for a particular user.
Filter criteria can apply.
Endpoint: `/api/v1/payments/all/paginated`
**Example** when user id login is allowed (`usr` query param present):
```curl
curl --location --request GET 'http://localhost:5000/api/v1/payments/all/paginated?limit=25&offset=0&sortby=created_at&direction=desc&usr=94c408ff520e42d1a16685eaea681563'
```
Example using an access token:
```curl
curl --location --request GET 'http://localhost:5000/api/v1/payments/all/paginated?limit=25&offset=0&sortby=created_at&direction=desc' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJ1c3IiOiI5NGM0MDhmZjUyMGU0MmQxYTE2Njg1ZWFlYTY4MTU2MyIsImF1dGhfdGltZSI6MTc0NTgzNjIwMCwiZXhwIjoxNzc3MzcyMjAwfQ.eKZsXeWCsG2lS8ItKogLZ2zQb …
```

[feat] fetch all payments for user

---

lnbits/core/crud/payments.py
lnbits/core/services/payments.py
lnbits/tasks.py
lnbits/wallets/alby.py
lnbits/wallets/base.py
lnbits/wallets/cliche.py
lnbits/wallets/corelightning.py
lnbits/wallets/corelightningrest.py
lnbits/wallets/eclair.py
lnbits/wallets/fake.py
lnbits/wallets/lnbits.py
lnbits/wallets/lndgrpc.py
lnbits/wallets/lndrest.py
lnbits/wallets/lntips.py
lnbits/wallets/nwc.py
lnbits/wallets/phoenixd.py
lnbits/wallets/spark.py
lnbits/wallets/zbd.py
tests/regtest/test_real_invoice.py
tests/regtest/test_services_create_invoice.py
tests/regtest/test_services_pay_invoice.py
tests/wallets/fixtures/json/fixtures_rpc.json

pass the preimage generated in `create_invoice` from `InvoiceResponse` to the service to be persistent in the payment model and database
- issue incoming payments did not have the preimage
- issue were `PaymentSuccessStatus()` overwrote an existing preimage with None

feat: preimages for incoming payments, fundingsource saves preimage on `create_invoice` 

---

lnbits/core/models/misc.py
lnbits/core/models/users.py

https://github.com/pyca/bcrypt/issues/684#issuecomment-2430047176
```
WARNING:passlib.handlers.bcrypt:(trapped) error reading bcrypt version
Traceback (most recent call last):
File "/root/.cache/pypoetry/virtualenvs/lnbits-S_y84ukP-py3.12/lib/python3.12/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
version = _bcrypt.__about__.__version__
^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
```

fix: `_bcrypt.__about__.__version__` log warning

---

lnbits/db.py
tests/unit/test_crud_payments.py

This PR resolves an issue with the search functionality that was failing in SQLite environments due to the use of the `concat()` function, which is not available in SQLite. The fix replaces this with the SQL standard string concatenation operator `||`, which is supported across SQLite, PostgreSQL, and CockroachDB.
- Modified the `where()` method to use the `||` operator for string concatenation
- Added handling for NULL values using COALESCE to prevent NULL propagation in search expressions
When attempting to perform searches on SQLite databases, the application was throwing the following error:
```
(sqlite3.OperationalError) no such function: concat 
[SQL: SELECT * FROM apipayments WHERE wallet_id = ? AND status != ? AND lower(concat(memo, amount, wallet_id, tag, status, time)) LIKE ? …
```

[FIX] Fix database compatibility issue in search query builder for payments filter

---

lnbits/core/views/auth_api.py
lnbits/core/views/payment_api.py
lnbits/decorators.py
lnbits/templates/error.html
tests/api/test_admin_api.py
tests/api/test_auth.py
tests/unit/test_decorators.py

- Use 401 when credentials are missing or incorrect
- Use 403 when credentials are correct, but access is not allowed.
**Problem**:
When the server auth secret is changed, all the client side tokens are invalidated.
This lead to an infinite loop from the `wallet` -> `error` -> `login` -> `wallet` -> ....
- user token is invalidated (by server side secret update)
- user goes to `wallet` page
- user is redirected to `error` page (invalid token)
- error page on `401` redirects to `login` page
- `login` page finds a token (though invalid) and redirects to `wallet` page
**Solution**:
- narrow the `401 UNAUTHORIZED` returned codes
- use `403 FORBIDDEN` where possible
- on error page logout if `401 UNAUTHORIZED` is retuned

fix: better differentiation between `UNAUTHORIZED` and `FORBIDDEN`

---

lnbits/core/templates/core/wallet.html
lnbits/static/js/wallet.js

There's no way to know when NFC is disabled. 
This PR checks if the user is trying to receive an LNURLw, is which case the create invoice doesn't need to start the NFC reader. 
On mobile, with NFC capability, if the user has NFC turned off, when trying to redeem an LNURLw, NDEFReader would fail and show an alert. That is completely unnecessary and unrelated to what the user is doing. 
Fixes #3128

fix: do not ask for NFC if not needed

---

Dockerfile
docs/guide/installation.md

This PR allows community users to reuse the Dockerfile with more flexibility by overriding the default arguments to `poetry install` with `--build-arg POETRY_INSTALL_ARGS="-E breez"`, for example. Specifically enables the `breez` and `liquid` optional dependencies, among other options supported by the `poetry install` command.
The build argument defaults to `--only main` as per the prior hardcoded value and installation documentation.
Example usage: `docker build --build-arg POETRY_INSTALL_ARGS="-E breez" -t lnbits-with-breez .`

build: add POETRY_INSTALL_ARGS build argument to Dockerfile

---

lnbits/utils/crypto.py

Utility function that verifies Lightning Network payment preimages against corresponding payment hashes.
- Takes a hex-encoded preimage and expected payment hash
- Calculates SHA-256 hash of the preimage
- Compares calculated hash with the provided payment hash
- Returns a boolean indicating if the preimage is valid
Written to be used anywhere preimages should be verified, such as in my Strike wallet implementation.

feat: add verify_preimage utility function

---

lnbits/core/crud/__init__.py
lnbits/core/crud/settings.py
lnbits/core/views/admin_api.py
lnbits/static/js/admin.js

✅ Deletes settings and not reset super_user
✅ Deletes localstorage settings
✅ Already resarts, so removes need to restart.
Unsure if this is also used to reset super_user somewhere?

feat: dont reset superuser on delete settings endpoint

---

.env.example
Dockerfile

i hope with this defaults no so many people will run into https issues with lnurl.

feat: add ssl proxy settings to docker and `.env.example`

---

lnbits/core/templates/core/_api_docs.html

Adds a QR popup on the wallet info sidebar.
Closes #3191

feat: add QR code for wallet keys

---

lnbits/core/services/payments.py
lnbits/tasks.py

adding a helper function to add to a queue takes care of  the circular import issue

feat: add internal_invoice_queue_put to get rid of dynamic import

---

lnbits/exceptions.py
lnbits/settings.py

Fix condition for when an extension is available, but not installed yet.
**Problem**: the error message for a not found page was a 403 even if an extension was installed
**Before**: `403 Extension 'tpos' not installed. Ask the admin to install it.`
**After**: `404 Page Not found`

fix: condition for available, but not installed extension

---

lnbits/core/crud/audit.py
lnbits/core/crud/extensions.py
lnbits/core/crud/payments.py
lnbits/core/crud/users.py
lnbits/core/crud/wallets.py
lnbits/core/migrations.py
lnbits/db.py
pyproject.toml

Some SQL queries are built by string concatenation.
Even if the values are sanitized this is still a code smell (that `bandit`) reports.
This PR fixes some SQL queries to not use string concatenation. For the rest of them it adds comments explaining why they are safe.

[fix] bandit sql warnings

---

lnbits/app.py
lnbits/utils/logger.py

The LNbits version was logged only after the migration was done. If something went wrong during the migration then we could not find the LNbits version from the logs.
**Extra**: add a log with the duration for the server to start.
New start log:
New time log:

feat: better server start logging

---

lnbits/core/models/users.py
poetry.lock
pyproject.toml

passlib does not seemed to be maintained for a longer time and runs into some combatibility issues soon and already throws warning

chore: replace passlib with bcrypt

---

lnbits/core/services/lnurl.py

dont check for redundant `LnurlPayActionResponse` this somehow failed but lnurl lib actually already verifies it.

bug: propergate LnurlErrorResponse in lnurl service and dont checks for redundant `LnurlPayActionResponse`

---

flake.nix
nix/modules/README.md
nix/modules/lnbits-service.nix

The current LNBits NixOS service module (`nix/modules/lnbits-service.nix`) has several issues that prevent it from working with the flake-built Python virtual environment package:
1. **Missing `src` attribute**: The module expects `cfg.package.src` but the flake builds a Python virtual environment package that doesn't have a `src` attribute
2. **Incorrect binary path**: `lib.getExe` resolves to the wrong binary name (`lnbits-env` instead of `lnbits`)
3. **Wrong working directory**: The service needs to run from where the Python package's static files and templates are located
This PR fixes the service module to work correctly with the virtual environment package structure produced by the flake.
```diff
- LNBITS_PATH = "${cfg.package.src}";
```
The `LNBITS_PATH` environment variable was …

FIX:  Flake and Module for NixOS deployment

---

lnbits/core/views/payment_api.py

The payment extra can contain sensible information.

fix: hide payment details for failed payments
