- lnbits/__init__.py
- lnbits/bolt11.py
- lnbits/core/__init__.py
- lnbits/core/crud.py
- lnbits/core/models.py
- lnbits/core/services.py
- lnbits/core/views/lnurl.py
- lnbits/decorators.py
- lnbits/extensions/amilk/__init__.py
- lnbits/extensions/diagonalley/__init__.py
- lnbits/extensions/events/__init__.py
- lnbits/extensions/example/__init__.py
- lnbits/extensions/tpos/__init__.py
- lnbits/extensions/withdraw/__init__.py
- lnbits/helpers.py
- lnbits/wallets/clightning.py
- lnbits/wallets/lndgrpc.py
- lnbits/wallets/lndrest.py
This builds on @eillarra's earlier commit to fix or ignore all type errors so that the CI will not fail on every PR anymore but only if it actually introduces potential bugs. Previous discussion happened in #22.
> Fix mypy errors

- .env.example
- README.md
- docs/devs/installation.md
- lnbits/core/templates/core/index.html
- lnbits/extensions/events/templates/events/_api_docs.html
- lnbits/extensions/events/templates/events/index.html
- lnbits/extensions/lnticket/templates/lnticket/_api_docs.html
- lnbits/extensions/paywall/templates/paywall/_api_docs.html
- lnbits/extensions/paywall/templates/paywall/display.html
- lnbits/extensions/paywall/templates/paywall/index.html
- lnbits/extensions/tpos/templates/tpos/_api_docs.html
- lnbits/extensions/withdraw/templates/withdraw/_api_docs.html
- lnbits/templates/base.html
- package-lock.json
- package.json
Working in some things I noticed while setting up the project locally.
> README improvements

- lnbits/extensions/lnurlp/templates/lnurlp/index.html
> Consider port number on lnurlp URL 

- lnbits/core/crud.py
- lnbits/core/models.py
- lnbits/core/views/api.py
- lnbits/extensions/lndhub/README.md
- lnbits/extensions/lndhub/__init__.py
- lnbits/extensions/lndhub/config.json
- lnbits/extensions/lndhub/decorators.py
- lnbits/extensions/lndhub/migrations.py
- lnbits/extensions/lndhub/templates/lndhub/_instructions.html
- lnbits/extensions/lndhub/templates/lndhub/_lndhub.html
- lnbits/extensions/lndhub/templates/lndhub/index.html
- lnbits/extensions/lndhub/utils.py
- lnbits/extensions/lndhub/views.py
- lnbits/extensions/lndhub/views_api.py
Work in progress.
For operating an lnbits wallet from Bluewallet or Zeus.
> lndhub extension

- lnbits/extensions/lnurlp/models.py
- lnbits/extensions/lnurlp/views_api.py
- lnbits/extensions/withdraw/models.py
- lnbits/settings.py
Fix proposed by @eillarra, following discussion on https://t.me/lnbits/5179.
> Use PREFER_SECURE_URLS, get rid of FORCE_HTTPS hacks

- docs/devs/installation.md
> docs: fix typo in purerpc package

- lnbits/core/services.py
- lnbits/core/static/js/wallet.js
- lnbits/core/templates/core/wallet.html
- lnbits/core/views/api.py
- lnbits/extensions/lnurlp/templates/lnurlp/display.html
- lnbits/static/js/base.js
- lnbits/static/js/components.js
- lnbits/wallets/base.py
- lnbits/wallets/lnpay.py
- lnbits/wallets/opennode.py
- lnbits/wallets/spark.py
This PR closes https://github.com/lnbits/lnbits/issues/63.
> lnurl-withdraw and lnurl-pay support from the core wallet

- lnbits/core/models.py
- lnbits/core/services.py
- lnbits/core/static/js/wallet.js
- lnbits/core/templates/core/wallet.html
- lnbits/core/views/api.py
- lnbits/extensions/usermanager/views_api.py
- lnbits/static/js/base.js
> lnurl-auth from lnbits wallets to services.

- lnbits/extensions/withdraw/templates/withdraw/print_qr.html
This fixes the qr code voucher printing on my raspiblitz. It would be great to have it merged and moved the raspiblitz tag to. thx.
> fix #125 qrcode printing

- lnbits/core/crud.py
- lnbits/core/migrations.py
- lnbits/core/models.py
- lnbits/core/services.py
- lnbits/core/tasks.py
- lnbits/core/templates/core/_api_docs.html
- lnbits/core/views/api.py
- lnbits/static/js/base.js
- lnbits/static/js/components.js
> specify webhooks from invoice creation and call them.

- lnbits/app.py
- lnbits/extensions/captcha/README.md
- lnbits/extensions/captcha/__init__.py
- lnbits/extensions/captcha/config.json
- lnbits/extensions/captcha/crud.py
- lnbits/extensions/captcha/migrations.py
- lnbits/extensions/captcha/models.py
- lnbits/extensions/captcha/static/js/captcha.js
- lnbits/extensions/captcha/templates/captcha/_api_docs.html
- lnbits/extensions/captcha/templates/captcha/display.html
- lnbits/extensions/captcha/templates/captcha/index.html
- lnbits/extensions/captcha/views.py
- lnbits/extensions/captcha/views_api.py
Not sure if it's useful but I finished it and wanted to share it. 
[quick demo](https://www.youtube.com/watch?v=HLxUdppn0k4)
Basically it generates a code snippet any website can integrate to request payment as a proof of humanity aka captcha.
After payment, website can check if checkbox is checked and allow the user to continue. 
Surely at this stage it will be easy to bypass but if people use it, we can improve further.
> captcha extension added

- Pipfile
- Pipfile.lock
- lnbits/extensions/withdraw/models.py
- lnbits/extensions/withdraw/templates/withdraw/index.html
- lnbits/extensions/withdraw/views.py
The image is generated from the LNURL id, so unique LNURLws are compatible.
Makes sense to add the same function to LNURLp
> Creates LNURLw image folks can embed 

- .env.example
- .github/workflows/tests.yml
- docs/guide/wallets.md
lnpay.co/v1 -> api.lnpay.co/v1
> Update default LNPay.co endpoints

- lnbits/core/crud.py
- lnbits/core/static/js/wallet.js
- lnbits/core/templates/core/wallet.html
- lnbits/extensions/livestream/README.md
- lnbits/extensions/livestream/__init__.py
- lnbits/extensions/livestream/config.json
- lnbits/extensions/livestream/crud.py
- lnbits/extensions/livestream/lnurl.py
- lnbits/extensions/livestream/migrations.py
- lnbits/extensions/livestream/models.py
- lnbits/extensions/livestream/static/js/index.js
- lnbits/extensions/livestream/tasks.py
- lnbits/extensions/livestream/templates/livestream/_api_docs.html
- lnbits/extensions/livestream/templates/livestream/index.html
- lnbits/extensions/livestream/views.py
- lnbits/extensions/livestream/views_api.py
- lnbits/static/js/base.js
Featured in https://twitter.com/cryptograffiti/status/1380669276948819969.
> DJ Livestream extension

- docs/guide/installation.md
Added missing step about installing python3 virtual environment
> note on virtualenv installation

- README.md
> Nearly undetectable typo fix.

- lnbits/extensions/lnurlp/views_api.py
> Enforce https on Success URL for lnurlp

- .env.example
Adding what they are called in the website to add clarity
> Adding comment for LNPay

- lnbits/extensions/lnurlp/lnurl.py
- lnbits/extensions/lnurlp/static/js/index.js
Fixed anoying behavior of keeping form data state after creation or update
> Fix form reset on LNURLp

- docs/devs/installation.md
- lnbits/extensions/lnurlp/static/js/index.js
- lnbits/extensions/subdomains/README.md
- lnbits/extensions/usermanager/README.md
- lnbits/extensions/usermanager/templates/usermanager/index.html
Updates for user manager and subdomains extensions
> Documentation Updates

- lnbits/extensions/lnurlp/lnurl.py
This is a quick and dirty fix of issue #212.  
Partially reverts previous changes from commit 5fbd1f08c46fd223e34dc233b1254a01e25e0070
Re-implements the change in a slightly different way.
I am not familiar with the rest of the codebase, so I structured the change in a way that hopefully doesn't break anything.
> Fixes #212

- lnbits/extensions/lnurlp/static/js/index.js
Fixes https://github.com/lnbits/lnbits/issues/214
> Fixed issue deleting lnurlp

- lnbits/extensions/satspay/README.md
- lnbits/extensions/watchonly/README.md
Watch Only and SatsPayServer documentation update
> Watch Only and SatsPayServer documentation update

- docs/guide/installation.md
This just adds a missing backtick
> Fix codeblock in guide

- lnbits/extensions/lnticket/__init__.py
- lnbits/extensions/lnticket/tasks.py
- lnbits/extensions/lnticket/templates/lnticket/display.html
- lnbits/extensions/lnticket/templates/lnticket/index.html
- lnbits/extensions/lnticket/views.py
changed polling to invoice listener
fixes issue #213
> changed polling to invoice listener on lnticket extension

- docs/guide/installation.md
Credit to @Vinnie64 for pointing out one of the errors to me
> Fix typos and make small improvements

- lnbits/extensions/withdraw/lnurl.py
The current extension authorizes concurrent withdraw and
In this case, 'used' and 'wait time' are not properly updated by api_lnurl_callback function.
As a result, the usage limit can be exceeded if too many concurrent withdrawal are performed at the same time. 
This PR is a proposition to fix this behavior.
> Fix concurrent withdrawal behavior

- .env.example
- lnbits/app.py
- lnbits/static/js/base.js
- lnbits/templates/base.html
- allowed/availabe themes defined by admin
> Read .env themeing colors

- lnbits/extensions/lnurlp/templates/lnurlp/_api_docs.html
> Fix for #238 Minor issues in API documentation of lnurlp extension

- lnbits/extensions/jukebox/README.md
- lnbits/extensions/jukebox/static/js/index.js
Update for jukebox extension readme
removed the profit column showing 0
> Update for jukebox extension readme

- .env.example
- lnbits/settings.py
- lnbits/static/js/base.js
- lnbits/static/scss/base.scss
- lnbits/templates/base.html
Fixed having classic as default and always showing
Added classic as falback
Fixed naming issues from not pulling updated master
few minor logic steps
> Fix theme choosing

- .env.example
- lnbits/helpers.py
- disable all extensions with "all" now possible
- follow up on issue #243
> Small fix to disable all extensions

- lnbits/core/templates/core/wallet.html
Fixes the filter box on wallet page. Now filters payments by search
> Fix payments filter on wallets.html

- lnbits/extensions/streamalerts/templates/streamalerts/index.html
- lnbits/extensions/streamalerts/views_api.py
fixed create_service from sending html and showing correctly on create
> Fix UI issue on service creation

- lnbits/core/crud.py
- lnbits/core/static/js/wallet.js
- lnbits/core/templates/core/wallet.html
- lnbits/core/views/api.py
- lnbits/extensions/lnurlp/crud.py
- lnbits/extensions/usermanager/templates/usermanager/_api_docs.html
- lnbits/extensions/usermanager/views_api.py
- lnbits/static/js/base.js
- lnbits/wallets/lndgrpc.py
Some issue tracking and fixing
fixes issues #286 #268 #267 and #141
> Issue tracking

- lnbits/extensions/livestream/crud.py
fix producers create returning id
> fix livestream for postgres compatibility

- lnbits/extensions/copilot/crud.py
- lnbits/extensions/copilot/migrations.py
- lnbits/extensions/copilot/templates/copilot/index.html
Various fixes for database compatibility and a few minor HTML fixes
> Make copilot postgres ready

- lnbits/extensions/lnticket/crud.py
- lnbits/extensions/lnticket/migrations.py
- lnbits/extensions/lnticket/models.py
- lnbits/extensions/lnticket/templates/lnticket/display.html
- lnbits/extensions/lnticket/templates/lnticket/index.html
- lnbits/extensions/lnticket/views.py
- lnbits/extensions/lnticket/views_api.py
As suggested by Darthcoin in lnbits telegram.
Pretty much done, just need tidying and testing
> Adds flat rate to tickets 

- lnbits/wallets/lndrest.py
Only lines 113 and 115 are changes, the rest is the formatter.
> LndRestWallet fix: add fees to output

- lnbits/core/services.py
- lnbits/core/views/api.py
- lnbits/wallets/lndrest.py
> (FastAPI) LNDRest fee limit

- lnbits/extensions/satspay/templates/satspay/display.html
Fixing swapped tooltips within the satspay extension.
> satspay - swapped tooltips

- .github/workflows/tests.yml
- .gitignore
- Makefile
- docs/devs/development.md
- lnbits/extensions/bleskomat/exchange_rates.py
- lnbits/extensions/bleskomat/lnurl_api.py
- lnbits/extensions/bleskomat/models.py
- pytest.ini
- tests/conftest.py
- tests/core/test_views.py
- tests/core/views/test_generic.py
- tests/extensions/bleskomat/conftest.py
- tests/extensions/bleskomat/test_lnurl_api.py
- tests/helpers.py
- tests/mocks.py
Install test dependencies as follows:
```bash
./venv/bin/pip install pytest pytest-asyncio requests trio mock
```
And to run the tests:
```bash
make test
```
> Unit tests for FastAPI branch

- lnbits/extensions/lnurlpos/lnurl.py
- lnbits/extensions/lnurlpos/models.py
- lnbits/extensions/lnurlpos/templates/lnurlpos/_api_docs.html
- lnbits/extensions/lnurlpos/templates/lnurlpos/index.html
- lnbits/utils/exchange_rates.py
Make it compatible with https://github.com/arcbtc/LNURLPoS/pull/15 and https://github.com/fiatjaf/lnurlpos-app.
> lnurlpos v2 lnurl endpoint (backwards-compatible)

- .env.example
- docs/guide/wallets.md
See: https://twitter.com/lntxbot/status/1457341136918482945
> lntxbot.bigsun.xyz will expire soon, use lntxbot.com instead

- lnbits/core/views/api.py
- lnbits/extensions/lnurlpayout/README.md
- lnbits/extensions/lnurlpayout/__init__.py
- lnbits/extensions/lnurlpayout/config.json
- lnbits/extensions/lnurlpayout/crud.py
- lnbits/extensions/lnurlpayout/migrations.py
- lnbits/extensions/lnurlpayout/models.py
- lnbits/extensions/lnurlpayout/tasks.py
- lnbits/extensions/lnurlpayout/templates/lnurlpayout/_api_docs.html
- lnbits/extensions/lnurlpayout/templates/lnurlpayout/index.html
- lnbits/extensions/lnurlpayout/views.py
- lnbits/extensions/lnurlpayout/views_api.py
A very similar extension has already been pr'd, which was being worked on at the same time as LNURLPayout.
> Adds LNURLPayout: auto-payout to an LNURL

- lnbits/extensions/watchonly/views_api.py
get address endpoint is returning multiple addresses instead of just one.
there's a different endpoint for getting multiple!
> get only one address instead of multiple

- lnbits/app.py
Allow for external websites to call lnbits API
> allow all origins to request from lnbits

- lnbits/extensions/satspay/models.py
fix pydantic model error when creating an onchain only charge
> fix issue #472

- lnbits/utils/exchange_rates.py
get the conversion rate as float, instead of integer
> fix issue #452

- lnbits/decorators.py
- lnbits/extensions/satspay/__init__.py
- lnbits/extensions/satspay/crud.py
- lnbits/extensions/satspay/tasks.py
- lnbits/extensions/satspay/templates/satspay/display.html
- lnbits/extensions/satspay/templates/satspay/index.html
- lnbits/extensions/satspay/views.py
- lnbits/extensions/satspay/views_api.py
- lnbits/extensions/withdraw/templates/withdraw/display.html
Allow for create charge using the invoice key
> fix wallet key permission for create

- lnbits/core/tasks.py
- lnbits/extensions/lnurlp/views_api.py
- lnbits/extensions/streamalerts/views_api.py
- lnbits/extensions/tipjar/views_api.py
referencing issue #456
found a few places where _asdict() was still being used
> Change _asdict() to dict()

- docs/guide/wallets.md
Perhaps it can spare others time to know this upfront.
> Added warning for LNULRp issues and CLightningWallet

- lnbits/extensions/copilot/crud.py
copilot wasn't being created. user in create_copilot needed `""`
> fix copilot not getting created

- lnbits/core/crud.py
> remove restriction for positive amount to check outgoing payments

- requirements.txt
requirements.txt is missing secp256k1 package 
``` # python -m uvicorn lnbits.__main__:app --host 0.0.0.0  --reload
INFO:     Will watch for changes in these directories: ['/opt/lnbits-legend']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [2927190] using watchgod
Process SpawnProcess-1:
Traceback (most recent call last):
File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
self.run()
File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/opt/.env-lnbits/lib/python3.9/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
target(sockets=sockets)
File "/opt/.env-lnbits/lib/python3.9/site-packages/uvicorn/server.py", line 68, in …
```
> adding secp256k1 to requirements.txt 

- lnbits/extensions/diagonalley/__init__.py
- lnbits/extensions/diagonalley/crud.py
- lnbits/extensions/diagonalley/models.py
- lnbits/extensions/diagonalley/tasks.py
- lnbits/extensions/diagonalley/views.py
- lnbits/extensions/diagonalley/views_api.py
Things won't work as there's some differences between migrations.py and models.py
> UI is working

- lnbits/core/crud.py
- lnbits/core/views/generic.py
Fix for the disapearing admin extension bug.
The fix (setting, and maintaining the user with admin status), could probably be "higher up", @arcbtc , not sure it's needed though and may create some security issues! This way the server admin can add and remove admin status and it will be checked at delivery time!
> fix disapearing admin extension

- lnbits/core/crud.py
- lnbits/core/views/generic.py
Reverts lnbits/lnbits-legend#513
> Revert "fix disapearing admin extension"

- lnbits/extensions/livestream/__init__.py
- lnbits/extensions/livestream/views.py
fixed some small bugs in livestream extension that was throwing errors when I downloaded a fresh clone of lnbits and tried to launch it.
> fix livestream startup issue

- docs/guide/installation.md
> Remove suggestion to switch to FastAPI branch

- lnbits/core/templates/core/index.html
- lnbits/core/views/generic.py
Starlette's url_for doesn't take params
> Fix instant wallet form LNURLw

- lnbits/core/static/js/wallet.js
- lnbits/extensions/withdraw/templates/withdraw/display.html
the QR encoded string had the URL attached, so it failed on scanning with lnbits!
> Fix LNURLw QR code 

- lnbits/extensions/lnticket/templates/lnticket/index.html
Fixed faulty toggle and added a dialog for display the ticket. Other questions raised in the issue... number 1 seems it's like that by design, and last one we need to see how to handle
> Tickets issue #548

- lnbits/extensions/jukebox/crud.py
- lnbits/extensions/jukebox/views_api.py
user keyword replaced for "user" in DB, was failing in postgres
a bit more information, when error is sent if no music has been played in the jukebox!
> fix jukebox

- lnbits/extensions/copilot/crud.py
> fix copilots not being fetched

- lnbits/extensions/streamalerts/models.py
- lnbits/extensions/streamalerts/templates/streamalerts/display.html
- lnbits/extensions/streamalerts/views_api.py
fix create invoice and set "Anonymous" as default name
> fix streamalerts

- lnbits/core/services.py
Restore the previous version with only the invoice check.
> remove get_payment_status

- lnbits/core/views/api.py
Wasn't working, is working now.
> API: fix decodepay

- docs/guide/wallets.md
There should be base URL, not only hostname.
> Fixed docs about LND_REST_ENDPOINT

- lnbits/core/static/js/wallet.js
- lnbits/core/templates/core/wallet.html
> get bookmark promp fired on new wallet

- lnbits/extensions/usermanager/templates/usermanager/index.html
- lnbits/extensions/usermanager/views_api.py
Fix to prevent security issues when using the extension! This fix will probably break some implementations already using usermanager. 
Listing or deleting users and wallets now requires the admin key!
> protect listing and deleteing user and wallets

- lnbits/extensions/withdraw/lnurl.py
Urgent fix for unique LNURLw, as they were being consumed linearly, rather than individually
> Fixed unique LNURLw bug

- lnbits/core/services.py
- lnbits/core/views/api.py
Reverts lnbits/lnbits-legend#619
Sadly had unforeseen consequences for extensions, that need to be fixed first
> Revert "Check invoice status outgoing"

- docs/guide/installation.md
> Docs: Fix comments in service daemon script

- docs/guide/installation.md
lnbits needs to run on postgres once before `python3 conv.py` actually works
> Adjusted sequencing of the migration script

- lnbits/wallets/spark.py
Working on c-lightning 0.11.0.1
Fixing the issue #640
> Added maxfee parameter to Spark pay method 

- lnbits/app.py
Forgot about the basic_error response 
Please check if line `189` is correct on the error information!
> Hotfix for JSON response

- lnbits/core/views/api.py
> hotfix api_payments failing

- .gitignore
Ignore docker directory if you clone and use the https://github.com/lnbits/legend-regtest-enviroment
> Ignore docker directory

- Makefile
- lnbits/extensions/tpos/__init__.py
- lnbits/extensions/tpos/crud.py
- lnbits/extensions/tpos/migrations.py
- lnbits/extensions/tpos/tasks.py
- lnbits/extensions/tpos/views.py
- lnbits/extensions/tpos/views_api.py
* `make format` only uses `black`
* `black` on the whole thing
> Makefile: remove prettier

- lnbits/extensions/withdraw/views_api.py
> fix issue #683

- lnbits/extensions/lnurlp/views_api.py
> return lnurl in create link

- lnbits/core/services.py
- lnbits/core/views/api.py
- lnbits/utils/exchange_rates.py
`logger.warn` -> `logger.warning`
> Fix loguru warnings

- lnbits/extensions/jukebox/templates/jukebox/index.html
Tweaks to the UI of the jukebox extension to make user easier to follow.
> Jukebox improvements

- lnbits/extensions/withdraw/static/js/index.js
- lnbits/extensions/withdraw/templates/withdraw/display.html
Add `lnurlw://` prefix and fix the language code.
> LNURLw: NFC fix uri prefix

- lnbits/extensions/lnurlp/static/js/index.js
- lnbits/extensions/withdraw/static/js/index.js
> LNURLp: NFC UI improvement

- lnbits/core/static/js/extensions.js
- lnbits/core/templates/core/extensions.html
- lnbits/static/js/base.js
- lnbits/templates/base.html
Improvements to the UI of the extensions list
--
+ Extensions are sorted alphabetically
+ Added a search input field
> Extension list UI improvements

- .github/workflows/regtest.yml
changes in .github/workflows/regtest.yml in preparation of this PR https://github.com/lnbits/legend-regtest-enviroment/pull/3
includes:
* tests
* fixed clightning nodes
* fewer commands for workflows
> preparation pr for regtest update

- .gitignore
- Makefile
quality of dev life improvement after running tests
* git ignore coverage.xml 
* do not delete mock_data.zip
> .gitignore coverage.xml + do not delete mock_data.zip

- lnbits/core/views/api.py
Error checks for making LNURLp.
Todo:
> LNURLp: check description hash

- lnbits/core/views/api.py
Reverts lnbits/lnbits-legend#758
> Revert "LNURLp: check description hash"

- lnbits/core/views/api.py
Reverts lnbits/lnbits-legend#781
> Revert "Revert "LNURLp: check description hash""

- lnbits/extensions/events/crud.py
- lnbits/extensions/events/templates/events/display.html
- lnbits/extensions/events/templates/events/register.html
- lnbits/extensions/events/templates/events/ticket.html
- lnbits/extensions/events/views_api.py
Fixed issue scanning tickets by adding "ticket://" prefix
> Made ticket scanning reliable

- docs/guide/installation.md
> Update build instructions

- .github/workflows/migrations.yml
- .github/workflows/regtest.yml
- .github/workflows/tests.yml
- Dockerfile
- docs/guide/installation.md
Origin copy of PR #810 by @cryptoteun.
> Fix docker staticfiles

- .env.example
- lnbits/wallets/__init__.py
- lnbits/wallets/cliche.py
- poetry.lock
- pyproject.toml
- requirements.txt
Adds the wonderful lite-node Cliche as a funding source,
https://github.com/fiatjaf/cliche
> Adds Cliche as a funding source

- lnbits/extensions/satsdice/templates/satsdice/index.html
The reset data for the form was setting everything to null, instead of the set of default data from the initial rendering!
> properly reset data

- lnbits/extensions/lnticket/templates/lnticket/index.html
Reset form when closing the dialog!
> reset the form after close

- lnbits/core/views/api.py
- lnbits/extensions/lnurlp/views_api.py
Small fix for cleaning a check.
> Code health: Small linting fix

- docs/devs/extensions.md
Documentation for extension data migrations.
> Docs: migration for extensions

- .dockerignore
- Dockerfile
- docs/guide/installation.md
test it with
```
git clone https://github.com/lnbits/lnbits-legend.git
cd lnbits-legend
docker build -t lnbits-legend .
cp .env.example .env
mkdir data
docker run --detach --publish 5000:5000 --name lnbits-legend --volume ${PWD}/.env:/app/.env --volume ${PWD}/data/:/app/data lnbits-legend
```
> create new Dockerfile using poetry

- docs/guide/installation.md
adds openssl method for creating cert files
> Docs: ssl cert creation method using openssl

- lnbits/extensions/watchonly/static/components/address-list/address-list.html
- lnbits/extensions/watchonly/static/components/address-list/address-list.js
- lnbits/extensions/watchonly/static/components/serial-signer/serial-signer.js
- lnbits/extensions/watchonly/static/components/wallet-config/wallet-config.html
- lnbits/extensions/watchonly/static/components/wallet-list/wallet-list.html
- lnbits/extensions/watchonly/templates/watchonly/index.html
> onchain extension - review & fix

- docs/guide/installation.md
added apache2 reverse proxy setup to docs
> add apache2 reverse proxy documentation

- lnbits/decorators.py
- tests/core/views/test_api.py
testcase to trigger this error as mentioned here
https://github.com/lnbits/lnbits-legend/issues/847
> added test for issue #847 and fixed it!

- lnbits/extensions/lnurlp/views_api.py
- lnbits/extensions/withdraw/views_api.py
This PR resolves the issue reported in #872 and #815, error deleting lnurlp/lnurlw links.
> resolves issue #872 & #815, error deleting lnurlp/lnurlw links

- lnbits/extensions/invoices/static/css/pay.css
- lnbits/extensions/invoices/templates/invoices/pay.html
This PR fixes the mobile styling issues identified by @callebtc in https://github.com/lnbits/lnbits-legend/pull/733#issuecomment-1214217856
> clean up mobile layout per @callebtc

- lnbits/decorators.py
- tests/core/views/test_api.py
another similar test that fails just like in issue: #847
including fix.
i also decided on using 400 BAD REQUEST, instead of 401 UNAUTHORIZED. just because in get_key_type this is also used.
> another testcase the fails similar to #847

- lnbits/core/static/js/wallet.js
> add pending column to CSV export on wallet page, issue #887

- Makefile
this pr adds more verbose logging to tests
> add debug env variable to test commands

- lnbits/extensions/lnaddress/templates/lnaddress/_api_docs.html
Fixes: https://github.com/lnbits/lnbits-legend/issues/900
> lnAdress fix link to docs, fixes #900

- lnbits/extensions/subdomains/templates/subdomains/_api_docs.html
fix subdomain link to docs: also mentioned in #900
> subdomains docs fix: #900

- lnbits/extensions/lnurlp/templates/lnurlp/index.html
- lnbits/extensions/satsdice/templates/satsdice/index.html
- lnbits/extensions/withdraw/templates/withdraw/index.html
> Frontend: LNURLp/w icons with tooltips

- lnbits/extensions/tpos/templates/tpos/tpos.html
> add copy invoice button

- lnbits/core/static/js/wallet.js
- lnbits/core/templates/core/wallet.html
> Set focus on amount for create invoice

- lnbits/core/views/api.py
> fix typo in view api.py

- lnbits/extensions/boltz/config.json
And we dont put urls in descriptions
> Ruined extension layout

- lnbits/extensions/boltcards/crud.py
- lnbits/extensions/boltcards/lnurl.py
- lnbits/tasks.py
Significant startup speed improvement by reusing the db connection for the startup tasks.
> reuse db connection for pending and expired tasks

- lnbits/core/crud.py
- lnbits/tasks.py
Minor improvements for the task logger.
> print time of expiration

- lnbits/core/crud.py
Logs the number of rows to check for expiry.
> expiry task: more logging

- lnbits/core/views/api.py
- lnbits/decorators.py
Reverts lnbits/lnbits-legend#961
> Revert "API key check: assert that wallet exists"

- lnbits/core/views/api.py
- lnbits/decorators.py
Reverts lnbits/lnbits-legend#962
> Revert "Revert "API key check: assert that wallet exists""

- lnbits/extensions/watchonly/templates/watchonly/_api_docs.html
Link points here: https://lnbits.github.io/hardware-wallet
> feat: add link for `hardware-wallet` browser flash

- .github/workflows/regtest.yml
- change python version of lnd wallet to python 3.9
> change regtest lndwallet  to python3.8

- lnbits/core/static/js/wallet.js
this fixes issue https://github.com/lnbits/lnbits/issues/977
> fixes issue #977

- pyproject.toml
- fix scss error on poetry install
> fix scss module error

- lnbits/core/crud.py
- lnbits/core/views/api.py
Just a feature that helps a LNbits operator to keep track of the total balance of his public instance.
> API auditor

- .github/workflows/regtest.yml
- docs/guide/wallets.md
- poetry.lock
- pyproject.toml
this PR adds dependencies for corelightning and lndgrpc.
this also makes this PR https://github.com/lnbits/lnbits/pull/978 obsolete
> add dependencies for corelightning and lndgrpc

- lnbits/extensions/watchonly/models.py
- lnbits/extensions/watchonly/static/components/payment/payment.html
- lnbits/extensions/watchonly/static/components/payment/payment.js
- lnbits/extensions/watchonly/static/components/serial-signer/serial-signer.html
- lnbits/extensions/watchonly/static/components/serial-signer/serial-signer.js
- lnbits/extensions/watchonly/templates/watchonly/_api_docs.html
- lnbits/extensions/watchonly/templates/watchonly/index.html
- lnbits/extensions/watchonly/views_api.py
On some OSs the USB connect failed.
Added extra checks.
> Fix USB connect

- lnbits/wallets/void.py
add warning for voidwallet for better coloring in logs.
> add warning for voidwallet for better coloring in logs

- .github/workflows/codeql.yml
- .github/workflows/formatting.yml
- .github/workflows/mypy.yml
- .github/workflows/regtest.yml
- .github/workflows/tests.yml
> Revert "make gh workflows only run on pull_request"

- lnbits/extensions/lnurldevice/__init__.py
- lnbits/extensions/lnurldevice/crud.py
- lnbits/extensions/lnurldevice/lnurl.py
- lnbits/extensions/lnurldevice/migrations.py
- lnbits/extensions/lnurldevice/models.py
- lnbits/extensions/lnurldevice/tasks.py
- lnbits/extensions/lnurldevice/templates/lnurldevice/_api_docs.html
- lnbits/extensions/lnurldevice/templates/lnurldevice/index.html
- lnbits/extensions/lnurldevice/views.py
- lnbits/extensions/lnurldevice/views_api.py
Websocket support for instant slaps and beer taps
> Adds bitcoinSwitch support to LNURLDevices

- lnbits/extensions/boltz/tasks.py
> boltz logs from warn to debug

- lnbits/extensions/watchonly/crud.py
- lnbits/extensions/watchonly/models.py
- lnbits/extensions/watchonly/views_api.py
> fix: remove user from model

- lnbits/extensions/livestream/tasks.py
- lnbits/extensions/splitpayments/models.py
- lnbits/extensions/splitpayments/tasks.py
- lnbits/extensions/tpos/tasks.py
now the splitpayments extension creates internal invoices and pays them instead of creating and updating payments directly.
all transaction are now shown properly in wallet, i also added a more descriptive memo.
> Improvement to payment handling in splitpayments extension

- lnbits/extensions/copilot/crud.py
- lnbits/extensions/copilot/tasks.py
- lnbits/extensions/copilot/views.py
- lnbits/extensions/copilot/views_api.py
- lnbits/extensions/discordbot/crud.py
- lnbits/extensions/discordbot/views.py
- lnbits/extensions/discordbot/views_api.py
- lnbits/extensions/example/views.py
- lnbits/extensions/subdomains/crud.py
- lnbits/extensions/subdomains/models.py
- lnbits/extensions/subdomains/tasks.py
- lnbits/extensions/subdomains/views.py
- lnbits/extensions/subdomains/views_api.py
- pyproject.toml
- explicitly exclude all extensions from mypy
- fix example extension mypy
- fix subdomains extension mypy + 1 type error fixed
- fix mypy discordbot
- fix mypy copilot
> fix mypy for extensions

- lnbits/extensions/usermanager/templates/usermanager/_api_docs.html
- update incorrect response status codes
- update invalid activate extension example
> Fix usermanager extension API docs

- .env.example
add `FORWARDED_ALLOW_IPS` variable to .example.env
> add FORWARDED_ALLOW_IPS variable to .example.env

- lnbits/extensions/lnurldevice/templates/lnurldevice/index.html
- lnbits/extensions/usermanager/templates/usermanager/_api_docs.html
prettier html formatting issues
> prettier html formatting issues

- lnbits/extensions/usermanager/crud.py
- lnbits/extensions/usermanager/templates/usermanager/_api_docs.html
- lnbits/extensions/usermanager/views_api.py
Fixed API keys on example curl in UI!
Added hability for user to keep wallet after user deleted from extension, only through API.
Fixes #344 
Fixes #1113 
Fixes #871
> Fix usermanager API keys

- lnbits/extensions/events/__init__.py
- lnbits/extensions/events/tasks.py
- lnbits/extensions/events/templates/events/display.html
- lnbits/extensions/events/views_api.py
> chore: code format

- lnbits/extensions/watchonly/static/components/fee-rate/fee-rate.html
https://mempool.space/testnet/address/tb1q7dwpahq08pqwzra6gmm20dgkv0mw2f26usvzzr
> feat: allow decimal fee rate

- lnbits/extensions/bleskomat/views_api.py
- lnbits/extensions/boltcards/views_api.py
- lnbits/extensions/discordbot/views_api.py
- lnbits/extensions/events/views_api.py
- lnbits/extensions/livestream/views_api.py
- lnbits/extensions/lnaddress/views_api.py
- lnbits/extensions/lnticket/views_api.py
- lnbits/extensions/lnurlpayout/views_api.py
- lnbits/extensions/offlineshop/views_api.py
- lnbits/extensions/paywall/views_api.py
- lnbits/extensions/satspay/views_api.py
- lnbits/extensions/scrub/views_api.py
- lnbits/extensions/streamalerts/views_api.py
- lnbits/extensions/subdomains/views_api.py
- lnbits/extensions/tpos/views_api.py
Fix raising an error for delete, or update, when we should have a return
Fixes #1101
> fix raise error on delete request

- lnbits/extensions/withdraw/static/js/index.js
> fix issue with export to CSV

- lnbits/core/crud.py
- lnbits/extensions/tpos/crud.py
- lnbits/extensions/tpos/templates/tpos/tpos.html
- lnbits/extensions/tpos/views_api.py
See a list of last TPOS transactions!
> Add the ability to check for last (5) transactions

- lnbits/extensions/tpos/templates/tpos/tpos.html
Hopefully it fixes some weird behavior on the amount displayed, specially on amounts bellow 100 sats
> Small fix for TPoS amount display

- lnbits/extensions/offlineshop/README.md
- lnbits/extensions/satspay/README.md
- lnbits/extensions/tpos/README.md
Costumer to Customer, costumer to customer
> Fix typo's

- lnbits/extensions/withdraw/lnurl.py
better errorhandling for withdraw callback endpoint
also added some metadata for api docs
> better errorhandling for withdraw callback endpoint

- lnbits/extensions/jukebox/crud.py
- lnbits/extensions/jukebox/models.py
- lnbits/extensions/jukebox/tasks.py
- lnbits/extensions/jukebox/views.py
- lnbits/extensions/jukebox/views_api.py
- lnbits/extensions/ngrok/views.py
- lnbits/extensions/satsdice/crud.py
- lnbits/extensions/satsdice/lnurl.py
- lnbits/extensions/satsdice/models.py
- lnbits/extensions/satsdice/views.py
- lnbits/extensions/satsdice/views_api.py
- pyproject.toml
> more mypy extension fixes

- tests/conftest.py
test wallet actually had to few funds for paying the invoice in tests/extensions/invoices/test_invoices_api.py
> fix failing tests because it to low balance in wallet

- lnbits/extensions/events/templates/events/index.html
> Rename "Price per Ticket" to "Sats per Ticket"

- .env.example
> User ID comment in `.env.example`

- lnbits/core/views/api.py
> Send BAD REQUEST response

- requirements.txt
> Revert "update requirements"

- requirements.txt
> Revert "Revert "update requirements""

- lnbits/extensions/watchonly/models.py
- lnbits/extensions/watchonly/static/components/payment/payment.js
- lnbits/extensions/watchonly/static/js/index.js
- lnbits/extensions/watchonly/templates/watchonly/index.html
- lnbits/extensions/watchonly/views_api.py
> Watchonly wallet: allow broadcast of already signed transation

- lnbits/extensions/tpos/tasks.py
Receives all payments to a pos
> Adds PoS websocket endpoint

- lnbits/extensions/lndhub/views_api.py
Fixes #1182, previously fixed in #368.
> Fix: LNDhub alias

- lnbits/db.py
- lnbits/extensions/cashu/templates/cashu/wallet.html
- lnbits/extensions/cashu/views.py
Shows the mint name (and fixes a timestamp problem in db.py that I would've fixed in #1033)
> Cashu wallet: display mint name

- lnbits/extensions/cashu/templates/cashu/wallet.html
Fixes https://github.com/cashubtc/cashu/issues/64
> Cashu: add copy token button

- lnbits/core/views/api.py
- lnbits/wallets/lnbits.py
SSE only works without compression.
> LnbitsWallet invoice listener fix: disable compression

- lnbits/core/views/admin_api.py
forgot to commit last changes to admin_ui PR, @arcbtc 
this is so only super_user can brrr. like we talked about.
> only let super_user brrrr sats

- docs/guide/admin_ui.md
> Add documentation for Admin UI

- docs/_config.yml
change documentation theme to darkmode
> change documentation theme to darkmode

- docs/guide/admin_ui.md
Docs: admin_ui change backend to frontend
> Docs: admin_ui change backend to frontend

- .github/workflows/tests.yml
remove unused env from gh workflow tests
> remove unused env from gh workflow tests

- Dockerfile
Updates python in docker image to 3.10
> docker: update to python 3.10

- lnbits/extensions/usermanager/crud.py
- lnbits/extensions/usermanager/models.py
- lnbits/extensions/usermanager/views.py
- lnbits/extensions/usermanager/views_api.py
- pyproject.toml
fixing mypy errors for usermanager and remove it from pyproject exclude list.
renamed models of usermanager:
Wallets -> Wallet
Users -> User
> FIX: mypy issues with usermanager extension

- lnbits/extensions/cashu/views_api.py
Adds more logging for cashu debugging
> cashu: add more logging

- lnbits/extensions/cashu/views_api.py
> fix logger

- lnbits/core/views/generic.py
- lnbits/decorators.py
this should fix the issue a @AxelHamburch had in telegram:
"""
Somehow I seem to have locked out my super user account. I had set LNBITS_ALLOWED_USERS and probably forgot to specify the super user. Now I can't get in anymore. Also a LNBITS_ADMIN_UI=false, reboot and again to "true" brings the same super user which does not work.
Can I do a "reset to defaults" from outside the UI?
"""
lnbits/core/views/generic.py not excluding admin users and superuser for allowed_users check
> BUG: fix auth issue for superusers  when allowed users are set

- lnbits/core/views/api.py
`GET /api/v1/health` returns `200`.
> feat: api health check endpoint

- lnbits/core/views/api.py
- lnbits/decorators.py
- lnbits/extensions/satspay/views_api.py
get rid of unused code. uses `require_admin_key`.
> fix: remove require_admin_user

- result
this shouldn't have been commited since it it listed in gitignore)
> remove result link

- lnbits/extensions/lnurlp/crud.py
- lnbits/extensions/lnurlp/migrations.py
- lnbits/extensions/lnurlp/models.py
> add UUID as id instead of sequential integer

- lnbits/extensions/gerty/helpers.py
- lnbits/extensions/satspay/crud.py
> remove duplicit functions 

- pyproject.toml
Duplicate of #1257 but rebased to main
> remove hivemind and lnurlpayout from mypy ignore list

- lnbits/extensions/boltcards/views_api.py
- lnbits/extensions/invoices/views.py
- lnbits/extensions/nostrnip5/views.py
- lnbits/extensions/satspay/views_api.py
- lnbits/extensions/watchonly/views_api.py
- lnbits/extensions/withdraw/views.py
so mypy is not confused
most of these were typos (copy-pasta) errors anyway
> let's use unique function names

- Makefile
> add -o to find opts meaning or (default is and)

- lnbits/core/views/admin_api.py
- lnbits/core/views/api.py
- lnbits/core/views/generic.py
- lnbits/decorators.py
- lnbits/extensions/cashu/views.py
- lnbits/extensions/cashu/views_api.py
- lnbits/extensions/copilot/views.py
- lnbits/extensions/copilot/views_api.py
- lnbits/extensions/discordbot/views.py
- lnbits/extensions/discordbot/views_api.py
- lnbits/extensions/example/views.py
- lnbits/extensions/jukebox/views.py
- lnbits/extensions/jukebox/views_api.py
- lnbits/extensions/livestream/models.py
- lnbits/extensions/ngrok/views.py
- lnbits/extensions/satsdice/views.py
- lnbits/extensions/satsdice/views_api.py
- lnbits/extensions/satspay/views_api.py
- lnbits/extensions/subdomains/models.py
- lnbits/extensions/subdomains/views.py
- lnbits/extensions/subdomains/views_api.py
- lnbits/extensions/usermanager/views.py
- lnbits/extensions/usermanager/views_api.py
removing type: ignore from Query, Depends, Body and import them correctly
> removing type: ignore from Query, Depends, Body and import them correctly

- .env.example
- lnbits/core/templates/core/wallet.html
- lnbits/core/views/generic.py
- Top up button only visible for `super_user`
- Better input for amount
- Mask of top up amount now denomination-aware
> Fix super_user check, fixes #1250

- lnbits/extensions/gerty/helpers.py
- lnbits/extensions/satspay/crud.py
> Revert "Revert "remove duplicit functions ""

- lnbits/extensions/withdraw/crud.py
- lnbits/extensions/withdraw/lnurl.py
- lnbits/extensions/withdraw/models.py
- lnbits/extensions/withdraw/views.py
- lnbits/extensions/withdraw/views_api.py
- pyproject.toml
fix mypy issue on withdraw + some refactoring
> fix mypy issue on withdraw + some refactoring

- lnbits/extensions/lnurlp/crud.py
- lnbits/extensions/lnurlp/migrations.py
- lnbits/extensions/lnurlp/models.py
- lnbits/extensions/withdraw/crud.py
> Revert "Revert "add UUID as id instead of sequential integer""

- lnbits/core/models.py
- lnbits/extensions/cashu/tasks.py
- lnbits/extensions/copilot/tasks.py
- lnbits/extensions/invoices/tasks.py
- lnbits/extensions/jukebox/tasks.py
- lnbits/extensions/lnticket/tasks.py
- lnbits/extensions/lnurlp/tasks.py
- lnbits/extensions/market/tasks.py
- lnbits/extensions/nostrnip5/tasks.py
- lnbits/extensions/scrub/tasks.py
- lnbits/extensions/splitpayments/tasks.py
- lnbits/extensions/subdomains/tasks.py
- lnbits/extensions/tpos/tasks.py
this makes handling in tasks.py so much easier
> make payment.extra non-optional

- lnbits/extensions/boltcards/tasks.py
- lnbits/extensions/satspay/tasks.py
Remove last remaining checks (as in #1280)
> refactor: remove remaining checks, as in #1280

- lnbits/extensions/boltcards/tasks.py
one extraneous check was forgotten
> followup to #1300

- lnbits/extensions/lnurlp/migrations.py
This commit breaks when migrating data https://github.com/lnbits/lnbits/pull/1298
> LNURLp fix

- lnbits/extensions/lnurlp/migrations.py
> Revert "LNURLp fix"

- lnbits/extensions/lnurlp/lnurl.py
- lnbits/extensions/lnurlp/static/js/index.js
- lnbits/extensions/lnurlp/views.py
> Revert "shorten lnurlp endpoint URL for smaller QR codes"

- lnbits/extensions/lnurlp/lnurl.py
- lnbits/extensions/lnurlp/static/js/index.js
- lnbits/extensions/lnurlp/views.py
> Revert "Revert "shorten lnurlp endpoint URL for smaller QR codes""

- lnbits/extensions/boltcards/crud.py
- lnbits/extensions/boltcards/views_api.py
- fix loading of refund records
- getting rid of unnecessary Unions
> Fix: Boltcard refunds

- lnbits/wallets/spark.py
>  Fixing spark string subtraction

- lnbits/extensions/tpos/tasks.py
followup to fca7e7bec3a40de8a5f7f65ac6030513c02e8db7
> tpos: remove extraneous not payment.extra check

- lnbits/extensions/tipjar/crud.py
- regression bug
**Steps**:
- create a `tipjar` using the API
```
curl --location --request POST 'https://127.0.0.1:5000/tipjar/api/v1/tipjars' \
--header 'Content-Type: application/json' \
--data-raw '{"wallet":"af3fee38943646dd84d57fef618322cd","name":"Nakamoto","webhook":"http://localhost:8081"}'
```
- the returned value always has `1` for ID
```
{
"id": 1,
"name": "Nakamoto",
"wallet": "af3fee38943646dd84d57fef618322cd",
"onchain": null,
"webhook": "http://localhost:8081"
}
```
**Expected Result**:
- the correctly incremented ID is returned
```
{
"id": 300,
"name": "Nakamoto",
"wallet": "af3fee38943646dd84d57fef618322cd",
"onchain": null,
"webhook": "http://localhost:8081"
}
```
> fix: (rollback refactoring) Use the `tipjar` id to fetch the created `tipjar`

- lnbits/extensions/smtp/templates/smtp/display.html
- pyproject.toml
remove livestream from mypy ignore and remove dead code from smtp
> BUG: remove livestream from mypy ignore and remove dead code from smtp

- lnbits/extensions/nostrnip5/crud.py
- lnbits/extensions/nostrnip5/models.py
- lnbits/extensions/nostrnip5/templates/nostrnip5/index.html
- lnbits/extensions/nostrnip5/views_api.py
Allow editing the price of a NIP-5 domain
> Enabled Editing the Price for NIP-5 Domains

- pyproject.toml
add additional metadata to pyproject, description, version, authors
> FEAT: add additional metadata to pyproject, description, version, authors

- lnbits/extensions/smtp/migrations.py
Bug: SMTP extension migrationfails
> Bug: SMTP extension migrationfails

- .env.example
I mostly just brought the example env file up to date with the documentation located at: https://github.com/lnbits/lnbits/blob/main/docs/guide/wallets.md
> add example configuration for connecting LND over grpc

- docs/guide/faq.md
I uploaded this faq.md to see if I edited correctly. If is ok will continue with more items in it.
> add FAQ page

- lnbits/core/views/generic.py
> Feat: add robots.txt

- lnbits/extensions/boltz/README.md
- lnbits/extensions/boltz/crud.py
- lnbits/extensions/boltz/templates/boltz/_api_docs.html
added another card element in UI to explain the boltz fees in detail, with examples.
@michael1011 please approve :)
> DOCS: improve boltz fee information

- Makefile
- lnbits/extensions/copilot/templates/copilot/compose.html
- lnbits/extensions/gerty/templates/gerty/gerty.html
- lnbits/extensions/gerty/templates/gerty/index.html
- lnbits/extensions/jukebox/static/js/index.js
- lnbits/extensions/lnurldevice/templates/lnurldevice/index.html
- lnbits/extensions/market/templates/market/index.html
- lnbits/extensions/satspay/templates/satspay/index.html
- lnbits/extensions/smtp/templates/smtp/index.html
- lnbits/extensions/subdomains/templates/subdomains/index.html
- lnbits/extensions/watchonly/static/components/wallet-list/wallet-list.js
- package-lock.json
- package.json
- pyproject.toml
- this PR adds pyright to the project (via package.json and also adds a Makefile entry)
- this PR also bumps prettier to latest and reformats html files to match the new rules (the new format is much more readable)
- this PR does not fix all pyright issues - this will came later and already has been started in https://github.com/lnbits/lnbits/pull/1356
> add pyright to the project

- lnbits/core/services.py
Rather than have `https://127` the link should be `http://127`
> Changes https for http in super user link

- .github/workflows/codeql.yml
- .github/workflows/formatting.yml
- .github/workflows/migrations.yml
- .github/workflows/mypy.yml
- .github/workflows/on-tag.yml
- .github/workflows/regtest.yml
- .github/workflows/tests.yml
* update versions for @actions/setup-python and @actions/checkout to latest.
* add caching for poetry
* create venv again for poetry install, unstable tests runs
> TEST: update actions setup-python to v4 and checkout to v3, add caching to python

- tests/conftest.py
- tests/core/views/test_api.py
- tests/helpers.py
pay and check external invoice
> TEST: add helpers and a test to pay external invoice

- lnbits/extensions/cashu/templates/cashu/wallet.html
Fixes JS fronted bug during spendable check.
> Cashu fix: token spendable check

- .env.example
- lnbits/core/templates/admin/index.html
- lnbits/settings.py
- lnbits/static/scss/base.scss
- lnbits/templates/base.html
Because we all liked the theme from this pr https://github.com/lnbits/lnbits/pull/622
> Added cyber theme

- lnbits/core/static/js/wallet.js
fixes this issue: https://github.com/lnbits/lnbits/issues/1506
> BUGFIX: topup #1506

- Makefile
we moved out the extension tests
> remove unused variable for test in makefile

- lnbits/core/crud.py
- lnbits/core/models.py
- lnbits/db.py
- lnbits/decorators.py
Enhancing https://github.com/lnbits/lnbits/pull/1557 with limit and offset functionality and small improvements to filter class
> add limit and offset to filters

- .gitignore
- lnbits/core/templates/admin/index.html
- lnbits/core/views/admin_api.py
add download backup route to api and adminUI.
> FEAT: add db export admin route for pg and sqlite, add to adminui

- Dockerfile
* remove build.py -> not needed
* create the right datadir
* add postgres-client for pg_dump backup functionality
> BUG: Dockerfile does not support backup funcionality

- pyproject.toml
fixes flake install issue thanks to https://github.com/lnbits/lnbits/issues/1088
> fix flake error: #1088

- docs/guide/installation.md
- docs: add nginx ssl proxy info to installation
- docs: fix readability of HTTPS section in installation
> docs: add nginx ssl proxy info to installation

- lnbits/app.py
- lnbits/settings.py
make versions more visible on multiple places.
> add version to fastapi app and startup log

- lnbits/static/js/components.js
implement this feature https://github.com/lnbits/lnbits/issues/1552
> FEAT: #1552 add copy payment_hash to payment details

- lnbits/wallets/fake.py
fix bug introduced here: https://github.com/lnbits/lnbits/pull/1468
> hotfix fakewallet

- poetry.lock
- pyproject.toml
- remove python3.7
- update lock file
- change to new dev-dependencies format
- update dev-dependencies
> FEAT: remove python 3.7 and update dependencies

- lnbits/wallets/lndrest.py
related to https://github.com/lnbits/lnbits/issues/1635
> BUG: SSL certificate for lndrest is required even though it could be a publicly issued one

- .github/workflows/formatting.yml
i think this is wrong it should just run on all push or pull_requests
> formatting did only run on branch main?

- lnbits/core/templates/admin/index.html
Fix inputs on LNDWallet and LNDRestWallet on Admin UI
> fix inputs on Lnd funding sources

- pyproject.toml
merge this pr before new version release
> Bump version to 0.10.5

- .gitignore
- lnbits/core/services.py
this is very useful for lnbits bundlers, to have easy access to the super_user url to show it to their users
> generate .super_user file on startup if adminui is enabled

- lnbits/helpers.py
- lnbits/settings.py
turning on DEBUG logs should not have any effect the asset bundling on the frontend.
You may want to turn on debug logging on your server, without the frontend beeing effected.
> FEAT: introduce bundle_assets variable and decouple it from DEBUG

- lnbits/core/views/generic.py
just a little cleanup removing some type ignores, and asserting where it is appropriate.
> removing type ignores from views/generic.py

- lnbits/extension_manager.py
- lnbits/server.py
create data dir on `poetry run lnbits` if it does not exist.
> create datadir on launch

- lnbits/core/crud.py
- lnbits/core/templates/admin/index.html
- lnbits/settings.py
Side effect of: PR https://github.com/lnbits/lnbits/pull/1663
**Steps**:
- Login with super admin
- Go to Manage Server
- Save
- Reload page
**Actual Result**
- User no longer has admin rights
**Expected Result**
- User permissions should not change
This issue does not reproduce for regular admins, only for super user. 
**Screen recording**:
https://user-images.githubusercontent.com/2951406/236933459-430cc0cd-1ad2-4d7b-91c4-5467bf2c225b.mov
> fix: rename bool `super_user` to `is_super_user`

- lnbits/templates/base.html
Super User
Admin User
Regular User
Closes #1708
> Add user role

- lnbits/core/services.py
> FIX: internal qrcode scanning check should always check for lowercase

- lnbits/db.py
Adds support for specifying sortable fields in a `FilterModel` and validates them accordingly
> feat: specify sort fields

- lnbits/static/i18n/de.js
This replaces some usages of "Sie" with "du", and also fixes a few minor mistakes.
> Minor improvements to the German translation

- lnbits/app.py
- lnbits/core/views/api.py
- lnbits/extension_manager.py
Requested here: https://github.com/lnbits/lnbits/issues/1710#event-9260988101
> feat: print extensions version on install/uninstall/reinstall

- lnbits/core/services.py
- lnbits/settings.py
- remove settings logging (security)
related to https://github.com/lnbits/lnbits/pull/1749
> SECURITY: Remove settings logging

- lnbits/core/tasks.py
asdict worked before, now it doesn't so I switched to dict.
> Changes asdict to dict for payment websocket

- lnbits/core/crud.py
- lnbits/decorators.py
Check for super_user when calling `check_user` so the user label it's correct across all pages
> Fix user label across lnbits

- .pre-commit-config.yaml
add precommit checks only for types
> precommit only check prettier if html/css/js/json

- .pre-commit-config.yaml
- .prettierignore
- pyproject.toml
i ran into this issue with `pre-commit` linting this lnbits/upgrades/ directory
> ignore upgrades dir in linters and formatters and precommit

- lnbits/middleware.py
only call next after validation
> ip blocker only call next after validation

- lnbits/middleware.py
> Middleware: remove sleep in IP blocker

- lnbits/middleware.py
> Fix ip blocker 2nd try

- lnbits/core/templates/admin/index.html
needs restart after saving killswitch
> needs restart after saving killswitch

- .github/workflows/mypy.yml
- .github/workflows/regtest.yml
- .github/workflows/tests.yml
> quickfixs failing checks on main

- .github/workflows/openapi.yml
- Makefile
- lnbits/settings.py
- poetry.lock
- pyproject.toml
adds workflow that validates openapi.json
relating to issue: https://github.com/lnbits/lnbits/issues/1442
> add github workflow for checking openapi

- lnbits/app.py
> fix ugly printed error of uvicorn.error

- lnbits/core/views/api.py
> follow redirect for lnurls

- lnbits/wallets/void.py
before that change anyone using the api just got a 500 error without any error message. there was also a bug stacetrace in the logs each time.
> FEAT: proper failing invoice/payment responses for VoidWallet

- lnbits/db.py
- lnbits/helpers.py
Since https://github.com/lnbits/lnbits/pull/1697 is now closed, this feature has to be removed as it is not working on sqlite.
> remove nested filters

- Makefile
- docs/devs/development.md
- lnbits/server.py
Autoreload is a pretty handy feature when developing. I changed the server.py to include this functionality and added a `dev` script in the Makefile
> support uvicorn reload functionality

- .flake8
- lnbits/app.py
- lnbits/core/crud.py
- lnbits/core/helpers.py
- lnbits/core/migrations.py
- lnbits/core/models.py
- lnbits/core/services.py
- lnbits/core/views/admin_api.py
- lnbits/core/views/api.py
- lnbits/core/views/generic.py
- lnbits/core/views/public_api.py
- lnbits/decorators.py
- lnbits/helpers.py
- lnbits/settings.py
- lnbits/wallets/cliche.py
- lnbits/wallets/cln.py
- lnbits/wallets/eclair.py
- lnbits/wallets/lnbits.py
- lnbits/wallets/lndgrpc.py
- lnbits/wallets/lndrest.py
- lnbits/wallets/lnpay.py
- lnbits/wallets/lntips.py
- lnbits/wallets/macaroon/macaroon.py
- lnbits/wallets/spark.py
remove all bare exceptions from codebase and change it in `.flake8`
Bare except will catch exceptions you almost certainly don't want to catch, including KeyboardInterrupt (the user hitting Ctrl+C) and Python-raised errors like SystemExit
If you don't have a specific exception you're expecting, at least except Exception, which is the base type for all "Regular" exceptions.
https://stackoverflow.com/questions/54948548/what-is-wrong-with-using-a-bare-except
> [CHORE] E722 bare exception fix

- .flake8
- lnbits/core/__init__.py
- lnbits/core/views/api.py
- lnbits/db.py
- lnbits/server.py
- lnbits/settings.py
- lnbits/tasks.py
- lnbits/wallets/lndgrpc.py
- lnbits/wallets/lnpay.py
- lnbits/wallets/macaroon/macaroon.py
- lnbits/wallets/opennode.py
- poetry.lock
- tests/core/test_db.py
- tests/core/views/test_api.py
for more details look into commit messages.
could not fix all E402 issues, the last one needed following refactor.
https://github.com/lnbits/lnbits/pull/1876
E721 only popped up for python 3.9 not 3.10
> [CHORE] flake8 issues E402, E721 and F821

- lnbits/db.py
```warning: Class methods should take a "cls" parameter (reportSelfClsParameterName)```
> [CHORE] fix pyright warning in db.py

- pyproject.toml
now you can see which lnbits logs belongs to which tests! :)
> [TEST] improved logs for tests

- Makefile
- lnbits/app.py
- lnbits/server.py
- tests/conftest.py
cherry picked from https://github.com/lnbits/lnbits/pull/1793
> [TEST] proper startup and shutdown

- lnbits/core/models.py
- lnbits/core/services.py
- lnbits/core/views/api.py
- tests/conftest.py
- tests/core/views/test_api.py
pull out models
line lengths
bare excepts
> [REFACTOR] cleanup views/api.py

- lnbits/commands.py
- pyproject.toml
- add superuser command for print
- add delete-settings command
> [FEAT] add `lnbits-cli` for commands.py

- lnbits/app.py
- lnbits/core/__init__.py
- lnbits/core/models.py
- lnbits/core/views/admin_api.py
- lnbits/core/views/api.py
- lnbits/core/views/generic.py
- lnbits/settings.py
https://github.com/dni/lnbits-client-java
https://github.com/dni/lnbits-client-js
https://github.com/dni/lnbits-client-python
https://github.com/dni/lnbits-client-rust
> [CHORE] improve on fastapi / openapi docs

- lnbits/settings.py
fallback does not use try/except for list_fallback. i think its unnecessary.
else it triggers inside a debugger if you have break on exception active
> [REFACTOR] do not throw an exception in list_parse_fallback

- .github/workflows/regtest.yml
- .github/workflows/tests.yml
> [TEST] add codecov token to workflow

- .github/workflows/regtest.yml
- lnbits/wallets/corelightningrest.py
- tests/core/views/test_api.py
- tests/helpers.py
refactoring test/helpers to be able to timeout them.
adding a timeout before paid_invoice_listener
> [TEST] workflows, added 10s timeout to `lncli` subprocess and logging

- lnbits/wallets/lndgrpc.py
also removed dead code def get_ssl_context
> [REFACTOR] grpcio and protofbuf for lndgrpc is not optional

- lnbits/core/services.py
closes: https://github.com/lnbits/lnbits/issues/1931
> [FIX] correct amount in fiat tracking

- .env.example
- docs/guide/wallets.md
Document CoreLightningRestWallet in `.env.example` and in wallet docs
> [CORE] Document CoreLightningRestWallet

- lnbits/core/crud.py
- lnbits/core/models.py
- tests/core/views/test_api.py
make it possible to pay to yourself on fakewallet.
adds failing test
and a commit fixing it
> [BUG] self payments for the same wallet

- lnbits/core/templates/admin/_tab_funding.html
- lnbits/core/templates/admin/index.html
Makes the wallet names more readeable on Admin funding tab
Closes #1911
> make wallets name prettier!

- lnbits/core/crud.py
- lnbits/core/models.py
- lnbits/core/static/js/wallet.js
- lnbits/core/templates/core/wallet.html
- lnbits/core/views/api.py
- tests/conftest.py
- tests/core/views/test_api.py
Continuation of https://github.com/lnbits/lnbits/pull/1756.
> Fix payments chart

- lnbits/app.py
> Extension loader: do not panic!

- lnbits/core/crud.py
> Revert "do not show deleted wallets"

- lnbits/core/views/api.py
Addresses https://github.com/lnurl/luds/pull/234
> LNURL-pay: drop `description_hash` validation

- lnbits/core/static/js/node.js
node ranks werent showing correctly in frontend
> fix: node ranks

- lnbits/core/templates/admin/_tab_server.html
undefined formData.lnbits_allowed_currencies JS error in console
> fix: admin_ui js error

- poetry.lock
- pyproject.toml
for the time beeing its better to readd this package for backwards compatibility in LNURLp and cashu
> hotfix: add environs backwards compatibility

- lnbits/core/static/js/node.js
- lnbits/core/templates/node/index.html
- lnbits/core/templates/node/public.html
lnbits-date component was a duplication.
moved all to the Vue.components into node.js
empty {% raw %} tags in public
> [CHORE] cleanup nodemanagement vue components

- lnbits/templates/base.html
since noone bothers fixing the important things, i did it myself :)
> remove comma after version

- lnbits/core/static/js/wallet.js
> feat: wallet name in payments export

- lnbits/nodes/base.py
- lnbits/nodes/cln.py
not every payment has a bolt11 present
> fix: make bolt11 optional in `NodePayment`

- .env.example
- lnbits/app.py
- lnbits/server.py
- lnbits/settings.py
logs into `lnbits.log` with info loglevel and `debug.log` with DEBUG loglevel files will be saved into `LNBITS_DATA_DIR`.
retentions is configurable but defaults to `30 days`
> feat: add file logging

- .github/workflows/ci.yml
> feat: improve im workflows runs

- lnbits/nodes/base.py
this pr got wrongly merged into main
> fix: closed channels affecting the stats (#1998)

- docs/guide/installation.md
this pr got wrongly merged into main
> Update installation.md (#1997)

- lnbits/app.py
- lnbits/extension_manager.py
Issue describe very well here: https://github.com/lnbits/lnbits/issues/2043
> [BUG] Installation of new extensions via LNBITS_EXTENSIONS_DEFAULT_INSTALL does not select the right version

- docs/guide/installation.md
> Revert "Update installation.md"

- lnbits/commands.py
- lnbits/core/crud.py
- lnbits/core/models.py
`lnbits-cli extensions`
update, install, uninstall, list extensions from CLI
> [FEAT] add extension functionality to lnbits-cli

- lnbits/nodes/cln.py
Fixes https://github.com/lnbits/lnbits/issues/2055
Never coded python before, so I had to wing it, but at least it works.
> CLN: Handle optional invoice fields

- lnbits/app.py
this should be a success log, see screenshot.
> feat: logger success when wallet is connected

- lnbits/static/i18n/cn.js
- lnbits/static/i18n/de.js
- lnbits/static/i18n/en.js
- lnbits/static/i18n/es.js
Some i18n files contain empty lines, this PR removes them
> i18n: remove empty lines

- lnbits/nodes/base.py
fixes https://github.com/lnbits/lnbits/issues/2081
> handle correctly the case with no active channels

- lnbits/settings.py
from `settings.py`
needs to be merged into 0.11.2, i will release a compatible ext version with `min_lnbits_version 0.11.2`
> chore: remove boltz settings

- lnbits/wallets/lndrest.py
> Fixed payment isn't initiated on lndrest

- lnbits/wallets/corelightning.py
> CLN: return payment failure if no payment is found

- lnbits/core/services.py
Fee reserve was used for internal payments.
> Fix: fee reserve for internal

- lnbits/core/__init__.py
- lnbits/core/views/api.py
- lnbits/core/views/tinyurl_api.py
small little refactor getting to a cleaner `views/api.py`
> refactor: move tinyurl to its own router

- lnbits/core/templates/admin/_tab_security_notifications.html
- lnbits/core/templates/core/extensions.html
- lnbits/core/templates/core/index.html
- lnbits/templates/base.html
Fixes https://github.com/lnbits/lnbits/issues/2129 - add a target="_blank" to all logos on index
> use _blank + noopener + noreferrer consistently

- lnbits/core/templates/core/wallet.html
- lnbits/static/js/wallet.js
If lightning/lnurl param is present in /wallet, it will pass to the decode dialogue
> Handles intents

- Makefile
make check does not run checkbundle, this PR fixes that
> add checkbundle to make check

- .env.example
(copied from the https://github.com/lnbits/lnbits/releases/tag/0.11.2 release notes)
> add vars related to service fee to .env.example

- lnbits/core/templates/core/index.html
PR https://github.com/lnbits/lnbits/pull/2137 was partially reverted when merging PR https://github.com/lnbits/lnbits/pull/2092
This PR reintroduces the change
> use _blank for external links on main

- lnbits/app.py
- lnbits/core/templates/core/index.html
- lnbits/core/views/auth_api.py
> Login polish

- flake.nix
> Fix nixos module getExe warning about meta attribute in nix poetry build

- .github/workflows/release.yml
create a draft release on tagging
> feat: use github release draft

- docs/guide/installation.md
> chore: update readme to use new docker alias

- lnbits/tasks.py
this code is not used anywhere on core nor on extensions
> chore: dead code `perform_balance_check`

- .env.example
LNBITS_ADMIN_UI has become the most important variable, so should be at the top of the file
> Improved env layout

- lnbits/core/templates/admin/_tab_users.html
added to users tab of admin ui.
> feat: add setting `lnbits_allow_new_accounts` to admin ui

- lnbits/core/templates/core/index.html
My solution to #2253 bug.
Please feel free to suggest any better solution since I'm really not much experienced with this Quasar positioning and styling.
> fix: custom site desc

- .github/workflows/release.yml
actions/checkout was missing so it could not release
> fix: github release missing checkout

- pyproject.toml
> chore: update to 0.12.2

- lnbits/tasks.py
> chore: remove dead code send_push_promise

- lnbits/core/services.py
also values where checked twice
> fix: raise proper exception in services pay_invoice

- poetry.lock
- pyproject.toml
- tests/core/views/test_node_api.py
- tests/helpers.py
- tools/conv.py
- tools/i18n-ai-tool.py
> test: lint `tests` and `tools` aswell

- .pre-commit-config.yaml
wasnt working after latest ruff update
> fix: update pre-commit ruff

- lnbits/wallets/lnbits.py
- tests/core/views/test_api.py
fix a bug where payments are deleted
> fix: lnbits funding source

- lnbits/tasks.py
this is especially useful for extensions.
with this an extension can only call `create_permanent_unique_task("my-ext", task)` and it will restarted when it exists and cancels when lnbits is stopped
> feat: create_unique_task helper

- .env.example
- lnbits/app.py
- lnbits/db.py
- lnbits/settings.py
makes it visible what db actions happen
> feat: add database debug env var

- lnbits/core/templates/core/wallet.html
> bug: recover user for export-to-phone

- lnbits/core/templates/core/wallet.html
> hotfix: qrcode broke wallet.html

- lnbits/commands.py
Add a new command that checks:
- payments settled in the LNbits DB in the last `d` days (default 3 days)
- on the above payments check the ones still pending on the funding source
- list invalid the payments and the wallets 
The command (in this version) does not alter payments or wallets, it simply lists them.
**Example**:
```sh
% lnbits-cli db check-payments 
```
```sh
efceca8caf664ca4a97a69b0b1d97c495c2ed9837cb39bb69101ecccc7af13ba 341d16d1e17847d48948b3d0ea230e58 1024.0     UPDATED SITETITLE
dea48986bdbbf2725452ff4752f573490b20f73b7ca35b2caa6238504b875e2a 9a795179846f400388d2b4bd488430e5 1006.0     66666
7a14e26ee2f85ac27050732bd5a5f6c6b841acb5d76a703d0e82d6b1f906fe83 9a795179846f400388d2b4bd488430e5 1005.0     LNbits XXX
62d97c5c3911de69e4b2654a3b563065ee55d06289035d34631624c1f662f72a …
```
> feat: add `check_invalid_payments` command

- lnbits/commands.py
- lnbits/core/crud.py
add commands:
- `delete-wallet`
- `delete-wallet-payment`
add `-verbose` option for check invalid payments
> feat: add commands `delete-walle`, `delete-wallet-payment` and `verbose` option, 

- lnbits/commands.py
- add `mark-payment-pending` command
- add `--auto-fix` option to `check-payments` command
> feat: add `mark-payment-pending` command

- .github/workflows/ci.yml
- .github/workflows/jmeter.yml
also uses `prepare` action to initialize python env
> ci: run jmeter only if linting passes to save resources

- lnbits/templates/base.html
> bug: show extensions in frontend had wrong boolean

- lnbits/core/templates/admin/_tab_server.html
- lnbits/core/templates/admin/_tab_users.html
> bug: frontend some v-text missing 

- README.md
See here:
https://github.com/lnbits/lnbits/blob/somereadmetweaks/README.md
> docs: improves readme

- lnbits/app.py
- lnbits/core/views/extension_api.py
- lnbits/extension_manager.py
> chore: typo in function name `nofiy_upgrade`

- poetry.lock
- pyproject.toml
https://github.com/lnbits/lnbits/security/dependabot/52
> chore: update black, security warning

- poetry.lock
- pyproject.toml
https://github.com/lnbits/lnbits/security/dependabot/41
> chore: fix `pycryptodomex` security issue

- lnbits/core/views/extension_api.py
- lnbits/core/views/generic.py
- lnbits/core/views/payment_api.py
- lnbits/middleware.py
- lnbits/nodes/lndrest.py
- lnbits/server.py
- lnbits/wallets/fake.py
- lnbits/wallets/lndrest.py
- pyproject.toml
- tools/conv.py
note: max-complexity should be decreased to 10 in another PR.
> chore: adhere to ruff's `C`

- docs/guide/installation.md
> docs: improve installation for none ubuntu

- .github/workflows/ci.yml
- .github/workflows/jmeter.yml
- .github/workflows/migration.yml
- .github/workflows/regtest.yml
- .github/workflows/tests.yml
- flake.nix
- poetry.lock
- pyproject.toml
utilizing this action: https://github.com/pavelzw/pytest-action/
> test: make nice pytest reports on github

- .env.example
closes #2134
suggestion from issue
> doc: add hint to configure reverse proxy in `.env.template`

- lnbits/app.py
should fix SaaS crashing when retrying.
- remove the signal handler!
> fix: improve on check_fundingsource retries

- .pre-commit-config.yaml
- lnbits/static/js/components.js
- lnbits/templates/base.html
- lnbits/templates/print.html
- package-lock.json
- package.json
update to new prettier version with some new formatting
> chore: update prettier

- pyproject.toml
needed in preparation of https://github.com/lnbits/lnbits/pull/2377
> chore: prepare version update to `0.12.6`

- .github/workflows/ci.yml
- lnbits/app.py
- lnbits/core/models.py
- lnbits/core/services.py
- lnbits/core/tasks.py
- lnbits/core/views/auth_api.py
- lnbits/core/views/generic.py
- lnbits/core/views/node_api.py
- lnbits/core/views/payment_api.py
- lnbits/core/views/websocket_api.py
- lnbits/db.py
- lnbits/decorators.py
- lnbits/settings.py
- lnbits/tasks.py
- lnbits/wallets/__init__.py
- lnbits/wallets/base.py
- lnbits/wallets/corelightning.py
- lnbits/wallets/corelightningrest.py
- lnbits/wallets/eclair.py
- lnbits/wallets/lndrest.py
- lnbits/wallets/opennode.py
- lnbits/wallets/zbd.py
- pyproject.toml
- tests/conftest.py
- tests/core/views/test_api.py
- tests/core/views/test_node_api.py
- tests/helpers.py
- tools/conv.py
bunch of more consistent variable naming. inspired by this issue. https://github.com/lnbits/lnbits/issues/2308
WARNING this breaks some imports in extensions, UPDATE them to fix!
jmeter tests temporarly disabled https://github.com/lnbits/lnbits/issues/2410
> chore: adhere to ruff's "N" rules

- tests/wallets/test_rpc_wallets.py
> fix: ruff linting broke

- .github/workflows/make.yml
https://github.com/lnbits/example/pull/9/files#diff-107e910e9f2ebfb9a741fa10b2aa7100cc1fc4f5f3aca2dfe78b905cbd73c0d2R10
> feat: make workflow reuseable for external repo

- lnbits/app.py
- lnbits/commands.py
- lnbits/core/views/payment_api.py
- lnbits/core/views/public_api.py
- lnbits/extension_manager.py
- lnbits/middleware.py
- lnbits/nodes/lndrest.py
- lnbits/settings.py
- lnbits/tasks.py
- lnbits/utils/exchange_rates.py
- pyproject.toml
- tests/wallets/fixtures/models.py
- tests/wallets/helpers.py
> chore: adhere to ruff's `RUF` rules, 2nd try

- README.md
- lnbits/core/templates/core/index.html
Fixes broken ad layout on homepage
Added badges to readme
> Fixes ad issue on homepage + readme badges

- lnbits/tasks.py
and remove type from `Coroutine` from the create_tasks
> feat: `catch_everything_and_restart` print name of the task

- lnbits/app.py
- lnbits/core/helpers.py
- lnbits/core/services.py
- lnbits/core/views/admin_api.py
- lnbits/core/views/api.py
- lnbits/core/views/auth_api.py
- lnbits/core/views/extension_api.py
- lnbits/core/views/generic.py
- lnbits/core/views/node_api.py
- lnbits/core/views/payment_api.py
- lnbits/core/views/public_api.py
- lnbits/core/views/tinyurl_api.py
- lnbits/decorators.py
- lnbits/extension_manager.py
- lnbits/nodes/cln.py
- lnbits/nodes/lndrest.py
- lnbits/server.py
- lnbits/utils/crypto.py
- lnbits/wallets/base.py
- lnbits/wallets/cliche.py
- lnbits/wallets/corelightning.py
- lnbits/wallets/fake.py
- lnbits/wallets/lndgrpc.py
- lnbits/wallets/spark.py
- lnbits/wallets/void.py
- pyproject.toml
- tests/wallets/helpers.py
- tools/conv.py
last of the ruff checks.
closes #2308
> feat: adhere to ruff's `B` rules

- lnbits/core/crud.py
- lnbits/core/migrations.py
> fix: balances view on use non deleted wallets

- lnbits/server.py
got the idea from: https://github.com/lnbits/lnbits/issues/2447
arguments it should be explicity allowed with `click` and a description should be added like here:
```
(lnbits-py3.10) dni@arch:~/repos/lnbits/lnbits (dev) $ lnbits --help
130
Usage: lnbits [OPTIONS]
Launched with `poetry run lnbits` at root level
Options:
--port INTEGER              Port to listen on
--host TEXT                 Host to run LNBits on
--forwarded-allow-ips TEXT  Allowed proxy servers
--ssl-keyfile TEXT          Path to SSL keyfile
--ssl-certfile TEXT         Path to SSL certificate
--help                      Show this message and exit.
```
> feat: remove magic argument parser from lnbits command

- lnbits/app.py
- lnbits/core/tasks.py
- lnbits/core/views/payment_api.py
- lnbits/core/views/websocket_api.py
- lnbits/server.py
- lnbits/settings.py
- lnbits/tasks.py
- lnbits/utils/cache.py
- lnbits/wallets/alby.py
- lnbits/wallets/cliche.py
- lnbits/wallets/corelightning.py
- lnbits/wallets/corelightningrest.py
- lnbits/wallets/eclair.py
- lnbits/wallets/fake.py
- lnbits/wallets/lnbits.py
- lnbits/wallets/lndgrpc.py
- lnbits/wallets/lndrest.py
- lnbits/wallets/lnpay.py
- lnbits/wallets/lntips.py
- lnbits/wallets/opennode.py
- lnbits/wallets/spark.py
- lnbits/wallets/zbd.py
https://github.com/lnbits/lnbits/issues/2399
There should be no `while True` loops in the app.
Instead `while settings.lnbits_runing:` should be used.
On the shutdown signal do `settings.lnbits_runing = False`.
This change also helps while testing. Previous infinite loops can no be stoped.
> feat: add `settings.lnbits_running `

- tests/unit/test_services_fees.py
> test: add unit for fee_reserve and service_fee

- lnbits/wallets/eclair.py
- lnbits/wallets/lndrest.py
- tests/wallets/fixtures/json/fixtures_rest.json
- tests/wallets/fixtures/models.py
- tests/wallets/test_rest_wallets.py
Continuation of https://github.com/lnbits/lnbits/pull/2396
TLDR;
- only `lnbits/wallets/eclair.py` needs serious reviewing, the rest of the changes are tests
- `lnbits/wallets/eclair.py` is only refactored to better handle errors (no functional changes added)
Note:
- one small change was made to `lndrest.py` for consistency reasons (give same response as other funding sources).
> [test] add tests for `eclair` funding source

- lnbits/wallets/lnbits.py
- tests/wallets/fixtures/json/fixtures_rest.json
Continuation of https://github.com/lnbits/lnbits/pull/2396
TLDR;
- only `lnbits/wallets/lnbits.py` needs serious reviewing, the rest of the changes are tests
- `lnbits/wallets/lnbits.py` is only refactored to better handle errors (no functional changes added)
> [test] add tests for `lnbits` funding source

- .prettierignore
- Makefile
- README.md
- docs/devs/api.md
- docs/devs/development.md
- docs/devs/extensions.md
- docs/devs/swagger.html
- docs/devs/websockets.md
- docs/guide/admin_ui.md
- docs/guide/extension-install.md
- docs/guide/faq.md
- docs/guide/fastapi_transition.md
- docs/guide/installation.md
- docs/guide/wallets.md
- docs/index.md
- tests/wallets/fixtures/json/fixtures_rest.json
- tests/wallets/fixtures/json/fixtures_rpc.json
we only checked `lnbits` dir before
> chore: use prettier for all of the codebase

- .github/workflows/regtest.yml
already is done inside regtest
> fix: no need to create fake admin

- Dockerfile
postgres client install was failing for bullseye, i think its time
> feat: update docker image to debian 12 (bookwork)

- lnbits/app.py
- lnbits/helpers.py
- lnbits/utils/logger.py
just some simply refactoring to clean up app.py
> refactor: move logger function from `app.py` to `utils/logger.py`

- lnbits/settings.py
Show in alphabetical order in the UI.
> chore: sort funding sources

- tests/regtest/conftest.py
- tests/regtest/test_services_create_invoice.py
- tests/regtest/test_services_pay_invoice.py
more tests for regtest `services.py`
> test: services create and pay invoice

- lnbits/static/js/admin.js
> fix: add admin ui methods back

- .env.example
- README.md
- docs/devs/api.md
- docs/devs/swagger.html
- docs/devs/websockets.md
- docs/guide/admin_ui.md
- docs/guide/faq.md
- docs/guide/installation.md
- lnbits/core/templates/core/index.html
- lnbits/settings.py
some old `legend` text still present
> [chore] Update `legend` to `demo`

- lnbits/core/crud.py
- lnbits/core/migrations.py
- lnbits/core/views/webpush_api.py
Reported here: https://github.com/lnbits/lnbits/issues/2531
Changes:
- replace in all SQL queries `user = ?` with `"user"" = ?`
- add `try-except` for `webpush_api` enpoints
> [fix] SQL error for `create webpush notification`

- lnbits/core/crud.py
- lnbits/core/views/webpush_api.py
- tests/api/test_webpush_api.py
Make sure this does not happen again: https://github.com/lnbits/lnbits/pull/2533
> [test] `webpush_api` endpoints

- .github/workflows/release.yml
- Dockerfile
issues in release action
https://github.com/lnbits/lnbits/actions/runs/9855301099
> fix: lib secp256k fails building

- lnbits/settings.py
- lnbits/wallets/blink.py
- tests/wallets/test_blink.py
Review code and refactor ocasiaonally.
> Blink review 01

- .dockerignore
- Dockerfile
Closes #2573
By doing a multi-stage Docker build, the size of the final image is reduced by ~45%.
> chore: optimize Dockerfile

- pyproject.toml
this is needed for testing the new lndhub version
> chore: bump version to 0.12.11

- lnbits/core/views/user_api.py
thanks for reporting, that was a serious bug. the indentation was wrong
closes #2598
> bug: removing admin user was not persistent

- lnbits/utils/exchange_rates.py
closes #2600
adds a list of currencies to exclude per provider, gets rid of 400 request and warnings in the logs
> feat: add `exclude_to` list for btcprice providers

- lnbits/wallets/zbd.py
Possible fix to https://github.com/lnbits/lnbits/issues/2457
modify description_hash/unhashed_desc for lnurlp payments
> Fix for LNURLp with ZBD wallet 

- tests/wallets/fixtures/json/fixtures_rest.json
- tests/wallets/test_rest_wallets.py
- tests/wallets/test_rpc_wallets.py
> feat: extra log for tests phases

- Makefile
- lnbits/core/services.py
- lnbits/exceptions.py
- lnbits/tasks.py
- tests/regtest/test_real_invoice.py
- fixed flaky regtest
- change success logs on successful invoices and payments
- clena up some unecessary logs
> test: fix flaky regtest

- tests/regtest/test_real_invoice.py
> fix: still flaky regtest

- .github/workflows/release-rc.yml
- pushes docker tag
- pushes to pypi for extensions to update
- generates a prerelease on github
> feat: add release flow for release candidates

- .github/workflows/nix.yml
we want cachix cache to work for pull requests too
> fix: run cachix nix action for all branches

- lnbits/db.py
- lnbits/helpers.py
those helpers are used in boltz extension and they did not take dates into consideration yet
> fix: db helpers to be used with timestamps

- lnbits/core/__init__.py
- lnbits/wallets/__init__.py
- lnbits/wallets/macaroon/__init__.py
- pyproject.toml
- remove ruff linting exception
> feat: use __all__ to export deps from `__init__.py`

- lnbits/wallets/__init__.py
> fix: export nwc wallet

- lnbits/core/templates/core/index.html
- lnbits/core/views/generic.py
> fix: add back lnurl wallet

- lnbits/core/views/api.py
this is already used and implemented by tpos, lnurlp and i probably need it for satspay aswell
> feat: add rate endpoint per currency

- lnbits/core/templates/core/extensions.html
Extensions will need it also
Fix #2517
> show wallet names in dropdown

- lnbits/core/templates/core/_api_docs.html
> Fix documentation on decode API

- docs/devs/development.md
fixes https://github.com/lnbits/lnbits/issues/2651
> chore: update install instructions for developers

- lnbits/core/templates/admin/_tab_security.html
- lnbits/core/templates/admin/_tab_users.html
Fix chips not having the remove functionality
Closes #2471
> fix chips on server page

- lnbits/static/js/wallet.js
Wrong string case search
Closes #1599
> Fix lnurl fallback

- lnbits/commands.py
- lnbits/core/helpers.py
commands.py should be used for cli commands
> refactor: move migrate_databases to core helpers

- .env.example
- package-lock.json
I don't see why this exists.
Tested uncommented and all sources are default available.
> Uncomment LNBITS_ALLOWED_FUNDING_SOURCES

- flake.lock
- flake.nix
- lnbits/core/views/generic.py
- poetry.lock
- pyproject.toml
- tests/wallets/helpers.py
- tools/i18n-ai-tool.py
i did not touch sqlalchemy since this is being worked on here: https://github.com/lnbits/lnbits/pull/2611
> chore: update pyproject dependencies

- lnbits/static/js/wallet.js
> fix: regeression on index.html

- lnbits/static/js/wallet.js
fix the hotfix to fix a fuckup
> fix: QR request case

- lnbits/core/services.py
- lnbits/core/views/user_api.py
- lnbits/exceptions.py
- lnbits/wallets/void.py
catch with on fastapi errorhandler
follow up on https://github.com/lnbits/lnbits/pull/2673
> feat: introduce `VoidWalletError`

- lnbits/core/templates/users/index.html
- lnbits/static/js/users.js
Improvements to the user chart:
+ Added more descriptive chart label
+ Added axis labels
+ Improved text formatting on data point tooltips 
+ Added admin toggle bg colour to avoid white on white colour scheme
Tested on IRL instance. See below.
> feat: UI / UX improvements to Users balance / tx chart

- docs/guide/installation.md
- lnbits.sh
continuation of https://github.com/lnbits/lnbits/pull/2664
> feat: add lnbits.sh install bash script

- docs/guide/installation.md
- lnbits.sh
continuation of https://github.com/lnbits/lnbits/pull/2664
> feat: install lnbits.sh bash script

- lnbits/core/models.py
> fix: internal payment can still be pending

- .github/workflows/release-rc.yml
> ci: do not create gh release on rc's

- .env.example
- Makefile
- lnbits/settings.py
- tools/create_fake_admin.py
> feat: make LNBITS_ADMIN_UI the default

- lnbits/wallets/boltz.py
> fix(boltz): check for direct onchain payments

- lnbits/core/views/api.py
Original Request: https://github.com/lnbits/lnbits/issues/2735
A new endpoint has been created: `GET http://127.0.0.1:5000/api/v1/status`
**Request example**:
```
curl --location 'http://127.0.0.1:5000/api/v1/status' \
--header 'x-api-key: 7ca987071ab847d3b7676d71ed5dc12d'
```
This endpoint requires the `invoice key` of a user.
Different responses are returned depending if the `invoice key` belongs to an admin user or not.
**Response for regular user (non admin)**:
```json
{
"server_time": 1728985995,
"up_time": 209,
"version": "1.0.0rc4"
}
```
**Response for admin**:
- when the funding source is connected:
```json
{
"server_time": 1728986208,
"up_time": 47,
"version": "1.0.0rc4",
"funding_source": "LNbitsWallet",
"funding_source_error": null,
"funding_source_balance_msat": 3105756
}
``` …
> feat: add server status endpoint

- lnbits/tasks.py
> fix: catch_everything_and_restart

- lnbits/core/models.py
> fix: default timestamp on models

- lnbits/db.py
Corner case for dict to model.
> fix: handle list models

- lnbits/static/js/node.js
> fix: date format

- lnbits/core/templates/admin/_tab_security_notifications.html
- lnbits/core/templates/core/extensions.html
> fix: vue3 changes

- lnbits/core/templates/admin/_tab_extensions.html
- lnbits/core/templates/admin/_tab_security.html
- lnbits/core/templates/admin/_tab_users.html
- lnbits/core/templates/admin/index.html
- lnbits/static/js/admin.js
> fix: some ui bugs

- lnbits/core/services/payments.py
- lnbits/decorators.py
db connection wasnt passed to `get_user_active_extensions_id`. and in some contexts nested db connection will stuck the server
> fix: stuck pay_invoice

- .github/actions/prepare/action.yml
- .github/workflows/ci.yml
- poetry.lock
- pyproject.toml
- tests/api/test_admin_api.py
- tests/api/test_api.py
- tests/api/test_auth.py
- tests/api/test_generic.py
- tests/api/test_public_api.py
- tests/api/test_webpush_api.py
- tests/conftest.py
- tests/regtest/conftest.py
- tests/regtest/test_real_invoice.py
- tests/regtest/test_services_create_invoice.py
- tests/regtest/test_services_pay_invoice.py
- tests/regtest/test_x_node_api.py
- tests/unit/test_cache.py
- tests/unit/test_db.py
- tests/unit/test_db_fetch_page.py
- tests/unit/test_helpers_query.py
- tests/unit/test_pay_invoice.py
- tests/unit/test_services_fees.py
- tests/unit/test_services_wallet_limit.py
- tests/wallets/test_blink.py
- tests/wallets/test_nwc_wallets.py
- tests/wallets/test_rest_wallets.py
- tests/wallets/test_rpc_wallets.py
possible solution for failing CI https://github.com/lnbits/lnbits/pull/2797
> chore: update to latest pytest

- lnbits/templates/base.html
> fix: error on custom badge

- .github/workflows/ci.yml
- lnbits/nodes/lndrest.py
- tests/regtest/conftest.py
- tests/regtest/helpers.py
- tests/regtest/test_real_invoice.py
- tests/regtest/test_x_node_api.py
something broke when updating to anyio
> test: fix lndrest on regtest

- lnbits/commands.py
- lnbits/core/models/extensions.py
fixes: `poetry run lnbits-cli extensions update -a`
> fix: ext upgrade from `lnbits-cli`

- .github/workflows/jmeter.yml
> test: fix jmeter for ci

- lnbits/core/views/api.py
- lnbits/utils/exchange_rates.py
Introduce `get_fiat_rate_and_price_satoshis`
> fix: backwards compatible `get_fiat_rate_satoshis`

- lnbits/core/crud/payments.py
- lnbits/core/views/payment_api.py
- tests/unit/test_crud_payments.py
fixed by https://github.com/lnbits/lnbits/pull/2841
> fix: get_payments where clause does query wrong payments including tests

- .github/workflows/regtest.yml
branch on regtest repo was temporarly changed for cln update
> test: use regtest main again

- lnbits/core/templates/admin/index.html
- lnbits/core/templates/audit/index.html
- lnbits/core/templates/core/extensions.html
Part of the break up of https://github.com/lnbits/lnbits/pull/2817
> feat: standardises top spacing of page layout

- lnbits/core/templates/core/wallet.html
- lnbits/static/js/wallet.js
Part of the break up of https://github.com/lnbits/lnbits/pull/2817
https://github.com/user-attachments/assets/2ce8bc6b-8017-45f5-995d-0193722f6ffe
> Added top cards

- lnbits/templates/components.vue
Part of the break up of https://github.com/lnbits/lnbits/pull/2817
Old version:
> feat: moved search inside the transaction table

- lnbits/core/models/users.py
- lnbits/core/views/auth_api.py
- lnbits/decorators.py
- tests/api/test_admin_api.py
- tests/api/test_auth.py
- tests/conftest.py
- tests/regtest/test_x_node_api.py
> feat: do not allow `user_id_only` login for admins

- lnbits/wallets/phoenixd.py
Translate expiry to expirySeconds for Phoenixd and add a default of 1 hour if not set
> Translate expiry to expirySeconds for Phoenixd

- docs/guide/installation.md
Means a copy/paste will work for most
> Tweak: Updated Poetry install to include headers and make copy/paste easier

- lnbits/static/js/wallet.js
I think it works, getting sqlite error so cant test
> adds gradient

- lnbits/templates/base.html
Global theme works for public pages.
> Tweak: Removes profile dropdown for public pages

- lnbits/core/templates/core/wallet.html
- lnbits/static/js/wallet.js
> Change UI for Pay Invoice Dialog

- lnbits/core/templates/admin/_tab_funding.html
funding tab was not working if you had node ui enabled
> bug: settings fundingtab errors

- lnbits/core/templates/admin/_tab_theme.html
fix missing = sign on admin settings on denomination.
it was assigning instead of comparing
> Fix: compare not assign

- lnbits/core/templates/core/index.html
Hide the description on small screens
> [Fix] Hide text on small screen

- lnbits/core/services/notifications.py
> Revert "tweak: fix for ws payment"

- lnbits/core/services/users.py
- lnbits/core/views/user_api.py
Issue reported here: https://github.com/lnbits/lnbits/issues/3058
> fix: add default extensions when a user is created

- lnbits/decorators.py
closes https://github.com/lnbits/lnbits/pull/3050
> fix: make swagger understand the access token `HTTPBearer`

- lnbits/app.py
- lnbits/core/models/misc.py
- lnbits/core/templates/admin/_tab_library.html
- lnbits/core/views/admin_api.py
- lnbits/helpers.py
- lnbits/server.py
- lnbits/settings.py
- lnbits/static/js/admin.js
- poetry.lock
- pyproject.toml
- tests/unit/test_upload_file_path.py
just to keep it clean :)
- added filesize and types to settings
- validate for path travels
- dont allow subdirs
- tests
> feat: cleanup on library dir creation and upload endpoints

- lnbits/core/views/user_api.py
> feat: do not allow regular admins to edit super user

- lnbits/wallets/phoenixd.py
- tests/wallets/fixtures/json/fixtures_rest.json
fees should be msat, we where off by a factor 100
> fix: phoenixd uses `sat` instead of `msat` for `pay_invoice`

- lnbits/templates/components.vue
> fix dialog consistency

- lnbits/wallets/fake.py
i think its not an issue, but just to be correct lets not expose the fake `preimage` in the payment_secret
> fix: FakeWallet, bolt11 payment_secret is not the preimage

- pyproject.toml
> chore: update LNbits to version v1.0.0

- docs/guide/installation.md
- lnbits.sh
Co-authored-by: arcbtc <ben@arc.wales>
> feat: install lnbits.sh bash script (#2684)

- lnbits/core/services/payments.py
- lnbits/static/js/payments.js
- lnbits/static/js/wallet.js
Fixes error reported here: https://github.com/lnbits/lnbits/issues/3103
Also fixes wrong order of labels:
> [fix] offset naive dates error

- lnbits/wallets/alby.py
- lnbits/wallets/blink.py
- lnbits/wallets/breez.py
- lnbits/wallets/cliche.py
- lnbits/wallets/corelightning.py
- lnbits/wallets/corelightningrest.py
- lnbits/wallets/eclair.py
- lnbits/wallets/lnbits.py
- lnbits/wallets/lndgrpc.py
- lnbits/wallets/lndrest.py
- lnbits/wallets/lnpay.py
- lnbits/wallets/lntips.py
- lnbits/wallets/nwc.py
- lnbits/wallets/opennode.py
- lnbits/wallets/phoenixd.py
- lnbits/wallets/spark.py
- lnbits/wallets/zbd.py
- refactor the wallets to kwargs instead of arguments, to make them more readable and flexible
- should be the same as before
> refactor: fundingsource Invoice-, PaymentResponses

- lnbits/core/views/auth_api.py
Fixes: https://github.com/lnbits/lnbits/issues/3122
> fix: set explicit `max_age` for cookies

- docs/guide/installation.md
> docs: add notes about freeBSD install

- docs/guide/installation.md
Please comment and amend. Many users are now days reading docs page.
> [doc] Update installation.md to match v1.0.x requirements

- lnbits/wallets/lndgrpc.py
- lnbits/wallets/lndrest.py
> fix: lnd/lndrest failed canceled/expired invoices

- lnbits/db.py
Testing an issue reported by users migrating from pre-v1 to v1.
Reported here: https://github.com/lnbits/lnbits/issues/3135
> fix: safe json conversion

- docs/guide/wallets.md
- lnbits/commands.py
- lnbits/helpers.py
- lnbits/utils/crypto.py
- lnbits/wallets/lndgrpc.py
- lnbits/wallets/lndrest.py
- lnbits/wallets/macaroon/macaroon.py
- tests/unit/test_crypto_aes.py
clean up the relation from lnd's load_macaroon function and utils/crypto.py AEScipher
- rename some variables/function names in AEScipher class to be more descriptive
- moves macaroon encryption to lnbits-cli
- adds aes en-/decrytion to lnbits-cli
> refactor: untangle lnd's macaroon encryption with AESCipher class

- tests/conftest.py
just stay under 1 million to not run into those
lnbits_max_outgoing_payment_amount_sats: int = Field(default=10_000_000, ge=0)
lnbits_max_incoming_payment_amount_sats: int = Field(default=10_000_000, ge=0)
> test: conftest smaller funding amounts

- lnbits/core/services/payments.py
Show more info for the service fee payment:
> feat: better service fee payment memo

- lnbits/core/views/node_api.py
Reported here: https://github.com/lnbits/lnbits/issues/3175
> fix: handle node absent in 1ml.com

- lnbits/core/templates/payments/index.html
- lnbits/static/js/payments.js
Add a better status filter method, like in wallet page
> [feat] Add payment status filters

- poetry.lock
- pyproject.toml
> feat: add `nostr-sdk` library

- lnbits/static/js/payments.js
Display the unit in sats in the payments table
Closes #3233
> [Fix] Display fee in sats

- lnbits/wallets/breez.py
- lnbits/wallets/breez_liquid.py
- pyproject.toml
- fix typing
- compabtibily issue on package update
- listerener as in BreezLiquidWallet
> fix: update and fixes for `BreezWallet`

- lnbits/app.py
- lnbits/core/services/notifications.py
- lnbits/core/tasks.py
- lnbits/wallets/blink.py
- lnbits/wallets/boltz.py
- lnbits/wallets/nwc.py
- lnbits/wallets/strike.py
- tests/unit/test_crud_payments.py
> chore: get rid of mypy notes and typecheck more functions

- lnbits/static/js/wallet.js
> fix: frontend withdraw error message

- lnbits/core/models/lnurl.py
added LnAddress model, introduce #3289
> fix: lnaddresses on new lnurlscan POST endpoint

- lnbits/helpers.py
This pr broke https://github.com/lnbits/lnbits/pull/3014
> Fix: fake wallet

- lnbits/core/views/extension_api.py
> fix: mispelling in logs #3306

- lnbits/core/views/user_api.py
- lnbits/helpers.py
- tests/api/test_users.py
> feat: allow creating/update user with nostr `npub1` pubkey

- lnbits/core/views/lnurl_api.py
- poetry.lock
- pyproject.toml
- uv.lock
> chore: update lnurl to v0.8.0

- lnbits/core/services/notifications.py
- lnbits/core/services/websockets.py
- lnbits/core/views/websocket_api.py
- change signature to id - data
- add has_connection
- add get_connections
- add receive
> feat: add `has_connection`, `listen` and `receive_queue` to websocket_manager

- .github/workflows/lint.yml
- .github/workflows/poetry.yml
- poetry.lock
- ci for checking poetry.lock
- release failed because of outdated lock
> CI: add poetry lock file check job and update poetry lock
